.TH "src/rapidjson/test/unittest/allocatorstest.cpp" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/allocatorstest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/allocators\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <functional>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTestStdAllocatorData\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBAllocator\fP > void \fBTestAllocator\fP (\fBAllocator\fP &\fBa\fP)"
.br
.ti -1c
.RI "template<typename \fBAllocator\fP > void \fBTestStdAllocator\fP (const \fBAllocator\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBAllocator\fP, \fBCrtAllocator\fP)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBAllocator\fP, \fBMemoryPoolAllocator\fP)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBAllocator\fP, Alignment)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBAllocator\fP, Issue399)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (\fBAllocator\fP, Alignment)"

.SS "TEST (\fBAllocator\fP, \fBCrtAllocator\fP)"

.SS "TEST (\fBAllocator\fP, Issue399)"

.SS "TEST (\fBAllocator\fP, \fBMemoryPoolAllocator\fP)"

.SS "template<typename \fBAllocator\fP > void TestAllocator (\fBAllocator\fP & a)"

.SS "template<typename \fBAllocator\fP > void TestStdAllocator (const \fBAllocator\fP & a)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
