.TH "src/rapidjson/example/archiver/archiver.cpp" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/example/archiver/archiver.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'archiver\&.h'\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <stack>\fP
.br
\fC#include 'rapidjson/document\&.h'\fP
.br
\fC#include 'rapidjson/prettywriter\&.h'\fP
.br
\fC#include 'rapidjson/stringbuffer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBJsonReaderStackItem\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDOCUMENT\fP   reinterpret_cast<\fBDocument\fP*>(mDocument)"
.br
.ti -1c
.RI "#define \fBSTACK\fP   (reinterpret_cast<\fBJsonReaderStack\fP*>(mStack))"
.br
.ti -1c
.RI "#define \fBTOP\fP   (\fBSTACK\fP\->top())"
.br
.ti -1c
.RI "#define \fBCURRENT\fP   (*\fBTOP\&.value\fP)"
.br
.ti -1c
.RI "#define \fBWRITER\fP   reinterpret_cast<\fBPrettyWriter\fP<\fBStringBuffer\fP>*>(mWriter)"
.br
.ti -1c
.RI "#define \fBSTREAM\fP   reinterpret_cast<\fBStringBuffer\fP*>(mStream)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::stack< \fBJsonReaderStackItem\fP > \fBJsonReaderStack\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CURRENT   (*\fBTOP\&.value\fP)"

.SS "#define DOCUMENT   reinterpret_cast<\fBDocument\fP*>(mDocument)"

.SS "#define STACK   (reinterpret_cast<\fBJsonReaderStack\fP*>(mStack))"

.SS "#define STREAM   reinterpret_cast<\fBStringBuffer\fP*>(mStream)"

.SS "#define TOP   (\fBSTACK\fP\->top())"

.SS "#define WRITER   reinterpret_cast<\fBPrettyWriter\fP<\fBStringBuffer\fP>*>(mWriter)"

.SH "Typedef Documentation"
.PP 
.SS "typedef std::stack<\fBJsonReaderStackItem\fP> \fBJsonReaderStack\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
