.TH "src/rapidjson/example/archiver/archiver.h" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/example/archiver/archiver.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstddef>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJsonReader\fP"
.br
.RI "Represents a JSON reader which implements \fBArchiver\fP concept\&. "
.ti -1c
.RI "class \fBJsonWriter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
