.TH "ASCII< CharType >" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ASCII< CharType > \- \fBASCII\fP encoding\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <encodings\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBsupportUnicode\fP = 0 }"
.br
.ti -1c
.RI "typedef CharType \fBCh\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename OutputStream > static void \fBEncode\fP (OutputStream &os, unsigned codepoint)"
.br
.ti -1c
.RI "template<typename OutputStream > static void \fBEncodeUnsafe\fP (OutputStream &os, unsigned codepoint)"
.br
.ti -1c
.RI "template<typename InputStream > static bool \fBDecode\fP (InputStream &is, unsigned *codepoint)"
.br
.ti -1c
.RI "template<typename InputStream , typename OutputStream > static bool \fBValidate\fP (InputStream &is, OutputStream &os)"
.br
.ti -1c
.RI "template<typename InputByteStream > static CharType \fBTakeBOM\fP (InputByteStream &is)"
.br
.ti -1c
.RI "template<typename InputByteStream > static \fBCh\fP \fBTake\fP (InputByteStream &is)"
.br
.ti -1c
.RI "template<typename OutputByteStream > static void \fBPutBOM\fP (OutputByteStream &os)"
.br
.ti -1c
.RI "template<typename OutputByteStream > static void \fBPut\fP (OutputByteStream &os, \fBCh\fP c)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename CharType = char>
.br
struct ASCII< CharType >"\fBASCII\fP encoding\&. 

http://en.wikipedia.org/wiki/ASCII 
.PP
\fBTemplate Parameters\fP
.RS 4
\fICharType\fP Code unit for storing 7-bit \fBASCII\fP data\&. Default is char\&. 
.RE
.PP
\fBNote\fP
.RS 4
implements Encoding concept 
.RE
.PP

.SH "Member Typedef Documentation"
.PP 
.SS "template<typename CharType  = char> typedef CharType \fBASCII\fP< CharType >::Ch"

.SH "Member Enumeration Documentation"
.PP 
.SS "template<typename CharType  = char> anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIsupportUnicode \fP\fP
.SH "Member Function Documentation"
.PP 
.SS "template<typename CharType  = char> template<typename InputStream > static bool \fBASCII\fP< CharType >::Decode (InputStream & is, unsigned * codepoint)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename CharType  = char> template<typename OutputStream > static void \fBASCII\fP< CharType >::Encode (OutputStream & os, unsigned codepoint)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename CharType  = char> template<typename OutputStream > static void \fBASCII\fP< CharType >::EncodeUnsafe (OutputStream & os, unsigned codepoint)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename CharType  = char> template<typename OutputByteStream > static void \fBASCII\fP< CharType >::Put (OutputByteStream & os, \fBCh\fP c)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename CharType  = char> template<typename OutputByteStream > static void \fBASCII\fP< CharType >::PutBOM (OutputByteStream & os)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename CharType  = char> template<typename InputByteStream > static \fBCh\fP \fBASCII\fP< CharType >::Take (InputByteStream & is)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename CharType  = char> template<typename InputByteStream > static CharType \fBASCII\fP< CharType >::TakeBOM (InputByteStream & is)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename CharType  = char> template<typename InputStream , typename OutputStream > static bool \fBASCII\fP< CharType >::Validate (InputStream & is, OutputStream & os)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
