.TH "AssertException" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AssertException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <unittest\&.h>\fP
.PP
Inherits std::logic_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssertException\fP (const char *w)"
.br
.ti -1c
.RI "\fBAssertException\fP (const \fBAssertException\fP &rhs)"
.br
.ti -1c
.RI "virtual \fB~AssertException\fP ()  throw ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AssertException::AssertException (const char * w)\fC [inline]\fP"

.SS "AssertException::AssertException (const \fBAssertException\fP & rhs)\fC [inline]\fP"

.SS "AssertException::~AssertException ()\fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
