.TH "AutoUTFInputStream< CharType, InputByteStream >" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoUTFInputStream< CharType, InputByteStream > \- Input stream wrapper with dynamically bound encoding and automatic encoding detection\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <encodedstream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef CharType \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAutoUTFInputStream\fP (InputByteStream &is, \fBUTFType\fP type=\fBkUTF8\fP)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBUTFType\fP \fBGetType\fP () const"
.br
.ti -1c
.RI "bool \fBHasBOM\fP () const"
.br
.ti -1c
.RI "\fBCh\fP \fBPeek\fP () const"
.br
.ti -1c
.RI "\fBCh\fP \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP () const"
.br
.ti -1c
.RI "void \fBPut\fP (\fBCh\fP)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "\fBCh\fP * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (\fBCh\fP *)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename CharType, typename InputByteStream>
.br
class AutoUTFInputStream< CharType, InputByteStream >"Input stream wrapper with dynamically bound encoding and automatic encoding detection\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fICharType\fP Type of character for reading\&. 
.br
\fIInputByteStream\fP type of input byte stream to be wrapped\&. 
.RE
.PP

.SH "Member Typedef Documentation"
.PP 
.SS "template<typename CharType , typename InputByteStream > typedef CharType \fBAutoUTFInputStream\fP< CharType, InputByteStream >::Ch"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename CharType , typename InputByteStream > \fBAutoUTFInputStream\fP< CharType, InputByteStream >\fB::AutoUTFInputStream\fP (InputByteStream & is, \fBUTFType\fP type = \fC\fBkUTF8\fP\fP)\fC [inline]\fP"

.PP
Constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIis\fP input stream to be wrapped\&. 
.br
\fItype\fP UTF encoding type if it is not detected from the stream\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<typename CharType , typename InputByteStream > void \fBAutoUTFInputStream\fP< CharType, InputByteStream >::Flush ()\fC [inline]\fP"

.SS "template<typename CharType , typename InputByteStream > \fBUTFType\fP \fBAutoUTFInputStream\fP< CharType, InputByteStream >::GetType () const\fC [inline]\fP"

.SS "template<typename CharType , typename InputByteStream > bool \fBAutoUTFInputStream\fP< CharType, InputByteStream >::HasBOM () const\fC [inline]\fP"

.SS "template<typename CharType , typename InputByteStream > \fBCh\fP \fBAutoUTFInputStream\fP< CharType, InputByteStream >::Peek () const\fC [inline]\fP"

.SS "template<typename CharType , typename InputByteStream > void \fBAutoUTFInputStream\fP< CharType, InputByteStream >::Put (\fBCh\fP)\fC [inline]\fP"

.SS "template<typename CharType , typename InputByteStream > \fBCh\fP * \fBAutoUTFInputStream\fP< CharType, InputByteStream >::PutBegin ()\fC [inline]\fP"

.SS "template<typename CharType , typename InputByteStream > size_t \fBAutoUTFInputStream\fP< CharType, InputByteStream >::PutEnd (\fBCh\fP *)\fC [inline]\fP"

.SS "template<typename CharType , typename InputByteStream > \fBCh\fP \fBAutoUTFInputStream\fP< CharType, InputByteStream >::Take ()\fC [inline]\fP"

.SS "template<typename CharType , typename InputByteStream > size_t \fBAutoUTFInputStream\fP< CharType, InputByteStream >::Tell () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
