.TH "BasicOStreamWrapper< StreamType >" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BasicOStreamWrapper< StreamType > \- Wrapper of \fCstd::basic_ostream\fP into RapidJSON's Stream concept\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ostreamwrapper\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef StreamType::char_type \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBasicOStreamWrapper\fP (StreamType &stream)"
.br
.ti -1c
.RI "void \fBPut\fP (\fBCh\fP c)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "char \fBPeek\fP () const"
.br
.ti -1c
.RI "char \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP () const"
.br
.ti -1c
.RI "char * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (char *)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename StreamType>
.br
class BasicOStreamWrapper< StreamType >"Wrapper of \fCstd::basic_ostream\fP into RapidJSON's Stream concept\&. 

The classes can be wrapped including but not limited to:
.PP
.IP "\(bu" 2
\fCstd::ostringstream\fP 
.IP "\(bu" 2
\fCstd::stringstream\fP 
.IP "\(bu" 2
\fCstd::wpstringstream\fP 
.IP "\(bu" 2
\fCstd::wstringstream\fP 
.IP "\(bu" 2
\fCstd::ifstream\fP 
.IP "\(bu" 2
\fCstd::fstream\fP 
.IP "\(bu" 2
\fCstd::wofstream\fP 
.IP "\(bu" 2
\fCstd::wfstream\fP 
.PP
.PP
\fBTemplate Parameters\fP
.RS 4
\fIStreamType\fP Class derived from \fCstd::basic_ostream\fP\&. 
.RE
.PP

.SH "Member Typedef Documentation"
.PP 
.SS "template<typename StreamType > typedef StreamType::char_type \fBBasicOStreamWrapper\fP< StreamType >::Ch"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename StreamType > \fBBasicOStreamWrapper\fP< StreamType >\fB::BasicOStreamWrapper\fP (StreamType & stream)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename StreamType > void \fBBasicOStreamWrapper\fP< StreamType >::Flush ()\fC [inline]\fP"

.SS "template<typename StreamType > char \fBBasicOStreamWrapper\fP< StreamType >::Peek () const\fC [inline]\fP"

.SS "template<typename StreamType > void \fBBasicOStreamWrapper\fP< StreamType >::Put (\fBCh\fP c)\fC [inline]\fP"

.SS "template<typename StreamType > char * \fBBasicOStreamWrapper\fP< StreamType >::PutBegin ()\fC [inline]\fP"

.SS "template<typename StreamType > size_t \fBBasicOStreamWrapper\fP< StreamType >::PutEnd (char *)\fC [inline]\fP"

.SS "template<typename StreamType > char \fBBasicOStreamWrapper\fP< StreamType >::Take ()\fC [inline]\fP"

.SS "template<typename StreamType > size_t \fBBasicOStreamWrapper\fP< StreamType >::Tell () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
