.TH "src/rapidjson/test/unittest/bigintegertest.cpp" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/bigintegertest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/internal/biginteger\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBIGINTEGER_LITERAL\fP(s)   BigInteger(s, sizeof(s) \- 1)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (BigInteger, Constructor)"
.br
.ti -1c
.RI "\fBTEST\fP (BigInteger, AddUint64)"
.br
.ti -1c
.RI "\fBTEST\fP (BigInteger, MultiplyUint64)"
.br
.ti -1c
.RI "\fBTEST\fP (BigInteger, MultiplyUint32)"
.br
.ti -1c
.RI "\fBTEST\fP (BigInteger, LeftShift)"
.br
.ti -1c
.RI "\fBTEST\fP (BigInteger, Compare)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BIGINTEGER_LITERAL(s)   BigInteger(s, sizeof(s) \- 1)"

.SH "Function Documentation"
.PP 
.SS "TEST (BigInteger, AddUint64)"

.SS "TEST (BigInteger, Compare)"

.SS "TEST (BigInteger, Constructor)"

.SS "TEST (BigInteger, LeftShift)"

.SS "TEST (BigInteger, MultiplyUint32)"

.SS "TEST (BigInteger, MultiplyUint64)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
