.TH "Bullet" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bullet
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Bullet\&.h>\fP
.PP
Inherits \fBProjectile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBullet\fP (sf::Vector2f pos, bool movingRight)"
.br
.ti -1c
.RI "void \fBupdate\fP (float deltaTime) override"
.br
.RI "Aktualizacja logiki pocisku\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBmove\fP () override"
.br
.RI "Porusza pociskiem w odpowiedni sposób\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBspeed\fP"
.br
.RI "Prędkość lecącego pocisku\&. "
.ti -1c
.RI "float \fBspeedRate\fP"
.br
.RI "Modyfikator prędkości pocisku\&. "
.ti -1c
.RI "float \fBspeedFallRate\fP"
.br
.RI "Wartość, o którą co klatkę zmniejsza się speedRate\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bullet::Bullet (sf::Vector2f pos, bool movingRight)"
Konstruktor pocisku gracza 
.PP
\fBParameters\fP
.RS 4
\fIpos\fP początkowa pozycja pocisku na mapie 
.br
\fImovingRight\fP określa, czy pocisk leci w prawo 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Bullet::move ()\fC [override]\fP, \fC [private]\fP, \fC [virtual]\fP"

.PP
Porusza pociskiem w odpowiedni sposób\&. 
.PP
Implements \fBProjectile\fP\&.
.SS "void Bullet::update (float deltaTime)\fC [override]\fP, \fC [virtual]\fP"

.PP
Aktualizacja logiki pocisku\&. 
.PP
Reimplemented from \fBProjectile\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float Bullet::speed\fC [private]\fP"

.PP
Prędkość lecącego pocisku\&. 
.SS "float Bullet::speedFallRate\fC [private]\fP"

.PP
Wartość, o którą co klatkę zmniejsza się speedRate\&. 
.SS "float Bullet::speedRate\fC [private]\fP"

.PP
Modyfikator prędkości pocisku\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
