.TH "Canvas" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Canvas
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCanvas\fP ()"
.br
.ti -1c
.RI "\fB~Canvas\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBAddShape\fP (\fBShape\fP *shape)"
.br
.ti -1c
.RI "void \fBPrint\fP (std::ostream &os)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBShape\fP * > \fBshapes_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename \fBArchiver\fP > \fBArchiver\fP & \fBoperator&\fP (\fBArchiver\fP &ar, \fBCanvas\fP &c)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Canvas::Canvas ()\fC [inline]\fP"

.SS "Canvas::~Canvas ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Canvas::AddShape (\fBShape\fP * shape)\fC [inline]\fP"

.SS "void Canvas::Clear ()\fC [inline]\fP"

.SS "void Canvas::Print (std::ostream & os)\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename \fBArchiver\fP > \fBArchiver\fP & operator& (\fBArchiver\fP & ar, \fBCanvas\fP & c)\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBShape\fP*> Canvas::shapes_\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
