.TH "Circle" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShape\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCircle\fP ()"
.br
.ti -1c
.RI "\fBCircle\fP (double x, double y, double radius)"
.br
.ti -1c
.RI "\fB~Circle\fP ()"
.br
.ti -1c
.RI "const char * \fBGetType\fP () const"
.br
.ti -1c
.RI "void \fBPrint\fP (std::ostream &os) const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBradius_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename \fBArchiver\fP > \fBArchiver\fP & \fBoperator&\fP (\fBArchiver\fP &ar, \fBCircle\fP &c)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Circle::Circle ()\fC [inline]\fP"

.SS "Circle::Circle (double x, double y, double radius)\fC [inline]\fP"

.SS "Circle::~Circle ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const char * Circle::GetType () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBShape\fP\&.
.SS "void Circle::Print (std::ostream & os) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBShape\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename \fBArchiver\fP > \fBArchiver\fP & operator& (\fBArchiver\fP & ar, \fBCircle\fP & c)\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double Circle::radius_\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
