.TH "src/rapidjson/include/rapidjson/internal/clzll.h" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/internal/clzll.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./rapidjson\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinternal\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRAPIDJSON_CLZLL\fP   RAPIDJSON_NAMESPACE::internal::clzll"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBinternal::clzll\fP (\fBuint64_t\fP x)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RAPIDJSON_CLZLL   RAPIDJSON_NAMESPACE::internal::clzll"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
