.TH "src/rapidjson/example/condense/condense.cpp" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/example/condense/condense.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'rapidjson/reader\&.h'\fP
.br
\fC#include 'rapidjson/writer\&.h'\fP
.br
\fC#include 'rapidjson/filereadstream\&.h'\fP
.br
\fC#include 'rapidjson/filewritestream\&.h'\fP
.br
\fC#include 'rapidjson/error/en\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int, char *[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int, char *[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
