.TH "src/rapidjson/include/rapidjson/cursorstreamwrapper.h" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/cursorstreamwrapper.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stream\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCursorStreamWrapper< InputStream, Encoding >\fP"
.br
.RI "Cursor stream wrapper for counting line and column number if error exists\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
