.TH "src/rapidjson/test/unittest/cursorstreamwrappertest.cpp" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/cursorstreamwrappertest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/document\&.h'\fP
.br
\fC#include 'rapidjson/cursorstreamwrapper\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBtestJson\fP (const char *json, size_t &line, size_t &col)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCursorStreamWrapper\fP, MissingFirstBracket)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCursorStreamWrapper\fP, MissingQuotes)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCursorStreamWrapper\fP, MissingColon)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCursorStreamWrapper\fP, MissingSecondQuotes)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCursorStreamWrapper\fP, MissingComma)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCursorStreamWrapper\fP, MissingArrayBracket)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCursorStreamWrapper\fP, MissingArrayComma)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCursorStreamWrapper\fP, MissingLastArrayBracket)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCursorStreamWrapper\fP, MissingLastBracket)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (\fBCursorStreamWrapper\fP, MissingArrayBracket)"

.SS "TEST (\fBCursorStreamWrapper\fP, MissingArrayComma)"

.SS "TEST (\fBCursorStreamWrapper\fP, MissingColon)"

.SS "TEST (\fBCursorStreamWrapper\fP, MissingComma)"

.SS "TEST (\fBCursorStreamWrapper\fP, MissingFirstBracket)"

.SS "TEST (\fBCursorStreamWrapper\fP, MissingLastArrayBracket)"

.SS "TEST (\fBCursorStreamWrapper\fP, MissingLastBracket)"

.SS "TEST (\fBCursorStreamWrapper\fP, MissingQuotes)"

.SS "TEST (\fBCursorStreamWrapper\fP, MissingSecondQuotes)"

.SS "bool testJson (const char * json, size_t & line, size_t & col)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
