.TH "CursorStreamWrapper< InputStream, Encoding >" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CursorStreamWrapper< InputStream, Encoding > \- Cursor stream wrapper for counting line and column number if error exists\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cursorstreamwrapper\&.h>\fP
.PP
Inherits \fBGenericStreamWrapper< InputStream, UTF8<> >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Encoding::Ch \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCursorStreamWrapper\fP (InputStream &is)"
.br
.ti -1c
.RI "\fBCh\fP \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBGetLine\fP () const"
.br
.RI "Get the error line number, if error exists\&. "
.ti -1c
.RI "size_t \fBGetColumn\fP () const"
.br
.RI "Get the error column number, if error exists\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "size_t \fBline_\fP"
.br
.RI "Current Line\&. "
.ti -1c
.RI "size_t \fBcol_\fP"
.br
.RI "Current Column\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename InputStream, typename \fBEncoding\fP = UTF8<>>
.br
class CursorStreamWrapper< InputStream, Encoding >"Cursor stream wrapper for counting line and column number if error exists\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIInputStream\fP Any stream that implements Stream Concept 
.RE
.PP

.SH "Member Typedef Documentation"
.PP 
.SS "template<typename InputStream , typename \fBEncoding\fP  = UTF8<>> typedef Encoding::Ch \fBCursorStreamWrapper\fP< InputStream, \fBEncoding\fP >::Ch"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename InputStream , typename \fBEncoding\fP  = UTF8<>> \fBCursorStreamWrapper\fP< InputStream, \fBEncoding\fP >\fB::CursorStreamWrapper\fP (InputStream & is)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename InputStream , typename \fBEncoding\fP  = UTF8<>> size_t \fBCursorStreamWrapper\fP< InputStream, \fBEncoding\fP >::GetColumn () const\fC [inline]\fP"

.PP
Get the error column number, if error exists\&. 
.SS "template<typename InputStream , typename \fBEncoding\fP  = UTF8<>> size_t \fBCursorStreamWrapper\fP< InputStream, \fBEncoding\fP >::GetLine () const\fC [inline]\fP"

.PP
Get the error line number, if error exists\&. 
.SS "template<typename InputStream , typename \fBEncoding\fP  = UTF8<>> \fBCh\fP \fBCursorStreamWrapper\fP< InputStream, \fBEncoding\fP >::Take ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename InputStream , typename \fBEncoding\fP  = UTF8<>> size_t \fBCursorStreamWrapper\fP< InputStream, \fBEncoding\fP >::col_\fC [private]\fP"

.PP
Current Column\&. 
.SS "template<typename InputStream , typename \fBEncoding\fP  = UTF8<>> size_t \fBCursorStreamWrapper\fP< InputStream, \fBEncoding\fP >::line_\fC [private]\fP"

.PP
Current Line\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
