.TH "src/modules/Damageable.h" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/Damageable.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDamageable\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
