.TH "Dependent" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dependent
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPerson\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDependent\fP (const std::string &name, unsigned age, \fBEducation\fP *education=0)"
.br
.ti -1c
.RI "\fBDependent\fP (const \fBDependent\fP &rhs)"
.br
.ti -1c
.RI "virtual \fB~Dependent\fP ()"
.br
.ti -1c
.RI "\fBDependent\fP & \fBoperator=\fP (const \fBDependent\fP &rhs)"
.br
.ti -1c
.RI "template<typename \fBWriter\fP > void \fBSerialize\fP (\fBWriter\fP &writer) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Dependent::Dependent (const std::string & name, unsigned age, \fBEducation\fP * education = \fC0\fP)\fC [inline]\fP"

.SS "Dependent::Dependent (const \fBDependent\fP & rhs)\fC [inline]\fP"

.SS "Dependent::~Dependent ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBDependent\fP & Dependent::operator= (const \fBDependent\fP & rhs)\fC [inline]\fP"

.SS "template<typename \fBWriter\fP > void Dependent::Serialize (\fBWriter\fP & writer) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
