.TH "src/rapidjson/include/rapidjson/internal/diyfp.h" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/internal/diyfp.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./rapidjson\&.h'\fP
.br
\fC#include 'clzll\&.h'\fP
.br
\fC#include <limits>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBinternal::DiyFp\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinternal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "DiyFp \fBinternal::GetCachedPowerByIndex\fP (size_t index)"
.br
.ti -1c
.RI "DiyFp \fBinternal::GetCachedPower\fP (int e, int *K)"
.br
.ti -1c
.RI "DiyFp \fBinternal::GetCachedPower10\fP (int exp, int *outExp)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
