.TH "src/rapidjson/test/unittest/documenttest.cpp" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/documenttest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/document\&.h'\fP
.br
\fC#include 'rapidjson/writer\&.h'\fP
.br
\fC#include 'rapidjson/filereadstream\&.h'\fP
.br
\fC#include 'rapidjson/encodedstream\&.h'\fP
.br
\fC#include 'rapidjson/stringbuffer\&.h'\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBOutputStringStream\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename DocumentType > void \fBParseCheck\fP (DocumentType &doc)"
.br
.ti -1c
.RI "template<typename \fBAllocator\fP , typename StackAllocator > void \fBParseTest\fP ()"
.br
.ti -1c
.RI "\fBTEST\fP (\fBDocument\fP, Parse)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBDocument\fP, UnchangedOnParseError)"
.br
.ti -1c
.RI "static FILE * \fBOpenEncodedFile\fP (const char *filename)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBDocument\fP, Parse_Encoding)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBDocument\fP, ParseStream_EncodedInputStream)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBDocument\fP, ParseStream_AutoUTFInputStream)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBDocument\fP, Swap)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBDocument\fP, AcceptWriter)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBDocument\fP, UserBuffer)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBDocument\fP, AssertAcceptInvalidNameType)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBDocument\fP, UTF16_Document)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static FILE * OpenEncodedFile (const char * filename)\fC [static]\fP"

.SS "template<typename DocumentType > void ParseCheck (DocumentType & doc)"

.SS "template<typename \fBAllocator\fP , typename StackAllocator > void ParseTest ()"

.SS "TEST (\fBDocument\fP, AcceptWriter)"

.SS "TEST (\fBDocument\fP, AssertAcceptInvalidNameType)"

.SS "TEST (\fBDocument\fP, Parse)"

.SS "TEST (\fBDocument\fP, Parse_Encoding)"

.SS "TEST (\fBDocument\fP, ParseStream_AutoUTFInputStream)"

.SS "TEST (\fBDocument\fP, ParseStream_EncodedInputStream)"

.SS "TEST (\fBDocument\fP, Swap)"

.SS "TEST (\fBDocument\fP, UnchangedOnParseError)"

.SS "TEST (\fBDocument\fP, UserBuffer)"

.SS "TEST (\fBDocument\fP, UTF16_Document)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
