.TH "src/rapidjson/test/unittest/dtoatest.cpp" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/dtoatest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/internal/dtoa\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTEST_DTOA\fP(d,  \fBa\fP)"
.br
.ti -1c
.RI "#define \fBTEST_DTOA\fP(m,  d,  \fBa\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (dtoa, normal)"
.br
.ti -1c
.RI "\fBTEST\fP (dtoa, maxDecimalPlaces)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TEST_DTOA(d, \fBa\fP)"
\fBValue:\fP
.PP
.nf
    *dtoa(d, buffer) = '\0';\
    EXPECT_STREQ(a, buffer)
.fi
.SS "#define TEST_DTOA(m, d, \fBa\fP)"
\fBValue:\fP
.PP
.nf
    *dtoa(d, buffer, m) = '\0';\
    EXPECT_STREQ(a, buffer)
.fi
.SH "Function Documentation"
.PP 
.SS "TEST (dtoa, maxDecimalPlaces)"

.SS "TEST (dtoa, normal)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
