.TH "src/rapidjson/include/rapidjson/internal/dtoa.h" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/internal/dtoa.h
.SH SYNOPSIS
.br
.PP
\fC#include 'itoa\&.h'\fP
.br
\fC#include 'diyfp\&.h'\fP
.br
\fC#include 'ieee754\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinternal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinternal::GrisuRound\fP (char *buffer, int len, \fBuint64_t\fP delta, \fBuint64_t\fP rest, \fBuint64_t\fP ten_kappa, \fBuint64_t\fP wp_w)"
.br
.ti -1c
.RI "int \fBinternal::CountDecimalDigit32\fP (\fBuint32_t\fP n)"
.br
.ti -1c
.RI "void \fBinternal::DigitGen\fP (const DiyFp &W, const DiyFp &Mp, \fBuint64_t\fP delta, char *buffer, int *len, int *K)"
.br
.ti -1c
.RI "void \fBinternal::Grisu2\fP (double \fBvalue\fP, char *buffer, int *length, int *K)"
.br
.ti -1c
.RI "char * \fBinternal::WriteExponent\fP (int K, char *buffer)"
.br
.ti -1c
.RI "char * \fBinternal::Prettify\fP (char *buffer, int length, int k, int maxDecimalPlaces)"
.br
.ti -1c
.RI "char * \fBinternal::dtoa\fP (double \fBvalue\fP, char *buffer, int maxDecimalPlaces=324)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
