.TH "Education" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Education
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEducation\fP (const std::string &school, double GPA)"
.br
.ti -1c
.RI "\fBEducation\fP (const \fBEducation\fP &rhs)"
.br
.ti -1c
.RI "template<typename \fBWriter\fP > void \fBSerialize\fP (\fBWriter\fP &writer) const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBschool_\fP"
.br
.ti -1c
.RI "double \fBGPA_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Education::Education (const std::string & school, double GPA)\fC [inline]\fP"

.SS "Education::Education (const \fBEducation\fP & rhs)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBWriter\fP > void Education::Serialize (\fBWriter\fP & writer) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double Education::GPA_\fC [private]\fP"

.SS "std::string Education::school_\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
