.TH "Employee" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Employee
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPerson\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEmployee\fP (const std::string &name, unsigned age, bool married)"
.br
.ti -1c
.RI "\fBEmployee\fP (const \fBEmployee\fP &rhs)"
.br
.ti -1c
.RI "virtual \fB~Employee\fP ()"
.br
.ti -1c
.RI "\fBEmployee\fP & \fBoperator=\fP (const \fBEmployee\fP &rhs)"
.br
.ti -1c
.RI "void \fBAddDependent\fP (const \fBDependent\fP &dependent)"
.br
.ti -1c
.RI "template<typename \fBWriter\fP > void \fBSerialize\fP (\fBWriter\fP &writer) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Employee::Employee (const std::string & name, unsigned age, bool married)\fC [inline]\fP"

.SS "Employee::Employee (const \fBEmployee\fP & rhs)\fC [inline]\fP"

.SS "Employee::~Employee ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Employee::AddDependent (const \fBDependent\fP & dependent)\fC [inline]\fP"

.SS "\fBEmployee\fP & Employee::operator= (const \fBEmployee\fP & rhs)\fC [inline]\fP"

.SS "template<typename \fBWriter\fP > void Employee::Serialize (\fBWriter\fP & writer) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
