.TH "src/rapidjson/include/rapidjson/error/en.h" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/error/en.h
.SH SYNOPSIS
.br
.PP
\fC#include 'error\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRAPIDJSON_NAMESPACE_BEGIN\fP const \fBRAPIDJSON_ERROR_CHARTYPE\fP * \fBGetParseError_En\fP (\fBParseErrorCode\fP parseErrorCode)"
.br
.RI "Maps error code of parsing into error message\&. "
.ti -1c
.RI "const \fBRAPIDJSON_ERROR_CHARTYPE\fP * \fBGetValidateError_En\fP (\fBValidateErrorCode\fP validateErrorCode)"
.br
.RI "Maps error code of validation into error message\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
