.TH "src/rapidjson/test/unittest/encodingstest.cpp" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/encodingstest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/filereadstream\&.h'\fP
.br
\fC#include 'rapidjson/filewritestream\&.h'\fP
.br
\fC#include 'rapidjson/encodedstream\&.h'\fP
.br
\fC#include 'rapidjson/stringbuffer\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUTF8_ACCEPT\fP   0u"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (EncodingsTest, \fBUTF8\fP)"
.br
.ti -1c
.RI "\fBTEST\fP (EncodingsTest, \fBUTF16\fP)"
.br
.ti -1c
.RI "\fBTEST\fP (EncodingsTest, \fBUTF32\fP)"
.br
.ti -1c
.RI "\fBTEST\fP (EncodingsTest, \fBASCII\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define UTF8_ACCEPT   0u"

.SH "Function Documentation"
.PP 
.SS "TEST (EncodingsTest, \fBASCII\fP)"

.SS "TEST (EncodingsTest, \fBUTF16\fP)"

.SS "TEST (EncodingsTest, \fBUTF32\fP)"

.SS "TEST (EncodingsTest, \fBUTF8\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
