.TH "EncodedInputStream< UTF8<>, MemoryStream >" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EncodedInputStream< UTF8<>, MemoryStream > \- Specialized for \fBUTF8\fP \fBMemoryStream\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <encodedstream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBUTF8\fP ::Ch \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEncodedInputStream\fP (\fBMemoryStream\fP &is)"
.br
.ti -1c
.RI "\fBCh\fP \fBPeek\fP () const"
.br
.ti -1c
.RI "\fBCh\fP \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP () const"
.br
.ti -1c
.RI "void \fBPut\fP (\fBCh\fP)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "\fBCh\fP * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (\fBCh\fP *)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMemoryStream\fP & \fBis_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Specialized for \fBUTF8\fP \fBMemoryStream\fP\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "typedef \fBUTF8\fP ::Ch \fBEncodedInputStream\fP< \fBUTF8\fP<>, \fBMemoryStream\fP >::Ch"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBEncodedInputStream\fP< \fBUTF8\fP<>, \fBMemoryStream\fP >\fB::EncodedInputStream\fP (\fBMemoryStream\fP & is)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void \fBEncodedInputStream\fP< \fBUTF8\fP<>, \fBMemoryStream\fP >::Flush ()\fC [inline]\fP"

.SS "\fBCh\fP \fBEncodedInputStream\fP< \fBUTF8\fP<>, \fBMemoryStream\fP >::Peek () const\fC [inline]\fP"

.SS "void \fBEncodedInputStream\fP< \fBUTF8\fP<>, \fBMemoryStream\fP >::Put (\fBCh\fP)\fC [inline]\fP"

.SS "\fBCh\fP * \fBEncodedInputStream\fP< \fBUTF8\fP<>, \fBMemoryStream\fP >::PutBegin ()\fC [inline]\fP"

.SS "size_t \fBEncodedInputStream\fP< \fBUTF8\fP<>, \fBMemoryStream\fP >::PutEnd (\fBCh\fP *)\fC [inline]\fP"

.SS "\fBCh\fP \fBEncodedInputStream\fP< \fBUTF8\fP<>, \fBMemoryStream\fP >::Take ()\fC [inline]\fP"

.SS "size_t \fBEncodedInputStream\fP< \fBUTF8\fP<>, \fBMemoryStream\fP >::Tell () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBMemoryStream\fP& \fBEncodedInputStream\fP< \fBUTF8\fP<>, \fBMemoryStream\fP >::is_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
