.TH "src/rapidjson/test/unittest/encodedstreamtest.cpp" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/encodedstreamtest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/filereadstream\&.h'\fP
.br
\fC#include 'rapidjson/filewritestream\&.h'\fP
.br
\fC#include 'rapidjson/encodedstream\&.h'\fP
.br
\fC#include 'rapidjson/stringbuffer\&.h'\fP
.br
\fC#include 'rapidjson/memorystream\&.h'\fP
.br
\fC#include 'rapidjson/memorybuffer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEncodedStreamTest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBEncodedStreamTest\fP, \fBEncodedInputStream\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBEncodedStreamTest\fP, \fBAutoUTFInputStream\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBEncodedStreamTest\fP, \fBEncodedOutputStream\fP)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBEncodedStreamTest\fP, \fBAutoUTFOutputStream\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST_F (\fBEncodedStreamTest\fP, \fBAutoUTFInputStream\fP)"

.SS "TEST_F (\fBEncodedStreamTest\fP, \fBAutoUTFOutputStream\fP)"

.SS "TEST_F (\fBEncodedStreamTest\fP, \fBEncodedInputStream\fP)"

.SS "TEST_F (\fBEncodedStreamTest\fP, \fBEncodedOutputStream\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
