.TH "src/rapidjson/include/rapidjson/encodedstream.h" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/encodedstream.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stream\&.h'\fP
.br
\fC#include 'memorystream\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEncodedInputStream< Encoding, InputByteStream >\fP"
.br
.RI "Input byte stream wrapper with a statically bound encoding\&. "
.ti -1c
.RI "class \fBEncodedInputStream< UTF8<>, MemoryStream >\fP"
.br
.RI "Specialized for \fBUTF8\fP \fBMemoryStream\fP\&. "
.ti -1c
.RI "class \fBEncodedOutputStream< Encoding, OutputByteStream >\fP"
.br
.RI "Output byte stream wrapper with statically bound encoding\&. "
.ti -1c
.RI "class \fBAutoUTFInputStream< CharType, InputByteStream >\fP"
.br
.RI "Input stream wrapper with dynamically bound encoding and automatic encoding detection\&. "
.ti -1c
.RI "class \fBAutoUTFOutputStream< CharType, OutputByteStream >\fP"
.br
.RI "Output stream wrapper with dynamically bound encoding and automatic encoding detection\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRAPIDJSON_ENCODINGS_FUNC\fP(x)   \fBUTF8\fP<Ch>::x, \fBUTF16LE\fP<Ch>::x, \fBUTF16BE\fP<Ch>::x, \fBUTF32LE\fP<Ch>::x, \fBUTF32BE\fP<Ch>::x"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RAPIDJSON_ENCODINGS_FUNC(x)   \fBUTF8\fP<Ch>::x, \fBUTF16LE\fP<Ch>::x, \fBUTF16BE\fP<Ch>::x, \fBUTF32LE\fP<Ch>::x, \fBUTF32BE\fP<Ch>::x"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
