.TH "Enemy" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Enemy
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Enemy\&.h>\fP
.PP
Inherits \fBDamageable\fP, and \fBAnimated\fP\&.
.PP
Inherited by \fBSlime\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnemy\fP (float x=0, float y=0)"
.br
.ti -1c
.RI "void \fBmoveHorizontal\fP (float x)"
.br
.ti -1c
.RI "sf::Vector2f \fBgetPosition\fP ()"
.br
.ti -1c
.RI "sf::RectangleShape & \fBgetHitbox\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdate\fP (float deltaSeconds)=0"
.br
.ti -1c
.RI "virtual void \fBrender\fP (sf::RenderTarget &window)=0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitSprite\fP (const std::string &filePath, sf::IntRect frame)"
.br
.ti -1c
.RI "void \fBinitHitbox\fP (sf::Vector2f size)"
.br
.ti -1c
.RI "virtual void \fBinitPath\fP (float pointA, float pointB)=0"
.br
.ti -1c
.RI "void \fBsetPosition\fP (float x, float y)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "sf::Texture \fB_texture\fP"
.br
.RI "Przechowuje teksturę przeciwnika\&. "
.ti -1c
.RI "sf::Sprite \fB_sprite\fP"
.br
.RI "Przechowuje sprite-a gracza\&. "
.ti -1c
.RI "sf::RectangleShape \fB_hitbox\fP"
.br
.RI "\fBReprezentuje\fP kształt odpowiedzialny za kolizje i ruch przeciwnika\&. "
.ti -1c
.RI "sf::RectangleShape \fB_path\fP"
.br
.RI "\fBReprezentuje\fP kształt określający granice ruchu przeciwnika\&. "
.ti -1c
.RI "bool \fBmovingRight\fP = false"
.br
.RI "Określa kierunek ruchu przeciwnika\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Enemy::Enemy (float x = \fC0\fP, float y = \fC0\fP)\fC [explicit]\fP"
Konstruktor przyjmuje początkową pozycję przeciwnika na mapie 
.PP
\fBParameters\fP
.RS 4
\fIx\fP początkowa pozycja x 
.br
\fIy\fP początkowa pozycja y 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "sf::RectangleShape & Enemy::getHitbox ()\fC [inline]\fP"
Zwraca hitbox przeciwnika\&. Używane do sprawdzania kolizji 
.PP
\fBReturns\fP
.RS 4
obiekt reprezentujący hitbox 
.RE
.PP

.SS "sf::Vector2f Enemy::getPosition ()"
Zwraca pozycję przeciwnika na mapie 
.PP
\fBReturns\fP
.RS 4
Pozycja gracza na mapie 
.RE
.PP

.SS "void Enemy::initHitbox (sf::Vector2f size)\fC [protected]\fP"
Nadaje odpowiednie parametry hitboxowi 
.PP
\fBParameters\fP
.RS 4
\fIsize\fP wymiary hitboxa 
.RE
.PP

.SS "virtual void Enemy::initPath (float pointA, float pointB)\fC [protected]\fP, \fC [pure virtual]\fP"
Nadaje odpowiednie parametry granicy ruchu 
.PP
\fBParameters\fP
.RS 4
\fIpointA\fP wartość x lewego punktu patrolowego 
.br
\fIpointB\fP wartość x prawego punktu patrolowego 
.RE
.PP

.PP
Implemented in \fBSlime\fP\&.
.SS "void Enemy::initSprite (const std::string & filePath, sf::IntRect frame)\fC [protected]\fP"
Wczytuje teksturę z pliku, oraz tworzy sprite ze wczytanej tekstury 
.PP
\fBParameters\fP
.RS 4
\fIfilePath\fP ścieżka do pliku tekstury 
.br
\fIframe\fP określa jakim fragmentem tekstury zostanie zainicjowany sprite 
.RE
.PP

.SS "void Enemy::moveHorizontal (float x)"
Porusza przeciwnikiem w poziomej linii o podaną wartość 
.PP
\fBParameters\fP
.RS 4
\fIx\fP wartość na osi x o jaką zostanie poruszony przeciwnik 
.RE
.PP

.SS "virtual void Enemy::render (sf::RenderTarget & window)\fC [pure virtual]\fP"
Wyświetla przeciwnika na ekranie 
.PP
\fBParameters\fP
.RS 4
\fIwindow\fP okno na którym wyświetlony zostanie przeciwnik 
.RE
.PP

.PP
Implemented in \fBSlime\fP\&.
.SS "void Enemy::setPosition (float x, float y)\fC [protected]\fP"
Ustawia pozycję przeciwnika na mapie 
.PP
\fBParameters\fP
.RS 4
\fIx\fP pozycja na osi x 
.br
\fIy\fP pozycja na osi y 
.RE
.PP

.SS "virtual void Enemy::update (float deltaSeconds)\fC [pure virtual]\fP"
Odpowiada za odświeżanie logiki przeciwnika 
.PP
\fBParameters\fP
.RS 4
\fIdeltaSeconds\fP czas pomiędzy klatkami aplikacji 
.RE
.PP

.PP
Implemented in \fBSlime\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "sf::RectangleShape Enemy::_hitbox\fC [protected]\fP"

.PP
\fBReprezentuje\fP kształt odpowiedzialny za kolizje i ruch przeciwnika\&. 
.SS "sf::RectangleShape Enemy::_path\fC [protected]\fP"

.PP
\fBReprezentuje\fP kształt określający granice ruchu przeciwnika\&. 
.SS "sf::Sprite Enemy::_sprite\fC [protected]\fP"

.PP
Przechowuje sprite-a gracza\&. 
.SS "sf::Texture Enemy::_texture\fC [protected]\fP"

.PP
Przechowuje teksturę przeciwnika\&. 
.SS "bool Enemy::movingRight = false\fC [protected]\fP"

.PP
Określa kierunek ruchu przeciwnika\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
