.TH "FileStreamTest" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileStreamTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits testing::Test\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileStreamTest\fP ()"
.br
.ti -1c
.RI "virtual \fB~FileStreamTest\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetUp\fP ()"
.br
.ti -1c
.RI "virtual void \fBTearDown\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const char * \fBfilename_\fP"
.br
.ti -1c
.RI "char * \fBjson_\fP"
.br
.ti -1c
.RI "size_t \fBlength_\fP"
.br
.ti -1c
.RI "const char * \fBabcde_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileStreamTest::FileStreamTest ()\fC [inline]\fP"

.SS "FileStreamTest::~FileStreamTest ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void FileStreamTest::SetUp ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual void FileStreamTest::TearDown ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const char* FileStreamTest::abcde_\fC [protected]\fP"

.SS "const char* FileStreamTest::filename_\fC [protected]\fP"

.SS "char* FileStreamTest::json_\fC [protected]\fP"

.SS "size_t FileStreamTest::length_\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
