.TH "src/rapidjson/include/rapidjson/filewritestream.h" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/filewritestream.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stream\&.h'\fP
.br
\fC#include <cstdio>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileWriteStream\fP"
.br
.RI "Wrapper of C file stream for output using fwrite()\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<> void \fBPutN\fP (\fBFileWriteStream\fP &stream, char c, size_t n)"
.br
.RI "Implement specialized version of \fBPutN()\fP with memset() for better performance\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<> void PutN (\fBFileWriteStream\fP & stream, char c, size_t n)\fC [inline]\fP"

.PP
Implement specialized version of \fBPutN()\fP with memset() for better performance\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
