.TH "FileReadStream" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileReadStream \- File byte stream for input using fread()\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <filereadstream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef char \fBCh\fP"
.br
.RI "Character type (byte)\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileReadStream\fP (std::FILE *fp, char *buffer, size_t bufferSize)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBCh\fP \fBPeek\fP () const"
.br
.ti -1c
.RI "\fBCh\fP \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP () const"
.br
.ti -1c
.RI "void \fBPut\fP (\fBCh\fP)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "\fBCh\fP * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (\fBCh\fP *)"
.br
.ti -1c
.RI "const \fBCh\fP * \fBPeek4\fP () const"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBRead\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::FILE * \fBfp_\fP"
.br
.ti -1c
.RI "\fBCh\fP * \fBbuffer_\fP"
.br
.ti -1c
.RI "size_t \fBbufferSize_\fP"
.br
.ti -1c
.RI "\fBCh\fP * \fBbufferLast_\fP"
.br
.ti -1c
.RI "\fBCh\fP * \fBcurrent_\fP"
.br
.ti -1c
.RI "size_t \fBreadCount_\fP"
.br
.ti -1c
.RI "size_t \fBcount_\fP"
.br
.RI "Number of characters read\&. "
.ti -1c
.RI "bool \fBeof_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
File byte stream for input using fread()\&. 


.PP
\fBNote\fP
.RS 4
implements Stream concept 
.RE
.PP

.SH "Member Typedef Documentation"
.PP 
.SS "typedef char \fBFileReadStream::Ch\fP"

.PP
Character type (byte)\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileReadStream::FileReadStream (std::FILE * fp, char * buffer, size_t bufferSize)\fC [inline]\fP"

.PP
Constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIfp\fP File pointer opened for read\&. 
.br
\fIbuffer\fP user-supplied buffer\&. 
.br
\fIbufferSize\fP size of buffer in bytes\&. Must >=4 bytes\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void FileReadStream::Flush ()\fC [inline]\fP"

.SS "\fBCh\fP FileReadStream::Peek () const\fC [inline]\fP"

.SS "const \fBCh\fP * FileReadStream::Peek4 () const\fC [inline]\fP"

.SS "void FileReadStream::Put (\fBCh\fP)\fC [inline]\fP"

.SS "\fBCh\fP * FileReadStream::PutBegin ()\fC [inline]\fP"

.SS "size_t FileReadStream::PutEnd (\fBCh\fP *)\fC [inline]\fP"

.SS "void FileReadStream::Read ()\fC [inline]\fP, \fC [private]\fP"

.SS "\fBCh\fP FileReadStream::Take ()\fC [inline]\fP"

.SS "size_t FileReadStream::Tell () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBCh\fP* FileReadStream::buffer_\fC [private]\fP"

.SS "\fBCh\fP* FileReadStream::bufferLast_\fC [private]\fP"

.SS "size_t FileReadStream::bufferSize_\fC [private]\fP"

.SS "size_t FileReadStream::count_\fC [private]\fP"

.PP
Number of characters read\&. 
.SS "\fBCh\fP* FileReadStream::current_\fC [private]\fP"

.SS "bool FileReadStream::eof_\fC [private]\fP"

.SS "std::FILE* FileReadStream::fp_\fC [private]\fP"

.SS "size_t FileReadStream::readCount_\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
