.TH "FileWriteStream" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileWriteStream \- Wrapper of C file stream for output using fwrite()\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <filewritestream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef char \fBCh\fP"
.br
.RI "Character type\&. Only support char\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileWriteStream\fP (std::FILE *fp, char *buffer, size_t bufferSize)"
.br
.ti -1c
.RI "void \fBPut\fP (char c)"
.br
.ti -1c
.RI "void \fBPutN\fP (char c, size_t n)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "char \fBPeek\fP () const"
.br
.ti -1c
.RI "char \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP () const"
.br
.ti -1c
.RI "char * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (char *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wrapper of C file stream for output using fwrite()\&. 


.PP
\fBNote\fP
.RS 4
implements Stream concept 
.RE
.PP

.SH "Member Typedef Documentation"
.PP 
.SS "typedef char \fBFileWriteStream::Ch\fP"

.PP
Character type\&. Only support char\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileWriteStream::FileWriteStream (std::FILE * fp, char * buffer, size_t bufferSize)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void FileWriteStream::Flush ()\fC [inline]\fP"

.SS "char FileWriteStream::Peek () const\fC [inline]\fP"

.SS "void FileWriteStream::Put (char c)\fC [inline]\fP"

.SS "char * FileWriteStream::PutBegin ()\fC [inline]\fP"

.SS "size_t FileWriteStream::PutEnd (char *)\fC [inline]\fP"

.SS "void FileWriteStream::PutN (char c, size_t n)\fC [inline]\fP"

.SS "char FileWriteStream::Take ()\fC [inline]\fP"

.SS "size_t FileWriteStream::Tell () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
