.TH "FilterKeyReader< InputStream >" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FilterKeyReader< InputStream >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef char \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFilterKeyReader\fP (InputStream &is, const \fBCh\fP *keyString, \fBSizeType\fP keyLength)"
.br
.ti -1c
.RI "template<typename \fBHandler\fP > bool \fBoperator()\fP (\fBHandler\fP &handler)"
.br
.ti -1c
.RI "const \fBParseResult\fP & \fBGetParseResult\fP () const"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename InputStream > typedef char \fBFilterKeyReader\fP< InputStream >::Ch"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename InputStream > \fBFilterKeyReader\fP< InputStream >\fB::FilterKeyReader\fP (InputStream & is, const \fBCh\fP * keyString, \fBSizeType\fP keyLength)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename InputStream > const \fBParseResult\fP & \fBFilterKeyReader\fP< InputStream >::GetParseResult () const\fC [inline]\fP"

.SS "template<typename InputStream > template<typename \fBHandler\fP > bool \fBFilterKeyReader\fP< InputStream >::operator() (\fBHandler\fP & handler)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
