.TH "FilterKeyReader< InputStream >" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FilterKeyReader< InputStream >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef char \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFilterKeyReader\fP (InputStream &is, const \fBCh\fP *keyString, \fBSizeType\fP keyLength)"
.br
.ti -1c
.RI "template<typename \fBHandler\fP > bool \fBoperator()\fP (\fBHandler\fP &handler)"
.br
.ti -1c
.RI "const \fBParseResult\fP & \fBGetParseResult\fP () const"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBFilterKeyReader\fP (const \fBFilterKeyReader\fP &)"
.br
.ti -1c
.RI "\fBFilterKeyReader\fP & \fBoperator=\fP (const \fBFilterKeyReader\fP &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "InputStream & \fBis_\fP"
.br
.ti -1c
.RI "const char * \fBkeyString_\fP"
.br
.ti -1c
.RI "const \fBSizeType\fP \fBkeyLength_\fP"
.br
.ti -1c
.RI "\fBParseResult\fP \fBparseResult_\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename InputStream > typedef char \fBFilterKeyReader\fP< InputStream >::Ch"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename InputStream > \fBFilterKeyReader\fP< InputStream >\fB::FilterKeyReader\fP (InputStream & is, const \fBCh\fP * keyString, \fBSizeType\fP keyLength)\fC [inline]\fP"

.SS "template<typename InputStream > \fBFilterKeyReader\fP< InputStream >\fB::FilterKeyReader\fP (const \fBFilterKeyReader\fP< InputStream > &)\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename InputStream > const \fBParseResult\fP & \fBFilterKeyReader\fP< InputStream >::GetParseResult () const\fC [inline]\fP"

.SS "template<typename InputStream > template<typename \fBHandler\fP > bool \fBFilterKeyReader\fP< InputStream >::operator() (\fBHandler\fP & handler)\fC [inline]\fP"

.SS "template<typename InputStream > \fBFilterKeyReader\fP & \fBFilterKeyReader\fP< InputStream >::operator= (const \fBFilterKeyReader\fP< InputStream > &)\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename InputStream > InputStream& \fBFilterKeyReader\fP< InputStream >::is_\fC [private]\fP"

.SS "template<typename InputStream > const \fBSizeType\fP \fBFilterKeyReader\fP< InputStream >::keyLength_\fC [private]\fP"

.SS "template<typename InputStream > const char* \fBFilterKeyReader\fP< InputStream >::keyString_\fC [private]\fP"

.SS "template<typename InputStream > \fBParseResult\fP \fBFilterKeyReader\fP< InputStream >::parseResult_\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
