.TH "FilterKeyHandler< OutputHandler >" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FilterKeyHandler< OutputHandler >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef char \fBCh\fP"
.br
.ti -1c
.RI "typedef char \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFilterKeyHandler\fP (OutputHandler &outputHandler, const \fBCh\fP *keyString, \fBSizeType\fP keyLength)"
.br
.ti -1c
.RI "bool \fBNull\fP ()"
.br
.ti -1c
.RI "bool \fBBool\fP (bool b)"
.br
.ti -1c
.RI "bool \fBInt\fP (int i)"
.br
.ti -1c
.RI "bool \fBUint\fP (unsigned u)"
.br
.ti -1c
.RI "bool \fBInt64\fP (\fBint64_t\fP i)"
.br
.ti -1c
.RI "bool \fBUint64\fP (\fBuint64_t\fP u)"
.br
.ti -1c
.RI "bool \fBDouble\fP (double d)"
.br
.ti -1c
.RI "bool \fBRawNumber\fP (const \fBCh\fP *str, \fBSizeType\fP len, bool copy)"
.br
.ti -1c
.RI "bool \fBString\fP (const \fBCh\fP *str, \fBSizeType\fP len, bool copy)"
.br
.ti -1c
.RI "bool \fBStartObject\fP ()"
.br
.ti -1c
.RI "bool \fBKey\fP (const \fBCh\fP *str, \fBSizeType\fP len, bool copy)"
.br
.ti -1c
.RI "bool \fBEndObject\fP (\fBSizeType\fP)"
.br
.ti -1c
.RI "bool \fBStartArray\fP ()"
.br
.ti -1c
.RI "bool \fBEndArray\fP (\fBSizeType\fP elementCount)"
.br
.ti -1c
.RI "\fBFilterKeyHandler\fP (OutputHandler &outputHandler, const \fBCh\fP *keyString, \fBSizeType\fP keyLength)"
.br
.ti -1c
.RI "bool \fBNull\fP ()"
.br
.ti -1c
.RI "bool \fBBool\fP (bool b)"
.br
.ti -1c
.RI "bool \fBInt\fP (int i)"
.br
.ti -1c
.RI "bool \fBUint\fP (unsigned u)"
.br
.ti -1c
.RI "bool \fBInt64\fP (\fBint64_t\fP i)"
.br
.ti -1c
.RI "bool \fBUint64\fP (\fBuint64_t\fP u)"
.br
.ti -1c
.RI "bool \fBDouble\fP (double d)"
.br
.ti -1c
.RI "bool \fBRawNumber\fP (const \fBCh\fP *str, \fBSizeType\fP len, bool copy)"
.br
.ti -1c
.RI "bool \fBString\fP (const \fBCh\fP *str, \fBSizeType\fP len, bool copy)"
.br
.ti -1c
.RI "bool \fBStartObject\fP ()"
.br
.ti -1c
.RI "bool \fBKey\fP (const \fBCh\fP *str, \fBSizeType\fP len, bool copy)"
.br
.ti -1c
.RI "bool \fBEndObject\fP (\fBSizeType\fP)"
.br
.ti -1c
.RI "bool \fBStartArray\fP ()"
.br
.ti -1c
.RI "bool \fBEndArray\fP (\fBSizeType\fP elementCount)"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename OutputHandler > typedef char \fBFilterKeyHandler\fP< OutputHandler >::Ch"

.SS "template<typename OutputHandler > typedef char \fBFilterKeyHandler\fP< OutputHandler >::Ch"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename OutputHandler > \fBFilterKeyHandler\fP< OutputHandler >\fB::FilterKeyHandler\fP (OutputHandler & outputHandler, const \fBCh\fP * keyString, \fBSizeType\fP keyLength)\fC [inline]\fP"

.SS "template<typename OutputHandler > \fBFilterKeyHandler\fP< OutputHandler >\fB::FilterKeyHandler\fP (OutputHandler & outputHandler, const \fBCh\fP * keyString, \fBSizeType\fP keyLength)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::Bool (bool b)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::Bool (bool b)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::Double (double d)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::Double (double d)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::EndArray (\fBSizeType\fP elementCount)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::EndArray (\fBSizeType\fP elementCount)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::EndObject (\fBSizeType\fP)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::EndObject (\fBSizeType\fP)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::Int (int i)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::Int (int i)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::Int64 (\fBint64_t\fP i)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::Int64 (\fBint64_t\fP i)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::Key (const \fBCh\fP * str, \fBSizeType\fP len, bool copy)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::Key (const \fBCh\fP * str, \fBSizeType\fP len, bool copy)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::Null ()\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::Null ()\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::RawNumber (const \fBCh\fP * str, \fBSizeType\fP len, bool copy)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::RawNumber (const \fBCh\fP * str, \fBSizeType\fP len, bool copy)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::StartArray ()\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::StartArray ()\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::StartObject ()\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::StartObject ()\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::String (const \fBCh\fP * str, \fBSizeType\fP len, bool copy)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::String (const \fBCh\fP * str, \fBSizeType\fP len, bool copy)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::Uint (unsigned u)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::Uint (unsigned u)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::Uint64 (\fBuint64_t\fP u)\fC [inline]\fP"

.SS "template<typename OutputHandler > bool \fBFilterKeyHandler\fP< OutputHandler >::Uint64 (\fBuint64_t\fP u)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
