.TH "Foo" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Foo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFoo\fP ()"
.br
.ti -1c
.RI "\fB~Foo\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUTF8\fP< char > * \fButf8\fP"
.br
.ti -1c
.RI "\fBUTF16\fP< wchar_t > * \fButf16\fP"
.br
.ti -1c
.RI "\fBUTF16BE\fP< wchar_t > * \fButf16be\fP"
.br
.ti -1c
.RI "\fBUTF16LE\fP< wchar_t > * \fButf16le\fP"
.br
.ti -1c
.RI "\fBUTF32\fP< unsigned > * \fButf32\fP"
.br
.ti -1c
.RI "\fBUTF32BE\fP< unsigned > * \fButf32be\fP"
.br
.ti -1c
.RI "\fBUTF32LE\fP< unsigned > * \fButf32le\fP"
.br
.ti -1c
.RI "\fBASCII\fP< char > * \fBascii\fP"
.br
.ti -1c
.RI "\fBAutoUTF\fP< unsigned > * \fBautoutf\fP"
.br
.ti -1c
.RI "\fBTranscoder\fP< \fBUTF8\fP< char >, \fBUTF8\fP< char > > * \fBtranscoder\fP"
.br
.ti -1c
.RI "\fBCrtAllocator\fP * \fBcrtallocator\fP"
.br
.ti -1c
.RI "\fBMemoryPoolAllocator\fP< \fBCrtAllocator\fP > * \fBmemorypoolallocator\fP"
.br
.ti -1c
.RI "\fBStringStream\fP * \fBstringstream\fP"
.br
.ti -1c
.RI "\fBInsituStringStream\fP * \fBinsitustringstream\fP"
.br
.ti -1c
.RI "\fBStringBuffer\fP * \fBstringbuffer\fP"
.br
.ti -1c
.RI "\fBMemoryBuffer\fP * \fBmemorybuffer\fP"
.br
.ti -1c
.RI "\fBMemoryStream\fP * \fBmemorystream\fP"
.br
.ti -1c
.RI "\fBBaseReaderHandler\fP< \fBUTF8\fP< char >, void > * \fBbasereaderhandler\fP"
.br
.ti -1c
.RI "\fBReader\fP * \fBreader\fP"
.br
.ti -1c
.RI "\fBWriter\fP< \fBStringBuffer\fP, \fBUTF8\fP< char >, \fBUTF8\fP< char >, \fBCrtAllocator\fP, 0 > * \fBwriter\fP"
.br
.ti -1c
.RI "\fBPrettyWriter\fP< \fBStringBuffer\fP, \fBUTF8\fP< char >, \fBUTF8\fP< char >, \fBCrtAllocator\fP, 0 > * \fBprettywriter\fP"
.br
.ti -1c
.RI "\fBValue\fP * \fBvalue\fP"
.br
.ti -1c
.RI "\fBDocument\fP * \fBdocument\fP"
.br
.ti -1c
.RI "\fBPointer\fP * \fBpointer\fP"
.br
.ti -1c
.RI "\fBSchemaDocument\fP * \fBschemadocument\fP"
.br
.ti -1c
.RI "\fBSchemaValidator\fP * \fBschemavalidator\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Foo::Foo ()"

.SS "Foo::~Foo ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBASCII\fP<char>* Foo::ascii"

.SS "\fBAutoUTF\fP<unsigned>* Foo::autoutf"

.SS "\fBBaseReaderHandler\fP<\fBUTF8\fP<char>, void>* Foo::basereaderhandler"

.SS "\fBCrtAllocator\fP* Foo::crtallocator"

.SS "\fBDocument\fP* Foo::document"

.SS "\fBInsituStringStream\fP* Foo::insitustringstream"

.SS "\fBMemoryBuffer\fP* Foo::memorybuffer"

.SS "\fBMemoryPoolAllocator\fP<\fBCrtAllocator\fP>* Foo::memorypoolallocator"

.SS "\fBMemoryStream\fP* Foo::memorystream"

.SS "\fBPointer\fP* Foo::pointer"

.SS "\fBPrettyWriter\fP<\fBStringBuffer\fP, \fBUTF8\fP<char>, \fBUTF8\fP<char>, \fBCrtAllocator\fP, 0>* Foo::prettywriter"

.SS "\fBReader\fP* Foo::reader"

.SS "\fBSchemaDocument\fP* Foo::schemadocument"

.SS "\fBSchemaValidator\fP* Foo::schemavalidator"

.SS "\fBStringBuffer\fP* Foo::stringbuffer"

.SS "\fBStringStream\fP* Foo::stringstream"

.SS "\fBTranscoder\fP<\fBUTF8\fP<char>, \fBUTF8\fP<char> >* Foo::transcoder"

.SS "\fBUTF16\fP<wchar_t>* Foo::utf16"

.SS "\fBUTF16BE\fP<wchar_t>* Foo::utf16be"

.SS "\fBUTF16LE\fP<wchar_t>* Foo::utf16le"

.SS "\fBUTF32\fP<unsigned>* Foo::utf32"

.SS "\fBUTF32BE\fP<unsigned>* Foo::utf32be"

.SS "\fBUTF32LE\fP<unsigned>* Foo::utf32le"

.SS "\fBUTF8\fP<char>* Foo::utf8"

.SS "\fBValue\fP* Foo::value"

.SS "\fBWriter\fP<\fBStringBuffer\fP, \fBUTF8\fP<char>, \fBUTF8\fP<char>, \fBCrtAllocator\fP, 0>* Foo::writer"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
