.TH "src/rapidjson/include/rapidjson/fwd.h" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/fwd.h
.SH SYNOPSIS
.br
.PP
\fC#include 'rapidjson\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBGenericStringStream\fP< \fBUTF8\fP< char > > \fBStringStream\fP"
.br
.ti -1c
.RI "typedef \fBGenericInsituStringStream\fP< \fBUTF8\fP< char > > \fBInsituStringStream\fP"
.br
.ti -1c
.RI "typedef \fBGenericStringBuffer\fP< \fBUTF8\fP< char >, \fBCrtAllocator\fP > \fBStringBuffer\fP"
.br
.ti -1c
.RI "typedef \fBGenericMemoryBuffer\fP< \fBCrtAllocator\fP > \fBMemoryBuffer\fP"
.br
.ti -1c
.RI "typedef \fBGenericReader\fP< \fBUTF8\fP< char >, \fBUTF8\fP< char >, \fBCrtAllocator\fP > \fBReader\fP"
.br
.ti -1c
.RI "typedef \fBGenericValue\fP< \fBUTF8\fP< char >, \fBMemoryPoolAllocator\fP< \fBCrtAllocator\fP > > \fBValue\fP"
.br
.ti -1c
.RI "typedef \fBGenericDocument\fP< \fBUTF8\fP< char >, \fBMemoryPoolAllocator\fP< \fBCrtAllocator\fP >, \fBCrtAllocator\fP > \fBDocument\fP"
.br
.ti -1c
.RI "typedef \fBGenericPointer\fP< \fBValue\fP, \fBCrtAllocator\fP > \fBPointer\fP"
.br
.ti -1c
.RI "typedef \fBGenericSchemaDocument\fP< \fBValue\fP, \fBCrtAllocator\fP > \fBSchemaDocument\fP"
.br
.ti -1c
.RI "typedef \fBIGenericRemoteSchemaDocumentProvider\fP< \fBSchemaDocument\fP > \fBIRemoteSchemaDocumentProvider\fP"
.br
.ti -1c
.RI "typedef \fBGenericSchemaValidator\fP< \fBSchemaDocument\fP, \fBBaseReaderHandler\fP< \fBUTF8\fP< char >, void >, \fBCrtAllocator\fP > \fBSchemaValidator\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBGenericDocument\fP<\fBUTF8\fP<char>, \fBMemoryPoolAllocator\fP<\fBCrtAllocator\fP>, \fBCrtAllocator\fP> \fBDocument\fP"

.SS "typedef \fBGenericInsituStringStream\fP<\fBUTF8\fP<char> > \fBInsituStringStream\fP"

.SS "typedef \fBIGenericRemoteSchemaDocumentProvider\fP<\fBSchemaDocument\fP> \fBIRemoteSchemaDocumentProvider\fP"

.SS "typedef \fBGenericMemoryBuffer\fP<\fBCrtAllocator\fP> \fBMemoryBuffer\fP"

.SS "typedef \fBGenericPointer\fP<\fBValue\fP, \fBCrtAllocator\fP> \fBPointer\fP"

.SS "typedef \fBGenericReader\fP<\fBUTF8\fP<char>, \fBUTF8\fP<char>, \fBCrtAllocator\fP> \fBReader\fP"

.SS "typedef \fBGenericSchemaDocument\fP<\fBValue\fP, \fBCrtAllocator\fP> \fBSchemaDocument\fP"

.SS "typedef \fBGenericSchemaValidator\fP<\fBSchemaDocument\fP, \fBBaseReaderHandler\fP<\fBUTF8\fP<char>, void>, \fBCrtAllocator\fP> \fBSchemaValidator\fP"

.SS "typedef \fBGenericStringBuffer\fP<\fBUTF8\fP<char>, \fBCrtAllocator\fP> \fBStringBuffer\fP"

.SS "typedef \fBGenericStringStream\fP<\fBUTF8\fP<char> > \fBStringStream\fP"

.SS "typedef \fBGenericValue\fP<\fBUTF8\fP<char>, \fBMemoryPoolAllocator\fP<\fBCrtAllocator\fP> > \fBValue\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
