.TH "src/states/GameState.h" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/states/GameState.h
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics/RenderTarget\&.hpp>\fP
.br
\fC#include <SFML/Audio\&.hpp>\fP
.br
\fC#include <stack>\fP
.br
\fC#include '\&.\&./UI/Button\&.h'\fP
.br
\fC#include '\&.\&./modules/PlayerHUD\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGameState\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
