.TH "GenericValue< Encoding, Allocator >::ShortString" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericValue< Encoding, Allocator >::ShortString
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <document\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBMaxChars\fP = sizeof(static_cast<Flag*>(0)->payload) / sizeof(Ch), \fBMaxSize\fP = MaxChars - 1, \fBLenPos\fP = MaxSize }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetLength\fP (\fBSizeType\fP len)"
.br
.ti -1c
.RI "\fBSizeType\fP \fBGetLength\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBUsable\fP (\fBSizeType\fP len)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCh\fP \fBstr\fP [\fBMaxChars\fP]"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMaxChars \fP\fP
.TP
\fB\fIMaxSize \fP\fP
.TP
\fB\fILenPos \fP\fP
.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> \fBSizeType\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::ShortString::GetLength () const\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> void \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::ShortString::SetLength (\fBSizeType\fP len)\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> static bool \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::ShortString::Usable (\fBSizeType\fP len)\fC [inline]\fP, \fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> \fBCh\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::ShortString::str[\fBMaxChars\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
