.TH "GenericDocument< Encoding, Allocator, StackAllocator >::ClearStackOnExit" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericDocument< Encoding, Allocator, StackAllocator >::ClearStackOnExit
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClearStackOnExit\fP (\fBGenericDocument\fP &d)"
.br
.ti -1c
.RI "\fB~ClearStackOnExit\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBClearStackOnExit\fP (const \fBClearStackOnExit\fP &)"
.br
.ti -1c
.RI "\fBClearStackOnExit\fP & \fBoperator=\fP (const \fBClearStackOnExit\fP &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBGenericDocument\fP & \fBd_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR, typename StackAllocator  = RAPIDJSON_DEFAULT_STACK_ALLOCATOR> \fBGenericDocument\fP< \fBEncoding\fP, \fBAllocator\fP, StackAllocator >::ClearStackOnExit::ClearStackOnExit (\fBGenericDocument\fP & d)\fC [inline]\fP, \fC [explicit]\fP"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR, typename StackAllocator  = RAPIDJSON_DEFAULT_STACK_ALLOCATOR> \fBGenericDocument\fP< \fBEncoding\fP, \fBAllocator\fP, StackAllocator >::ClearStackOnExit::~ClearStackOnExit ()\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR, typename StackAllocator  = RAPIDJSON_DEFAULT_STACK_ALLOCATOR> \fBGenericDocument\fP< \fBEncoding\fP, \fBAllocator\fP, StackAllocator >::ClearStackOnExit::ClearStackOnExit (const \fBClearStackOnExit\fP &)\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR, typename StackAllocator  = RAPIDJSON_DEFAULT_STACK_ALLOCATOR> \fBClearStackOnExit\fP & \fBGenericDocument\fP< \fBEncoding\fP, \fBAllocator\fP, StackAllocator >::ClearStackOnExit::operator= (const \fBClearStackOnExit\fP &)\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR, typename StackAllocator  = RAPIDJSON_DEFAULT_STACK_ALLOCATOR> \fBGenericDocument\fP& \fBGenericDocument\fP< \fBEncoding\fP, \fBAllocator\fP, StackAllocator >::ClearStackOnExit::d_\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
