.TH "GenericValue< Encoding, Allocator >::String" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericValue< Encoding, Allocator >::String
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <document\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSizeType\fP \fBlength\fP"
.br
.ti -1c
.RI "\fBSizeType\fP \fBhashcode\fP"
.br
.RI "reserved "
.ti -1c
.RI "const \fBCh\fP * \fBstr\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> \fBSizeType\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::String::hashcode"

.PP
reserved 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> \fBSizeType\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::String::length"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> const \fBCh\fP* \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::String::str"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
