.TH "GenericMember< Encoding, Allocator >" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericMember< Encoding, Allocator > \- Name-value pair in a JSON object value\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <document\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericMember\fP & \fBoperator=\fP (\fBGenericMember\fP &rhs) RAPIDJSON_NOEXCEPT"
.br
.RI "Assignment with move semantics\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP > \fBname\fP"
.br
.RI "name of member (must be a string) "
.ti -1c
.RI "\fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP > \fBvalue\fP"
.br
.RI "value of member\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericMember\fP (const \fBGenericMember\fP &rhs)"
.br
.RI "Copy constructor is not permitted\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "void \fBswap\fP (\fBGenericMember\fP &\fBa\fP, \fBGenericMember\fP &b) RAPIDJSON_NOEXCEPT"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename \fBEncoding\fP, typename \fBAllocator\fP>
.br
class GenericMember< Encoding, Allocator >"Name-value pair in a JSON object value\&. 

This class was internal to \fBGenericValue\fP\&. It used to be a inner struct\&. But a compiler (IBM XL C/C++ for AIX) have reported to have problem with that so it moved as a namespace scope struct\&. https://code.google.com/p/rapidjson/issues/detail?id=64 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP > \fBGenericMember\fP< \fBEncoding\fP, \fBAllocator\fP >\fB::GenericMember\fP (const \fBGenericMember\fP< \fBEncoding\fP, \fBAllocator\fP > & rhs)\fC [private]\fP"

.PP
Copy constructor is not permitted\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP > \fBGenericMember\fP & \fBGenericMember\fP< \fBEncoding\fP, \fBAllocator\fP >::operator= (\fBGenericMember\fP< \fBEncoding\fP, \fBAllocator\fP > & rhs)\fC [inline]\fP"

.PP
Assignment with move semantics\&. 
.PP
\fBParameters\fP
.RS 4
\fIrhs\fP Source of the assignment\&. Its name and value will become a null value after assignment\&. 
.RE
.PP

.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP > void swap (\fBGenericMember\fP< \fBEncoding\fP, \fBAllocator\fP > & a, \fBGenericMember\fP< \fBEncoding\fP, \fBAllocator\fP > & b)\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP > \fBGenericValue\fP<\fBEncoding\fP, \fBAllocator\fP> \fBGenericMember\fP< \fBEncoding\fP, \fBAllocator\fP >::name"

.PP
name of member (must be a string) 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP > \fBGenericValue\fP<\fBEncoding\fP, \fBAllocator\fP> \fBGenericMember\fP< \fBEncoding\fP, \fBAllocator\fP >::value"

.PP
value of member\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
