.TH "GenericValue< Encoding, Allocator >::Data" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericValue< Encoding, Allocator >::Data
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <document\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBString\fP \fBs\fP"
.br
.ti -1c
.RI "\fBShortString\fP \fBss\fP"
.br
.ti -1c
.RI "\fBNumber\fP \fBn\fP"
.br
.ti -1c
.RI "\fBObjectData\fP \fBo\fP"
.br
.ti -1c
.RI "\fBArrayData\fP \fBa\fP"
.br
.ti -1c
.RI "\fBFlag\fP \fBf\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> \fBArrayData\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::Data::a"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> \fBFlag\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::Data::f"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> \fBNumber\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::Data::n"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> \fBObjectData\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::Data::o"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> \fBString\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::Data::s"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> \fBShortString\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::Data::ss"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
