.TH "GenericPointer< ValueType, Allocator >::PercentEncodeStream< OutputStream >" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericPointer< ValueType, Allocator >::PercentEncodeStream< OutputStream > \- A helper stream to encode character (UTF-8 code unit) into percent-encoded sequence\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pointer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPercentEncodeStream\fP (OutputStream &os)"
.br
.ti -1c
.RI "void \fBPut\fP (char c)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "OutputStream & \fBos_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename \fBValueType\fP, typename \fBAllocator\fP = CrtAllocator>
.br
template<typename OutputStream>
.br
class GenericPointer< ValueType, Allocator >::PercentEncodeStream< OutputStream >"A helper stream to encode character (UTF-8 code unit) into percent-encoded sequence\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \fBValueType\fP , typename \fBAllocator\fP  = CrtAllocator> template<typename OutputStream > \fBGenericPointer\fP< \fBValueType\fP, \fBAllocator\fP >::PercentEncodeStream< OutputStream >::PercentEncodeStream (OutputStream & os)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBValueType\fP , typename \fBAllocator\fP  = CrtAllocator> template<typename OutputStream > void \fBGenericPointer\fP< \fBValueType\fP, \fBAllocator\fP >\fB::PercentEncodeStream\fP< OutputStream >::Put (char c)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBValueType\fP , typename \fBAllocator\fP  = CrtAllocator> template<typename OutputStream > OutputStream& \fBGenericPointer\fP< \fBValueType\fP, \fBAllocator\fP >\fB::PercentEncodeStream\fP< OutputStream >::os_\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
