.TH "GenericSchemaDocument< ValueT, Allocator >" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericSchemaDocument< ValueT, Allocator > \- JSON schema document\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schema\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef ValueT \fBValueType\fP"
.br
.ti -1c
.RI "typedef \fBIGenericRemoteSchemaDocumentProvider\fP< \fBGenericSchemaDocument\fP > \fBIRemoteSchemaDocumentProviderType\fP"
.br
.ti -1c
.RI "typedef \fBAllocator\fP \fBAllocatorType\fP"
.br
.ti -1c
.RI "typedef \fBValueType::EncodingType\fP \fBEncodingType\fP"
.br
.ti -1c
.RI "typedef EncodingType::Ch \fBCh\fP"
.br
.ti -1c
.RI "typedef \fBinternal::Schema\fP< \fBGenericSchemaDocument\fP > \fBSchemaType\fP"
.br
.ti -1c
.RI "typedef \fBGenericPointer\fP< \fBValueType\fP, \fBAllocator\fP > \fBPointerType\fP"
.br
.ti -1c
.RI "typedef \fBGenericValue\fP< \fBEncodingType\fP, \fBAllocatorType\fP > \fBSValue\fP"
.br
.ti -1c
.RI "typedef \fBGenericUri\fP< \fBValueType\fP, \fBAllocator\fP > \fBUriType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericSchemaDocument\fP (const \fBValueType\fP &document, const \fBCh\fP *uri=0, \fBSizeType\fP uriLength=0, \fBIRemoteSchemaDocumentProviderType\fP *remoteProvider=0, \fBAllocator\fP *allocator=0, const \fBPointerType\fP &\fBpointer\fP=\fBPointerType\fP())"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~GenericSchemaDocument\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "const \fBSValue\fP & \fBGetURI\fP () const"
.br
.ti -1c
.RI "const \fBSchemaType\fP & \fBGetRoot\fP () const"
.br
.RI "Get the root schema\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBinternal::Schema< GenericSchemaDocument >\fP"
.br
.ti -1c
.RI "template<typename , typename , typename > class \fBGenericSchemaValidator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename ValueT, typename \fBAllocator\fP = CrtAllocator>
.br
class GenericSchemaDocument< ValueT, Allocator >"JSON schema document\&. 

A JSON schema document is a compiled version of a JSON schema\&. It is basically a tree of \fBinternal::Schema\fP\&.
.PP
\fBNote\fP
.RS 4
This is an immutable class (i\&.e\&. its instance cannot be modified after construction)\&. 
.RE
.PP
\fBTemplate Parameters\fP
.RS 4
\fIValueT\fP Type of JSON value (e\&.g\&. \fCValue\fP ), which also determine the encoding\&. 
.br
\fIAllocator\fP Allocator type for allocating memory of this document\&. 
.RE
.PP

.SH "Member Typedef Documentation"
.PP 
.SS "template<typename ValueT , typename \fBAllocator\fP  = CrtAllocator> typedef \fBAllocator\fP \fBGenericSchemaDocument\fP< ValueT, \fBAllocator\fP >::AllocatorType"

.SS "template<typename ValueT , typename \fBAllocator\fP  = CrtAllocator> typedef EncodingType::Ch \fBGenericSchemaDocument\fP< ValueT, \fBAllocator\fP >::Ch"

.SS "template<typename ValueT , typename \fBAllocator\fP  = CrtAllocator> typedef \fBValueType::EncodingType\fP \fBGenericSchemaDocument\fP< ValueT, \fBAllocator\fP >::EncodingType"

.SS "template<typename ValueT , typename \fBAllocator\fP  = CrtAllocator> typedef \fBIGenericRemoteSchemaDocumentProvider\fP<\fBGenericSchemaDocument\fP> \fBGenericSchemaDocument\fP< ValueT, \fBAllocator\fP >::IRemoteSchemaDocumentProviderType"

.SS "template<typename ValueT , typename \fBAllocator\fP  = CrtAllocator> typedef \fBGenericPointer\fP<\fBValueType\fP, \fBAllocator\fP> \fBGenericSchemaDocument\fP< ValueT, \fBAllocator\fP >::PointerType"

.SS "template<typename ValueT , typename \fBAllocator\fP  = CrtAllocator> typedef \fBinternal::Schema\fP<\fBGenericSchemaDocument\fP> \fBGenericSchemaDocument\fP< ValueT, \fBAllocator\fP >::SchemaType"

.SS "template<typename ValueT , typename \fBAllocator\fP  = CrtAllocator> typedef \fBGenericValue\fP<\fBEncodingType\fP, \fBAllocatorType\fP> \fBGenericSchemaDocument\fP< ValueT, \fBAllocator\fP >::SValue"

.SS "template<typename ValueT , typename \fBAllocator\fP  = CrtAllocator> typedef \fBGenericUri\fP<\fBValueType\fP, \fBAllocator\fP> \fBGenericSchemaDocument\fP< ValueT, \fBAllocator\fP >::UriType"

.SS "template<typename ValueT , typename \fBAllocator\fP  = CrtAllocator> typedef ValueT \fBGenericSchemaDocument\fP< ValueT, \fBAllocator\fP >\fB::ValueType\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename ValueT , typename \fBAllocator\fP  = CrtAllocator> \fBGenericSchemaDocument\fP< ValueT, \fBAllocator\fP >\fB::GenericSchemaDocument\fP (const \fBValueType\fP & document, const \fBCh\fP * uri = \fC0\fP, \fBSizeType\fP uriLength = \fC0\fP, \fBIRemoteSchemaDocumentProviderType\fP * remoteProvider = \fC0\fP, \fBAllocator\fP * allocator = \fC0\fP, const \fBPointerType\fP & pointer = \fC\fBPointerType\fP()\fP)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Constructor\&. Compile a JSON document into schema document\&.
.PP
\fBParameters\fP
.RS 4
\fIdocument\fP A JSON document as source\&. 
.br
\fIuri\fP The base URI of this schema document for purposes of violation reporting\&. 
.br
\fIuriLength\fP Length of \fCname\fP, in code points\&. 
.br
\fIremoteProvider\fP An optional remote schema document provider for resolving remote reference\&. Can be null\&. 
.br
\fIallocator\fP An optional allocator instance for allocating memory\&. Can be null\&. 
.br
\fIpointer\fP An optional JSON pointer to the start of the schema document 
.RE
.PP

.SS "template<typename ValueT , typename \fBAllocator\fP  = CrtAllocator> \fBGenericSchemaDocument\fP< ValueT, \fBAllocator\fP >::~\fBGenericSchemaDocument\fP ()\fC [inline]\fP"

.PP
Destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename ValueT , typename \fBAllocator\fP  = CrtAllocator> const \fBSchemaType\fP & \fBGenericSchemaDocument\fP< ValueT, \fBAllocator\fP >::GetRoot () const\fC [inline]\fP"

.PP
Get the root schema\&. 
.SS "template<typename ValueT , typename \fBAllocator\fP  = CrtAllocator> const \fBSValue\fP & \fBGenericSchemaDocument\fP< ValueT, \fBAllocator\fP >::GetURI () const\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename ValueT , typename \fBAllocator\fP  = CrtAllocator> template<typename , typename , typename > friend class \fBGenericSchemaValidator\fP\fC [friend]\fP"

.SS "template<typename ValueT , typename \fBAllocator\fP  = CrtAllocator> friend class \fBinternal::Schema\fP< \fBGenericSchemaDocument\fP >\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
