.TH "GenericValue< Encoding, Allocator >::Flag" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericValue< Encoding, Allocator >::Flag
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <document\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBpayload\fP [sizeof(\fBSizeType\fP) *2+sizeof(void *)+2]"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBflags\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> \fBuint16_t\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::Flag::flags"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> char \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::Flag::payload[sizeof(\fBSizeType\fP) *2+sizeof(void *)+2]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
