.TH "GenericStringStream< Encoding >" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericStringStream< Encoding > \- Read-only string stream\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Encoding::Ch \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericStringStream\fP (const \fBCh\fP *src)"
.br
.ti -1c
.RI "\fBCh\fP \fBPeek\fP () const"
.br
.ti -1c
.RI "\fBCh\fP \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP () const"
.br
.ti -1c
.RI "\fBCh\fP * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "void \fBPut\fP (\fBCh\fP)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (\fBCh\fP *)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBCh\fP * \fBsrc_\fP"
.br
.RI "Current read position\&. "
.ti -1c
.RI "const \fBCh\fP * \fBhead_\fP"
.br
.RI "Original head of the string\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename \fBEncoding\fP>
.br
struct GenericStringStream< Encoding >"Read-only string stream\&. 


.PP
\fBNote\fP
.RS 4
implements Stream concept 
.RE
.PP

.SH "Member Typedef Documentation"
.PP 
.SS "template<typename \fBEncoding\fP > typedef Encoding::Ch \fBGenericStringStream\fP< \fBEncoding\fP >::Ch"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \fBEncoding\fP > \fBGenericStringStream\fP< \fBEncoding\fP >\fB::GenericStringStream\fP (const \fBCh\fP * src)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBEncoding\fP > void \fBGenericStringStream\fP< \fBEncoding\fP >::Flush ()\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > \fBCh\fP \fBGenericStringStream\fP< \fBEncoding\fP >::Peek () const\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > void \fBGenericStringStream\fP< \fBEncoding\fP >::Put (\fBCh\fP)\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > \fBCh\fP * \fBGenericStringStream\fP< \fBEncoding\fP >::PutBegin ()\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > size_t \fBGenericStringStream\fP< \fBEncoding\fP >::PutEnd (\fBCh\fP *)\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > \fBCh\fP \fBGenericStringStream\fP< \fBEncoding\fP >::Take ()\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > size_t \fBGenericStringStream\fP< \fBEncoding\fP >::Tell () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBEncoding\fP > const \fBCh\fP* \fBGenericStringStream\fP< \fBEncoding\fP >::head_"

.PP
Original head of the string\&. 
.SS "template<typename \fBEncoding\fP > const \fBCh\fP* \fBGenericStringStream\fP< \fBEncoding\fP >::src_"

.PP
Current read position\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
