.TH "GenericInsituStringStream< Encoding >" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericInsituStringStream< Encoding > \- A read-write string stream\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Encoding::Ch \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericInsituStringStream\fP (\fBCh\fP *src)"
.br
.ti -1c
.RI "\fBCh\fP \fBPeek\fP ()"
.br
.ti -1c
.RI "\fBCh\fP \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP ()"
.br
.ti -1c
.RI "void \fBPut\fP (\fBCh\fP c)"
.br
.ti -1c
.RI "\fBCh\fP * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (\fBCh\fP *begin)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "\fBCh\fP * \fBPush\fP (size_t count)"
.br
.ti -1c
.RI "void \fBPop\fP (size_t count)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCh\fP * \fBsrc_\fP"
.br
.ti -1c
.RI "\fBCh\fP * \fBdst_\fP"
.br
.ti -1c
.RI "\fBCh\fP * \fBhead_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename \fBEncoding\fP>
.br
struct GenericInsituStringStream< Encoding >"A read-write string stream\&. 

This string stream is particularly designed for in-situ parsing\&. 
.PP
\fBNote\fP
.RS 4
implements Stream concept 
.RE
.PP

.SH "Member Typedef Documentation"
.PP 
.SS "template<typename \fBEncoding\fP > typedef Encoding::Ch \fBGenericInsituStringStream\fP< \fBEncoding\fP >::Ch"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \fBEncoding\fP > \fBGenericInsituStringStream\fP< \fBEncoding\fP >\fB::GenericInsituStringStream\fP (\fBCh\fP * src)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBEncoding\fP > void \fBGenericInsituStringStream\fP< \fBEncoding\fP >::Flush ()\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > \fBCh\fP \fBGenericInsituStringStream\fP< \fBEncoding\fP >::Peek ()\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > void \fBGenericInsituStringStream\fP< \fBEncoding\fP >::Pop (size_t count)\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > \fBCh\fP * \fBGenericInsituStringStream\fP< \fBEncoding\fP >::Push (size_t count)\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > void \fBGenericInsituStringStream\fP< \fBEncoding\fP >::Put (\fBCh\fP c)\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > \fBCh\fP * \fBGenericInsituStringStream\fP< \fBEncoding\fP >::PutBegin ()\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > size_t \fBGenericInsituStringStream\fP< \fBEncoding\fP >::PutEnd (\fBCh\fP * begin)\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > \fBCh\fP \fBGenericInsituStringStream\fP< \fBEncoding\fP >::Take ()\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > size_t \fBGenericInsituStringStream\fP< \fBEncoding\fP >::Tell ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBEncoding\fP > \fBCh\fP* \fBGenericInsituStringStream\fP< \fBEncoding\fP >::dst_"

.SS "template<typename \fBEncoding\fP > \fBCh\fP* \fBGenericInsituStringStream\fP< \fBEncoding\fP >::head_"

.SS "template<typename \fBEncoding\fP > \fBCh\fP* \fBGenericInsituStringStream\fP< \fBEncoding\fP >::src_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
