.TH "GenericValue< Encoding, Allocator >::Number" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericValue< Encoding, Allocator >::Number
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <document\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBI\fP"
.br
.ti -1c
.RI "struct \fBU\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBGenericValue::Number::I\fP \fBi\fP"
.br
.ti -1c
.RI "struct \fBGenericValue::Number::U\fP \fBu\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBi64\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBu64\fP"
.br
.ti -1c
.RI "double \fBd\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> double \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::Number::d"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> struct \fBGenericValue::Number::I\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::Number::i"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> \fBint64_t\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::Number::i64"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> struct \fBGenericValue::Number::U\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::Number::u"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> \fBuint64_t\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::Number::u64"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
