.TH "GenericValue< Encoding, Allocator >::ObjectData" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericValue< Encoding, Allocator >::ObjectData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <document\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSizeType\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBSizeType\fP \fBcapacity\fP"
.br
.ti -1c
.RI "\fBMember\fP * \fBmembers\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> \fBSizeType\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::ObjectData::capacity"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> \fBMember\fP* \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::ObjectData::members"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = RAPIDJSON_DEFAULT_ALLOCATOR> \fBSizeType\fP \fBGenericValue\fP< \fBEncoding\fP, \fBAllocator\fP >::ObjectData::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
