.TH "Group" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Group
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGroup\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBgroupName\fP"
.br
.ti -1c
.RI "std::vector< \fBStudent\fP > \fBstudents\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Group::Group ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string Group::groupName"

.SS "std::vector<\fBStudent\fP> Group::students"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
