.TH "HandlerTerminateAtEndObject" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HandlerTerminateAtEndObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIterativeParsingReaderHandler< Encoding >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBEndObject\fP (\fBSizeType\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "bool HandlerTerminateAtEndObject::EndObject (\fBSizeType\fP)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
