.TH "IGenericRemoteSchemaDocumentProvider< SchemaDocumentType >" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IGenericRemoteSchemaDocumentProvider< SchemaDocumentType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schema\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef SchemaDocumentType::Ch \fBCh\fP"
.br
.ti -1c
.RI "typedef SchemaDocumentType::ValueType \fBValueType\fP"
.br
.ti -1c
.RI "typedef SchemaDocumentType::AllocatorType \fBAllocatorType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IGenericRemoteSchemaDocumentProvider\fP ()"
.br
.ti -1c
.RI "virtual const SchemaDocumentType * \fBGetRemoteDocument\fP (const \fBCh\fP *uri, \fBSizeType\fP length)=0"
.br
.ti -1c
.RI "virtual const SchemaDocumentType * \fBGetRemoteDocument\fP (\fBGenericUri\fP< \fBValueType\fP, \fBAllocatorType\fP > uri)"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename SchemaDocumentType > typedef SchemaDocumentType::AllocatorType \fBIGenericRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::AllocatorType"

.SS "template<typename SchemaDocumentType > typedef SchemaDocumentType::Ch \fBIGenericRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::Ch"

.SS "template<typename SchemaDocumentType > typedef SchemaDocumentType::ValueType \fBIGenericRemoteSchemaDocumentProvider\fP< SchemaDocumentType >\fB::ValueType\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename SchemaDocumentType > virtual \fBIGenericRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::~\fBIGenericRemoteSchemaDocumentProvider\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename SchemaDocumentType > virtual const SchemaDocumentType * \fBIGenericRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::GetRemoteDocument (const \fBCh\fP * uri, \fBSizeType\fP length)\fC [pure virtual]\fP"

.SS "template<typename SchemaDocumentType > virtual const SchemaDocumentType * \fBIGenericRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::GetRemoteDocument (\fBGenericUri\fP< \fBValueType\fP, \fBAllocatorType\fP > uri)\fC [inline]\fP, \fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
