.TH "imaxdiv_t" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imaxdiv_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <inttypes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBintmax_t\fP \fBquot\fP"
.br
.ti -1c
.RI "\fBintmax_t\fP \fBrem\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBintmax_t\fP imaxdiv_t::quot"

.SS "\fBintmax_t\fP imaxdiv_t::rem"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
