.TH "internal::DecodedStream< SourceStream, Encoding >" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::DecodedStream< SourceStream, Encoding >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <regex\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecodedStream\fP (SourceStream &ss)"
.br
.ti -1c
.RI "unsigned \fBPeek\fP ()"
.br
.ti -1c
.RI "unsigned \fBTake\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename SourceStream , typename \fBEncoding\fP > \fBinternal::DecodedStream\fP< SourceStream, \fBEncoding\fP >::DecodedStream (SourceStream & ss)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename SourceStream , typename \fBEncoding\fP > unsigned \fBinternal::DecodedStream\fP< SourceStream, \fBEncoding\fP >::Peek ()\fC [inline]\fP"

.SS "template<typename SourceStream , typename \fBEncoding\fP > unsigned \fBinternal::DecodedStream\fP< SourceStream, \fBEncoding\fP >::Take ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
