.TH "internal::Schema< SchemaDocumentType >::Property" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::Schema< SchemaDocumentType >::Property
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProperty\fP ()"
.br
.ti -1c
.RI "\fB~Property\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSValue\fP \fBname\fP"
.br
.ti -1c
.RI "const \fBSchemaType\fP * \fBschema\fP"
.br
.ti -1c
.RI "const \fBSchemaType\fP * \fBdependenciesSchema\fP"
.br
.ti -1c
.RI "\fBSizeType\fP \fBdependenciesValidatorIndex\fP"
.br
.ti -1c
.RI "bool * \fBdependencies\fP"
.br
.ti -1c
.RI "bool \fBrequired\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename SchemaDocumentType > \fBinternal::Schema\fP< SchemaDocumentType >::Property::Property ()\fC [inline]\fP"

.SS "template<typename SchemaDocumentType > \fBinternal::Schema\fP< SchemaDocumentType >::Property::~Property ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename SchemaDocumentType > bool* \fBinternal::Schema\fP< SchemaDocumentType >::Property::dependencies"

.SS "template<typename SchemaDocumentType > const \fBSchemaType\fP* \fBinternal::Schema\fP< SchemaDocumentType >::Property::dependenciesSchema"

.SS "template<typename SchemaDocumentType > \fBSizeType\fP \fBinternal::Schema\fP< SchemaDocumentType >::Property::dependenciesValidatorIndex"

.SS "template<typename SchemaDocumentType > \fBSValue\fP \fBinternal::Schema\fP< SchemaDocumentType >::Property::name"

.SS "template<typename SchemaDocumentType > bool \fBinternal::Schema\fP< SchemaDocumentType >::Property::required"

.SS "template<typename SchemaDocumentType > const \fBSchemaType\fP* \fBinternal::Schema\fP< SchemaDocumentType >::Property::schema"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
