.TH "internal::IsRefCounted< typename, typename >" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::IsRefCounted< typename, typename >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <allocators\&.h>\fP
.PP
Inherits FalseType\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
