.TH "internal::Schema< SchemaDocumentType >::PatternProperty" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::Schema< SchemaDocumentType >::PatternProperty
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPatternProperty\fP ()"
.br
.ti -1c
.RI "\fB~PatternProperty\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBSchemaType\fP * \fBschema\fP"
.br
.ti -1c
.RI "\fBRegexType\fP * \fBpattern\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename SchemaDocumentType > \fBinternal::Schema\fP< SchemaDocumentType >::PatternProperty::PatternProperty ()\fC [inline]\fP"

.SS "template<typename SchemaDocumentType > \fBinternal::Schema\fP< SchemaDocumentType >::PatternProperty::~PatternProperty ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename SchemaDocumentType > \fBRegexType\fP* \fBinternal::Schema\fP< SchemaDocumentType >::PatternProperty::pattern"

.SS "template<typename SchemaDocumentType > const \fBSchemaType\fP* \fBinternal::Schema\fP< SchemaDocumentType >::PatternProperty::schema"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
