.TH "internal::TypeHelper< ValueType, uint64_t >" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::TypeHelper< ValueType, uint64_t >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <document\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIs\fP (const \fBValueType\fP &v)"
.br
.ti -1c
.RI "static \fBuint64_t\fP \fBGet\fP (const \fBValueType\fP &v)"
.br
.ti -1c
.RI "static \fBValueType\fP & \fBSet\fP (\fBValueType\fP &v, \fBuint64_t\fP data)"
.br
.ti -1c
.RI "static \fBValueType\fP & \fBSet\fP (\fBValueType\fP &v, \fBuint64_t\fP data, typename \fBValueType::AllocatorType\fP &)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBValueType\fP > static \fBuint64_t\fP \fBinternal::TypeHelper\fP< \fBValueType\fP, \fBuint64_t\fP >::Get (const \fBValueType\fP & v)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename \fBValueType\fP > static bool \fBinternal::TypeHelper\fP< \fBValueType\fP, \fBuint64_t\fP >::Is (const \fBValueType\fP & v)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename \fBValueType\fP > static \fBValueType\fP & \fBinternal::TypeHelper\fP< \fBValueType\fP, \fBuint64_t\fP >::Set (\fBValueType\fP & v, \fBuint64_t\fP data)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename \fBValueType\fP > static \fBValueType\fP & \fBinternal::TypeHelper\fP< \fBValueType\fP, \fBuint64_t\fP >::Set (\fBValueType\fP & v, \fBuint64_t\fP data, typename \fBValueType::AllocatorType\fP &)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
