.TH "internal::GenericRegex< Encoding, Allocator >::State" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::GenericRegex< Encoding, Allocator >::State
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSizeType\fP \fBout\fP"
.br
.RI "Equals to kInvalid for matching state\&. "
.ti -1c
.RI "\fBSizeType\fP \fBout1\fP"
.br
.RI "Equals to non-kInvalid for split\&. "
.ti -1c
.RI "\fBSizeType\fP \fBrangeStart\fP"
.br
.ti -1c
.RI "unsigned \fBcodepoint\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = CrtAllocator> unsigned \fBinternal::GenericRegex\fP< \fBEncoding\fP, \fBAllocator\fP >::State::codepoint"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = CrtAllocator> \fBSizeType\fP \fBinternal::GenericRegex\fP< \fBEncoding\fP, \fBAllocator\fP >::State::out"

.PP
Equals to kInvalid for matching state\&. 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = CrtAllocator> \fBSizeType\fP \fBinternal::GenericRegex\fP< \fBEncoding\fP, \fBAllocator\fP >::State::out1"

.PP
Equals to non-kInvalid for split\&. 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = CrtAllocator> \fBSizeType\fP \fBinternal::GenericRegex\fP< \fBEncoding\fP, \fBAllocator\fP >::State::rangeStart"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
