.TH "internal::StreamLocalCopy< Stream, 0 >" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::StreamLocalCopy< Stream, 0 > \- Keep reference\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStreamLocalCopy\fP (\fBStream\fP &original)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBStream\fP & \fBs\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBStreamLocalCopy\fP & \fBoperator=\fP (const \fBStreamLocalCopy\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename \fBStream\fP>
.br
class internal::StreamLocalCopy< Stream, 0 >"Keep reference\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \fBStream\fP > \fBinternal::StreamLocalCopy\fP< \fBStream\fP, 0 >::StreamLocalCopy (\fBStream\fP & original)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBStream\fP > \fBStreamLocalCopy\fP & \fBinternal::StreamLocalCopy\fP< \fBStream\fP, 0 >::operator= (const \fBStreamLocalCopy\fP< \fBStream\fP, 0 > &)\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBStream\fP > \fBStream\fP& \fBinternal::StreamLocalCopy\fP< \fBStream\fP, 0 >::s"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
