.TH "internal::SchemaValidationContext< SchemaDocumentType >" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::SchemaValidationContext< SchemaDocumentType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schema\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBPatternValidatorType\fP { \fBkPatternValidatorOnly\fP, \fBkPatternValidatorWithProperty\fP, \fBkPatternValidatorWithAdditionalProperty\fP }"
.br
.ti -1c
.RI "typedef \fBSchema\fP< SchemaDocumentType > \fBSchemaType\fP"
.br
.ti -1c
.RI "typedef \fBISchemaStateFactory\fP< \fBSchemaType\fP > \fBSchemaValidatorFactoryType\fP"
.br
.ti -1c
.RI "typedef \fBIValidationErrorHandler\fP< \fBSchemaType\fP > \fBErrorHandlerType\fP"
.br
.ti -1c
.RI "typedef \fBSchemaType::ValueType\fP \fBValueType\fP"
.br
.ti -1c
.RI "typedef \fBValueType::Ch\fP \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSchemaValidationContext\fP (\fBSchemaValidatorFactoryType\fP &f, \fBErrorHandlerType\fP &eh, const \fBSchemaType\fP *s)"
.br
.ti -1c
.RI "\fB~SchemaValidationContext\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSchemaValidatorFactoryType\fP & \fBfactory\fP"
.br
.ti -1c
.RI "\fBErrorHandlerType\fP & \fBerror_handler\fP"
.br
.ti -1c
.RI "const \fBSchemaType\fP * \fBschema\fP"
.br
.ti -1c
.RI "const \fBSchemaType\fP * \fBvalueSchema\fP"
.br
.ti -1c
.RI "const \fBCh\fP * \fBinvalidKeyword\fP"
.br
.ti -1c
.RI "\fBValidateErrorCode\fP \fBinvalidCode\fP"
.br
.ti -1c
.RI "void * \fBhasher\fP"
.br
.ti -1c
.RI "void * \fBarrayElementHashCodes\fP"
.br
.ti -1c
.RI "\fBISchemaValidator\fP ** \fBvalidators\fP"
.br
.ti -1c
.RI "\fBSizeType\fP \fBvalidatorCount\fP"
.br
.ti -1c
.RI "\fBISchemaValidator\fP ** \fBpatternPropertiesValidators\fP"
.br
.ti -1c
.RI "\fBSizeType\fP \fBpatternPropertiesValidatorCount\fP"
.br
.ti -1c
.RI "const \fBSchemaType\fP ** \fBpatternPropertiesSchemas\fP"
.br
.ti -1c
.RI "\fBSizeType\fP \fBpatternPropertiesSchemaCount\fP"
.br
.ti -1c
.RI "\fBPatternValidatorType\fP \fBvaluePatternValidatorType\fP"
.br
.ti -1c
.RI "\fBPatternValidatorType\fP \fBobjectPatternValidatorType\fP"
.br
.ti -1c
.RI "\fBSizeType\fP \fBarrayElementIndex\fP"
.br
.ti -1c
.RI "bool * \fBpropertyExist\fP"
.br
.ti -1c
.RI "bool \fBinArray\fP"
.br
.ti -1c
.RI "bool \fBvalueUniqueness\fP"
.br
.ti -1c
.RI "bool \fBarrayUniqueness\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename SchemaDocumentType > typedef \fBValueType::Ch\fP \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::Ch"

.SS "template<typename SchemaDocumentType > typedef \fBIValidationErrorHandler\fP<\fBSchemaType\fP> \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::ErrorHandlerType"

.SS "template<typename SchemaDocumentType > typedef \fBSchema\fP<SchemaDocumentType> \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::SchemaType"

.SS "template<typename SchemaDocumentType > typedef \fBISchemaStateFactory\fP<\fBSchemaType\fP> \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::SchemaValidatorFactoryType"

.SS "template<typename SchemaDocumentType > typedef \fBSchemaType::ValueType\fP \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >\fB::ValueType\fP"

.SH "Member Enumeration Documentation"
.PP 
.SS "template<typename SchemaDocumentType > enum \fBinternal::SchemaValidationContext::PatternValidatorType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIkPatternValidatorOnly \fP\fP
.TP
\fB\fIkPatternValidatorWithProperty \fP\fP
.TP
\fB\fIkPatternValidatorWithAdditionalProperty \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename SchemaDocumentType > \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::SchemaValidationContext (\fBSchemaValidatorFactoryType\fP & f, \fBErrorHandlerType\fP & eh, const \fBSchemaType\fP * s)\fC [inline]\fP"

.SS "template<typename SchemaDocumentType > \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::~\fBSchemaValidationContext\fP ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename SchemaDocumentType > void* \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::arrayElementHashCodes"

.SS "template<typename SchemaDocumentType > \fBSizeType\fP \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::arrayElementIndex"

.SS "template<typename SchemaDocumentType > bool \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::arrayUniqueness"

.SS "template<typename SchemaDocumentType > \fBErrorHandlerType\fP& \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::error_handler"

.SS "template<typename SchemaDocumentType > \fBSchemaValidatorFactoryType\fP& \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::factory"

.SS "template<typename SchemaDocumentType > void* \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::hasher"

.SS "template<typename SchemaDocumentType > bool \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::inArray"

.SS "template<typename SchemaDocumentType > \fBValidateErrorCode\fP \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::invalidCode"

.SS "template<typename SchemaDocumentType > const \fBCh\fP* \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::invalidKeyword"

.SS "template<typename SchemaDocumentType > \fBPatternValidatorType\fP \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::objectPatternValidatorType"

.SS "template<typename SchemaDocumentType > \fBSizeType\fP \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::patternPropertiesSchemaCount"

.SS "template<typename SchemaDocumentType > const \fBSchemaType\fP** \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::patternPropertiesSchemas"

.SS "template<typename SchemaDocumentType > \fBSizeType\fP \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::patternPropertiesValidatorCount"

.SS "template<typename SchemaDocumentType > \fBISchemaValidator\fP** \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::patternPropertiesValidators"

.SS "template<typename SchemaDocumentType > bool* \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::propertyExist"

.SS "template<typename SchemaDocumentType > const \fBSchemaType\fP* \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::schema"

.SS "template<typename SchemaDocumentType > \fBSizeType\fP \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::validatorCount"

.SS "template<typename SchemaDocumentType > \fBISchemaValidator\fP** \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::validators"

.SS "template<typename SchemaDocumentType > \fBPatternValidatorType\fP \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::valuePatternValidatorType"

.SS "template<typename SchemaDocumentType > const \fBSchemaType\fP* \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::valueSchema"

.SS "template<typename SchemaDocumentType > bool \fBinternal::SchemaValidationContext\fP< SchemaDocumentType >::valueUniqueness"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
