.TH "internal::ISchemaValidator" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::ISchemaValidator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schema\&.h>\fP
.PP
Inherited by \fBGenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ISchemaValidator\fP ()"
.br
.ti -1c
.RI "virtual bool \fBIsValid\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBSetValidateFlags\fP (unsigned flags)=0"
.br
.ti -1c
.RI "virtual unsigned \fBGetValidateFlags\fP () const =0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual internal::ISchemaValidator::~ISchemaValidator ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual unsigned internal::ISchemaValidator::GetValidateFlags () const\fC [pure virtual]\fP"

.PP
Implemented in \fBGenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >\fP\&.
.SS "virtual bool internal::ISchemaValidator::IsValid () const\fC [pure virtual]\fP"

.PP
Implemented in \fBGenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >\fP\&.
.SS "virtual void internal::ISchemaValidator::SetValidateFlags (unsigned flags)\fC [pure virtual]\fP"

.PP
Implemented in \fBGenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
