.TH "internal::TokenHelper< Stack, char >" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::TokenHelper< Stack, char >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schema\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static RAPIDJSON_FORCEINLINE void \fBAppendIndexToken\fP (\fBStack\fP &documentStack, \fBSizeType\fP index)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBStack\fP > static RAPIDJSON_FORCEINLINE void \fBinternal::TokenHelper\fP< \fBStack\fP, char >::AppendIndexToken (\fBStack\fP & documentStack, \fBSizeType\fP index)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
