.TH "internal::ISchemaStateFactory< SchemaType >" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::ISchemaStateFactory< SchemaType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schema\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ISchemaStateFactory\fP ()"
.br
.ti -1c
.RI "virtual \fBISchemaValidator\fP * \fBCreateSchemaValidator\fP (const SchemaType &, const bool inheritContinueOnErrors)=0"
.br
.ti -1c
.RI "virtual void \fBDestroySchemaValidator\fP (\fBISchemaValidator\fP *validator)=0"
.br
.ti -1c
.RI "virtual void * \fBCreateHasher\fP ()=0"
.br
.ti -1c
.RI "virtual \fBuint64_t\fP \fBGetHashCode\fP (void *hasher)=0"
.br
.ti -1c
.RI "virtual void \fBDestroryHasher\fP (void *hasher)=0"
.br
.ti -1c
.RI "virtual void * \fBMallocState\fP (size_t size)=0"
.br
.ti -1c
.RI "virtual void \fBFreeState\fP (void *p)=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename SchemaType > virtual \fBinternal::ISchemaStateFactory\fP< SchemaType >::~\fBISchemaStateFactory\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename SchemaType > virtual void * \fBinternal::ISchemaStateFactory\fP< SchemaType >::CreateHasher ()\fC [pure virtual]\fP"

.PP
Implemented in \fBGenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >\fP\&.
.SS "template<typename SchemaType > virtual \fBISchemaValidator\fP * \fBinternal::ISchemaStateFactory\fP< SchemaType >::CreateSchemaValidator (const SchemaType &, const bool inheritContinueOnErrors)\fC [pure virtual]\fP"

.PP
Implemented in \fBGenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >\fP\&.
.SS "template<typename SchemaType > virtual void \fBinternal::ISchemaStateFactory\fP< SchemaType >::DestroryHasher (void * hasher)\fC [pure virtual]\fP"

.PP
Implemented in \fBGenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >\fP\&.
.SS "template<typename SchemaType > virtual void \fBinternal::ISchemaStateFactory\fP< SchemaType >::DestroySchemaValidator (\fBISchemaValidator\fP * validator)\fC [pure virtual]\fP"

.SS "template<typename SchemaType > virtual void \fBinternal::ISchemaStateFactory\fP< SchemaType >::FreeState (void * p)\fC [pure virtual]\fP"

.PP
Implemented in \fBGenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >\fP\&.
.SS "template<typename SchemaType > virtual \fBuint64_t\fP \fBinternal::ISchemaStateFactory\fP< SchemaType >::GetHashCode (void * hasher)\fC [pure virtual]\fP"

.PP
Implemented in \fBGenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >\fP\&.
.SS "template<typename SchemaType > virtual void * \fBinternal::ISchemaStateFactory\fP< SchemaType >::MallocState (size_t size)\fC [pure virtual]\fP"

.PP
Implemented in \fBGenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
