.TH "internal::GenericRegex< Encoding, Allocator >::Frag" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::GenericRegex< Encoding, Allocator >::Frag
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFrag\fP (\fBSizeType\fP s, \fBSizeType\fP o, \fBSizeType\fP m)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSizeType\fP \fBstart\fP"
.br
.ti -1c
.RI "\fBSizeType\fP \fBout\fP"
.br
.RI "link-list of all output states "
.ti -1c
.RI "\fBSizeType\fP \fBminIndex\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = CrtAllocator> \fBinternal::GenericRegex\fP< \fBEncoding\fP, \fBAllocator\fP >::Frag::Frag (\fBSizeType\fP s, \fBSizeType\fP o, \fBSizeType\fP m)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = CrtAllocator> \fBSizeType\fP \fBinternal::GenericRegex\fP< \fBEncoding\fP, \fBAllocator\fP >::Frag::minIndex"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = CrtAllocator> \fBSizeType\fP \fBinternal::GenericRegex\fP< \fBEncoding\fP, \fBAllocator\fP >::Frag::out"

.PP
link-list of all output states 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP  = CrtAllocator> \fBSizeType\fP \fBinternal::GenericRegex\fP< \fBEncoding\fP, \fBAllocator\fP >::Frag::start"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
