.TH "internal::Hasher< Encoding, Allocator >::Number" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::Hasher< Encoding, Allocator >::Number
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "union \fBU\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union \fBinternal::Hasher::Number::U\fP \fBu\fP"
.br
.ti -1c
.RI "double \fBd\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP > double \fBinternal::Hasher\fP< \fBEncoding\fP, \fBAllocator\fP >::Number::d"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP > union \fBinternal::Hasher::Number::U\fP \fBinternal::Hasher\fP< \fBEncoding\fP, \fBAllocator\fP >::Number::u"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
