.TH "internal::Schema< SchemaDocumentType >::SchemaArray" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::Schema< SchemaDocumentType >::SchemaArray
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSchemaArray\fP ()"
.br
.ti -1c
.RI "\fB~SchemaArray\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBSchemaType\fP ** \fBschemas\fP"
.br
.ti -1c
.RI "\fBSizeType\fP \fBbegin\fP"
.br
.ti -1c
.RI "\fBSizeType\fP \fBcount\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename SchemaDocumentType > \fBinternal::Schema\fP< SchemaDocumentType >::SchemaArray::SchemaArray ()\fC [inline]\fP"

.SS "template<typename SchemaDocumentType > \fBinternal::Schema\fP< SchemaDocumentType >::SchemaArray::~SchemaArray ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename SchemaDocumentType > \fBSizeType\fP \fBinternal::Schema\fP< SchemaDocumentType >::SchemaArray::begin"

.SS "template<typename SchemaDocumentType > \fBSizeType\fP \fBinternal::Schema\fP< SchemaDocumentType >::SchemaArray::count"

.SS "template<typename SchemaDocumentType > const \fBSchemaType\fP** \fBinternal::Schema\fP< SchemaDocumentType >::SchemaArray::schemas"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
