.TH "internal::Hasher< Encoding, Allocator >::Number::U" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::Hasher< Encoding, Allocator >::Number::U
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schema\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint64_t\fP \fBu\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBi\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP > \fBint64_t\fP \fBinternal::Hasher\fP< \fBEncoding\fP, \fBAllocator\fP >::Number::U::i"

.SS "template<typename \fBEncoding\fP , typename \fBAllocator\fP > \fBuint64_t\fP \fBinternal::Hasher\fP< \fBEncoding\fP, \fBAllocator\fP >::Number::U::u"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
