.TH "internal::Double" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::Double
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ieee754\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDouble\fP ()"
.br
.ti -1c
.RI "\fBDouble\fP (double d)"
.br
.ti -1c
.RI "\fBDouble\fP (\fBuint64_t\fP u)"
.br
.ti -1c
.RI "double \fBValue\fP () const"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBUint64Value\fP () const"
.br
.ti -1c
.RI "double \fBNextPositiveDouble\fP () const"
.br
.ti -1c
.RI "bool \fBSign\fP () const"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBSignificand\fP () const"
.br
.ti -1c
.RI "int \fBExponent\fP () const"
.br
.ti -1c
.RI "bool \fBIsNan\fP () const"
.br
.ti -1c
.RI "bool \fBIsInf\fP () const"
.br
.ti -1c
.RI "bool \fBIsNanOrInf\fP () const"
.br
.ti -1c
.RI "bool \fBIsNormal\fP () const"
.br
.ti -1c
.RI "bool \fBIsZero\fP () const"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBIntegerSignificand\fP () const"
.br
.ti -1c
.RI "int \fBIntegerExponent\fP () const"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBToBias\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBEffectiveSignificandSize\fP (int order)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   double \fBd_\fP"
.br
.ti -1c
.RI "   \fBuint64_t\fP \fBu_\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static const int \fBkSignificandSize\fP = 52"
.br
.ti -1c
.RI "static const int \fBkExponentBias\fP = 0x3FF"
.br
.ti -1c
.RI "static const int \fBkDenormalExponent\fP = 1 \- \fBkExponentBias\fP"
.br
.ti -1c
.RI "static const \fBuint64_t\fP \fBkSignMask\fP = \fBRAPIDJSON_UINT64_C2\fP(0x80000000, 0x00000000)"
.br
.ti -1c
.RI "static const \fBuint64_t\fP \fBkExponentMask\fP = \fBRAPIDJSON_UINT64_C2\fP(0x7FF00000, 0x00000000)"
.br
.ti -1c
.RI "static const \fBuint64_t\fP \fBkSignificandMask\fP = \fBRAPIDJSON_UINT64_C2\fP(0x000FFFFF, 0xFFFFFFFF)"
.br
.ti -1c
.RI "static const \fBuint64_t\fP \fBkHiddenBit\fP = \fBRAPIDJSON_UINT64_C2\fP(0x00100000, 0x00000000)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "internal::Double::Double ()\fC [inline]\fP"

.SS "internal::Double::Double (double d)\fC [inline]\fP"

.SS "internal::Double::Double (\fBuint64_t\fP u)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static int internal::Double::EffectiveSignificandSize (int order)\fC [inline]\fP, \fC [static]\fP"

.SS "int internal::Double::Exponent () const\fC [inline]\fP"

.SS "int internal::Double::IntegerExponent () const\fC [inline]\fP"

.SS "\fBuint64_t\fP internal::Double::IntegerSignificand () const\fC [inline]\fP"

.SS "bool internal::Double::IsInf () const\fC [inline]\fP"

.SS "bool internal::Double::IsNan () const\fC [inline]\fP"

.SS "bool internal::Double::IsNanOrInf () const\fC [inline]\fP"

.SS "bool internal::Double::IsNormal () const\fC [inline]\fP"

.SS "bool internal::Double::IsZero () const\fC [inline]\fP"

.SS "double internal::Double::NextPositiveDouble () const\fC [inline]\fP"

.SS "bool internal::Double::Sign () const\fC [inline]\fP"

.SS "\fBuint64_t\fP internal::Double::Significand () const\fC [inline]\fP"

.SS "\fBuint64_t\fP internal::Double::ToBias () const\fC [inline]\fP"

.SS "\fBuint64_t\fP internal::Double::Uint64Value () const\fC [inline]\fP"

.SS "double internal::Double::Value () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "union  { \&.\&.\&. }  internal::Double::@8\fC [private]\fP"

.SS "double internal::Double::d_"

.SS "const int internal::Double::kDenormalExponent = 1 \- \fBkExponentBias\fP\fC [static]\fP, \fC [private]\fP"

.SS "const int internal::Double::kExponentBias = 0x3FF\fC [static]\fP, \fC [private]\fP"

.SS "const \fBuint64_t\fP internal::Double::kExponentMask = \fBRAPIDJSON_UINT64_C2\fP(0x7FF00000, 0x00000000)\fC [static]\fP, \fC [private]\fP"

.SS "const \fBuint64_t\fP internal::Double::kHiddenBit = \fBRAPIDJSON_UINT64_C2\fP(0x00100000, 0x00000000)\fC [static]\fP, \fC [private]\fP"

.SS "const \fBuint64_t\fP internal::Double::kSignificandMask = \fBRAPIDJSON_UINT64_C2\fP(0x000FFFFF, 0xFFFFFFFF)\fC [static]\fP, \fC [private]\fP"

.SS "const int internal::Double::kSignificandSize = 52\fC [static]\fP, \fC [private]\fP"

.SS "const \fBuint64_t\fP internal::Double::kSignMask = \fBRAPIDJSON_UINT64_C2\fP(0x80000000, 0x00000000)\fC [static]\fP, \fC [private]\fP"

.SS "\fBuint64_t\fP internal::Double::u_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
