.TH "internal::StreamLocalCopy< Stream, 0 >" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::StreamLocalCopy< Stream, 0 > \- Keep reference\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStreamLocalCopy\fP (\fBStream\fP &original)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBStream\fP & \fBs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename \fBStream\fP>
.br
class internal::StreamLocalCopy< Stream, 0 >"Keep reference\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \fBStream\fP > \fBinternal::StreamLocalCopy\fP< \fBStream\fP, 0 >::StreamLocalCopy (\fBStream\fP & original)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBStream\fP > \fBStream\fP& \fBinternal::StreamLocalCopy\fP< \fBStream\fP, 0 >::s"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
