.TH "src/rapidjson/include/rapidjson/istreamwrapper.h" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/istreamwrapper.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stream\&.h'\fP
.br
\fC#include <iosfwd>\fP
.br
\fC#include <ios>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBasicIStreamWrapper< StreamType >\fP"
.br
.RI "Wrapper of \fCstd::basic_istream\fP into RapidJSON's Stream concept\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBBasicIStreamWrapper\fP< std::istream > \fBIStreamWrapper\fP"
.br
.ti -1c
.RI "typedef \fBBasicIStreamWrapper\fP< std::wistream > \fBWIStreamWrapper\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBBasicIStreamWrapper\fP<std::istream> \fBIStreamWrapper\fP"

.SS "typedef \fBBasicIStreamWrapper\fP<std::wistream> \fBWIStreamWrapper\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
