.TH "src/rapidjson/test/unittest/istreamwrappertest.cpp" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/istreamwrappertest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/istreamwrapper\&.h'\fP
.br
\fC#include 'rapidjson/encodedstream\&.h'\fP
.br
\fC#include 'rapidjson/document\&.h'\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <fstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename StringStreamType > static void \fBTestStringStream\fP ()"
.br
.ti -1c
.RI "\fBTEST\fP (\fBIStreamWrapper\fP, istringstream)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBIStreamWrapper\fP, stringstream)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBIStreamWrapper\fP, wistringstream)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBIStreamWrapper\fP, wstringstream)"
.br
.ti -1c
.RI "template<typename FileStreamType > static bool \fBOpen\fP (FileStreamType &fs, const char *filename)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBIStreamWrapper\fP, ifstream)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBIStreamWrapper\fP, fstream)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename FileStreamType > static bool Open (FileStreamType & fs, const char * filename)\fC [static]\fP"

.SS "TEST (\fBIStreamWrapper\fP, fstream)"

.SS "TEST (\fBIStreamWrapper\fP, ifstream)"

.SS "TEST (\fBIStreamWrapper\fP, istringstream)"

.SS "TEST (\fBIStreamWrapper\fP, stringstream)"

.SS "TEST (\fBIStreamWrapper\fP, wistringstream)"

.SS "TEST (\fBIStreamWrapper\fP, wstringstream)"

.SS "template<typename StringStreamType > static void TestStringStream ()\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
