.TH "IStreamWrapper" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IStreamWrapper
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef char \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIStreamWrapper\fP (std::istream &is)"
.br
.ti -1c
.RI "\fBCh\fP \fBPeek\fP () const"
.br
.ti -1c
.RI "\fBCh\fP \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP () const"
.br
.ti -1c
.RI "\fBCh\fP * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "void \fBPut\fP (\fBCh\fP)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (\fBCh\fP *)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBIStreamWrapper\fP (const \fBIStreamWrapper\fP &)"
.br
.ti -1c
.RI "\fBIStreamWrapper\fP & \fBoperator=\fP (const \fBIStreamWrapper\fP &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::istream & \fBis_\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef char \fBIStreamWrapper::Ch\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "IStreamWrapper::IStreamWrapper (std::istream & is)\fC [inline]\fP"

.SS "IStreamWrapper::IStreamWrapper (const \fBIStreamWrapper\fP &)\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void IStreamWrapper::Flush ()\fC [inline]\fP"

.SS "\fBIStreamWrapper\fP & IStreamWrapper::operator= (const \fBIStreamWrapper\fP &)\fC [private]\fP"

.SS "\fBCh\fP IStreamWrapper::Peek () const\fC [inline]\fP"

.SS "void IStreamWrapper::Put (\fBCh\fP)\fC [inline]\fP"

.SS "\fBCh\fP * IStreamWrapper::PutBegin ()\fC [inline]\fP"

.SS "size_t IStreamWrapper::PutEnd (\fBCh\fP *)\fC [inline]\fP"

.SS "\fBCh\fP IStreamWrapper::Take ()\fC [inline]\fP"

.SS "size_t IStreamWrapper::Tell () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::istream& IStreamWrapper::is_\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
