.TH "src/rapidjson/test/unittest/itoatest.cpp" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/itoatest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/internal/itoa\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTraits< T >\fP"
.br
.ti -1c
.RI "struct \fBTraits< uint32_t >\fP"
.br
.ti -1c
.RI "struct \fBTraits< int32_t >\fP"
.br
.ti -1c
.RI "struct \fBTraits< uint64_t >\fP"
.br
.ti -1c
.RI "struct \fBTraits< int64_t >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBT\fP > static void \fBVerifyValue\fP (\fBT\fP \fBvalue\fP, void(*f)(\fBT\fP, char *), char *(*g)(\fBT\fP, char *))"
.br
.ti -1c
.RI "template<typename \fBT\fP > static void \fBVerify\fP (void(*f)(\fBT\fP, char *), char *(*g)(\fBT\fP, char *))"
.br
.ti -1c
.RI "static void \fBu32toa_naive\fP (\fBuint32_t\fP \fBvalue\fP, char *buffer)"
.br
.ti -1c
.RI "static void \fBi32toa_naive\fP (\fBint32_t\fP \fBvalue\fP, char *buffer)"
.br
.ti -1c
.RI "static void \fBu64toa_naive\fP (\fBuint64_t\fP \fBvalue\fP, char *buffer)"
.br
.ti -1c
.RI "static void \fBi64toa_naive\fP (\fBint64_t\fP \fBvalue\fP, char *buffer)"
.br
.ti -1c
.RI "\fBTEST\fP (itoa, u32toa)"
.br
.ti -1c
.RI "\fBTEST\fP (itoa, i32toa)"
.br
.ti -1c
.RI "\fBTEST\fP (itoa, u64toa)"
.br
.ti -1c
.RI "\fBTEST\fP (itoa, i64toa)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void i32toa_naive (\fBint32_t\fP value, char * buffer)\fC [static]\fP"

.SS "static void i64toa_naive (\fBint64_t\fP value, char * buffer)\fC [static]\fP"

.SS "TEST (itoa, i32toa)"

.SS "TEST (itoa, i64toa)"

.SS "TEST (itoa, u32toa)"

.SS "TEST (itoa, u64toa)"

.SS "static void u32toa_naive (\fBuint32_t\fP value, char * buffer)\fC [static]\fP"

.SS "static void u64toa_naive (\fBuint64_t\fP value, char * buffer)\fC [static]\fP"

.SS "template<typename \fBT\fP > static void Verify (void(*)(\fBT\fP, char *) f, char *(*)(\fBT\fP, char *) g)\fC [static]\fP"

.SS "template<typename \fBT\fP > static void VerifyValue (\fBT\fP value, void(*)(\fBT\fP, char *) f, char *(*)(\fBT\fP, char *) g)\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
