.TH "src/rapidjson/include/rapidjson/internal/itoa.h" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/internal/itoa.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./rapidjson\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinternal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBinternal::GetDigitsLut\fP ()"
.br
.ti -1c
.RI "char * \fBinternal::u32toa\fP (\fBuint32_t\fP \fBvalue\fP, char *buffer)"
.br
.ti -1c
.RI "char * \fBinternal::i32toa\fP (\fBint32_t\fP \fBvalue\fP, char *buffer)"
.br
.ti -1c
.RI "char * \fBinternal::u64toa\fP (\fBuint64_t\fP \fBvalue\fP, char *buffer)"
.br
.ti -1c
.RI "char * \fBinternal::i64toa\fP (\fBint64_t\fP \fBvalue\fP, char *buffer)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
