.TH "src/rapidjson/test/unittest/jsoncheckertest.cpp" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/jsoncheckertest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/document\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBNoOpHandler\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static char * \fBReadFile\fP (const char *filename, size_t &length)"
.br
.ti -1c
.RI "\fBTEST\fP (JsonChecker, \fBReader\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static char * ReadFile (const char * filename, size_t & length)\fC [static]\fP"

.SS "TEST (JsonChecker, \fBReader\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
