.TH "JsonReaderStackItem" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JsonReaderStackItem
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBState\fP { \fBBeforeStart\fP, \fBStarted\fP, \fBClosed\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJsonReaderStackItem\fP (const \fBValue\fP *\fBvalue\fP, \fBState\fP \fBstate\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBValue\fP * \fBvalue\fP"
.br
.ti -1c
.RI "\fBState\fP \fBstate\fP"
.br
.ti -1c
.RI "\fBSizeType\fP \fBindex\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBJsonReaderStackItem::State\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBeforeStart \fP\fP
An object/array is in the stack but it is not yet called by StartObject()/StartArray()\&. 
.TP
\fB\fIStarted \fP\fP
An object/array is called by StartObject()/StartArray()\&. 
.TP
\fB\fIClosed \fP\fP
An array is closed after read all element, but before EndArray()\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JsonReaderStackItem::JsonReaderStackItem (const \fBValue\fP * value, \fBState\fP state)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBSizeType\fP JsonReaderStackItem::index"

.SS "\fBState\fP JsonReaderStackItem::state"

.SS "const \fBValue\fP* JsonReaderStackItem::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
