.TH "Klasa" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Klasa
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
do wczytywania mapy oraz jej elementów
.PP
pobrania informacji o mapie z pliku json
.PP
tworzenia HUD dla gracza
.PP
pobrania informacji dotyczacych kafeków 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
