.TH "Layer" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Layer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Layer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLayer\fP ()"
.br
.RI "Konstruktor pusty\&. "
.ti -1c
.RI "\fBLayer\fP (\fBrapidjson::Value\fP &\fBvalue\fP)"
.br
.RI "Konstruktor który przyjmuje sparsowane wartości z json'a\&. "
.ti -1c
.RI "\fB~Layer\fP ()"
.br
.RI "Destruktor\&. "
.ti -1c
.RI "std::vector< int > \fBgetData\fP ()"
.br
.RI "Służy do zwracania informacji o miejscach wystąpienia na mapie danej warstwy\&. "
.ti -1c
.RI "int \fBgetHeight\fP ()"
.br
.RI "Zwraca wysokość warstwy\&. "
.ti -1c
.RI "int \fBgetId\fP ()"
.br
.RI "Zwraca id warstwy\&. "
.ti -1c
.RI "std::string \fBgetImage\fP ()"
.br
.RI "Zwraca sciezke do obrazka\&. "
.ti -1c
.RI "std::string \fBgetName\fP ()"
.br
.RI "Zwraca nazwe\&. "
.ti -1c
.RI "int \fBgetOpacity\fP ()"
.br
.RI "Zwraca informacje o przezroczystości\&. "
.ti -1c
.RI "std::string \fBgetType\fP ()"
.br
.RI "Zwraca informacje o typie\&. "
.ti -1c
.RI "bool \fBisVisible\fP ()"
.br
.RI "Zwraca informacje o widoczności\&. "
.ti -1c
.RI "int \fBgetWidth\fP ()"
.br
.RI "Zwraca szerokość warstwy\&. "
.ti -1c
.RI "int \fBgetX\fP ()"
.br
.RI "Zwraca współrzędną x\&. "
.ti -1c
.RI "int \fBgetY\fP ()"
.br
.RI "Zwraca współrzędną y\&. "
.ti -1c
.RI "std::vector< \fBLayerObject\fP > \fBgetObjects\fP ()"
.br
.RI "Zwraca obiekty występujące w warstwie\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Layer::Layer ()\fC [inline]\fP"

.PP
Konstruktor pusty\&. 
.SS "Layer::Layer (\fBrapidjson::Value\fP & value)"

.PP
Konstruktor który przyjmuje sparsowane wartości z json'a\&. 
.SS "Layer::~Layer ()\fC [default]\fP"

.PP
Destruktor\&. 
.SH "Member Function Documentation"
.PP 
.SS "std::vector< int > Layer::getData ()\fC [inline]\fP"

.PP
Służy do zwracania informacji o miejscach wystąpienia na mapie danej warstwy\&. 
.SS "int Layer::getHeight ()\fC [inline]\fP"

.PP
Zwraca wysokość warstwy\&. 
.SS "int Layer::getId ()\fC [inline]\fP"

.PP
Zwraca id warstwy\&. 
.SS "std::string Layer::getImage ()\fC [inline]\fP"

.PP
Zwraca sciezke do obrazka\&. 
.SS "std::string Layer::getName ()\fC [inline]\fP"

.PP
Zwraca nazwe\&. 
.SS "std::vector< \fBLayerObject\fP > Layer::getObjects ()\fC [inline]\fP"

.PP
Zwraca obiekty występujące w warstwie\&. 
.SS "int Layer::getOpacity ()\fC [inline]\fP"

.PP
Zwraca informacje o przezroczystości\&. 
.SS "std::string Layer::getType ()\fC [inline]\fP"

.PP
Zwraca informacje o typie\&. 
.SS "int Layer::getWidth ()\fC [inline]\fP"

.PP
Zwraca szerokość warstwy\&. 
.SS "int Layer::getX ()\fC [inline]\fP"

.PP
Zwraca współrzędną x\&. 
.SS "int Layer::getY ()\fC [inline]\fP"

.PP
Zwraca współrzędną y\&. 
.SS "bool Layer::isVisible ()\fC [inline]\fP"

.PP
Zwraca informacje o widoczności\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
