.TH "LevelTwoState" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LevelTwoState
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LevelTwoState\&.h>\fP
.PP
Inherits \fBGameState\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevelTwoState\fP (std::stack< \fBGameState\fP * > *\fBstates\fP)"
.br
.RI "Konstruktor przyjmujący odniesienie do stosu stanów aplikacji\&. "
.ti -1c
.RI "void \fBupdate\fP (float deltaTime) override"
.br
.RI "Odświeża logikę stanu\&. "
.ti -1c
.RI "void \fBrender\fP (sf::RenderTarget &window) override"
.br
.RI "Wyświetla elementy stanu na ekranie\&. "
.ti -1c
.RI "void \fBloadGame\fP ()"
.br
.RI "Wczytuje grę "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LevelTwoState::LevelTwoState (std::stack< \fBGameState\fP * > * states)\fC [explicit]\fP"

.PP
Konstruktor przyjmujący odniesienie do stosu stanów aplikacji\&. 
.SH "Member Function Documentation"
.PP 
.SS "void LevelTwoState::loadGame ()"

.PP
Wczytuje grę 
.SS "void LevelTwoState::render (sf::RenderTarget & window)\fC [override]\fP, \fC [virtual]\fP"

.PP
Wyświetla elementy stanu na ekranie\&. 
.PP
Reimplemented from \fBGameState\fP\&.
.SS "void LevelTwoState::update (float deltaTime)\fC [override]\fP, \fC [virtual]\fP"

.PP
Odświeża logikę stanu\&. 
.PP
Implements \fBGameState\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
