.TH "src/LoadMap.h" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/LoadMap.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Map\&.h'\fP
.br
\fC#include 'TileSet\&.h'\fP
.br
\fC#include 'TileMap\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLoadMap\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
