.TH "LoadMap" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoadMap
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LoadMap\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoadMap\fP (std::string mapFileName)"
.br
.RI "Konstruktor, który przyjmuje nazwę pliku json w którym to znajdują się elementy mapy\&. "
.ti -1c
.RI "std::ifstream \fBreadFile\fP (std::string)"
.br
.RI "Metoda która słuzy do wczytywania danych z pliku\&. "
.ti -1c
.RI "\fBTileSet\fP \fBfindTileSet\fP (\fBLayer\fP &, std::vector< \fBTileSet\fP > &)"
.br
.RI "Metoda która służy do znalezienia przekazanej w parametrze warstwy\&. "
.ti -1c
.RI "\fBLayer\fP \fBgetSolidLayer\fP ()"
.br
.RI "Metoda klasy \fBLayer\fP która zwraca warstwe hitboxow dla terenu\&. "
.ti -1c
.RI "\fBLayer\fP \fBgetDamageLayer\fP ()"
.br
.RI "Metoda klasy \fBLayer\fP która zwraca warstwe hitboxow dla obiektow ktore zadaja obrazenia\&. "
.ti -1c
.RI "void \fBdraw\fP (sf::RenderTarget &window)"
.br
.RI "Służy do wyświetlania na ekranie warstw\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LoadMap::LoadMap (std::string mapFileName)"

.PP
Konstruktor, który przyjmuje nazwę pliku json w którym to znajdują się elementy mapy\&. 
.SH "Member Function Documentation"
.PP 
.SS "void LoadMap::draw (sf::RenderTarget & window)"

.PP
Służy do wyświetlania na ekranie warstw\&. 
.SS "\fBTileSet\fP LoadMap::findTileSet (\fBLayer\fP & layer, std::vector< \fBTileSet\fP > & tilesets)"

.PP
Metoda która służy do znalezienia przekazanej w parametrze warstwy\&. 
.SS "\fBLayer\fP LoadMap::getDamageLayer ()"

.PP
Metoda klasy \fBLayer\fP która zwraca warstwe hitboxow dla obiektow ktore zadaja obrazenia\&. 
.SS "\fBLayer\fP LoadMap::getSolidLayer ()"

.PP
Metoda klasy \fBLayer\fP która zwraca warstwe hitboxow dla terenu\&. 
.SS "std::ifstream LoadMap::readFile (std::string path)"

.PP
Metoda która słuzy do wczytywania danych z pliku\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
