.TH "src/states/MainMenuState.h" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/states/MainMenuState.h
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics/Texture\&.hpp>\fP
.br
\fC#include <SFML/Graphics/Sprite\&.hpp>\fP
.br
\fC#include <SFML/Graphics/RectangleShape\&.hpp>\fP
.br
\fC#include <SFML/Window/Mouse\&.hpp>\fP
.br
\fC#include <SFML/Audio\&.hpp>\fP
.br
\fC#include <map>\fP
.br
\fC#include 'GameState\&.h'\fP
.br
\fC#include 'LevelOneState\&.h'\fP
.br
\fC#include '\&.\&./UI/Button\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainMenuState\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
