.TH "src/main.cpp" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'LoadMap\&.h'\fP
.br
\fC#include 'states/MainMenuState\&.h'\fP
.br
\fC#include 'states/LevelTwoState\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <stack>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
