.TH "Map" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Map
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Map\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMap\fP (std::string mapa)"
.br
.RI "Konstruktor który parsuje przekazana w parametrze mape\&. "
.ti -1c
.RI "\fB~Map\fP ()"
.br
.RI "Destruktor\&. "
.ti -1c
.RI "int \fBgetHeight\fP ()"
.br
.RI "Zwraca wysokość "
.ti -1c
.RI "bool \fBisInfinite\fP ()"
.br
.RI "Sprawdza czy wystepuje niesokonczoność "
.ti -1c
.RI "std::vector< \fBLayer\fP > \fBgetLayers\fP ()"
.br
.RI "Zwraca poszczególne warstwy\&. "
.ti -1c
.RI "int \fBgetNextLayerId\fP ()"
.br
.RI "Zwaraca nastepne id warstwy\&. "
.ti -1c
.RI "int \fBgetNextObjectId\fP ()"
.br
.RI "Zwraca nastepny id obiektu\&. "
.ti -1c
.RI "std::string \fBgetOrientation\fP ()"
.br
.RI "Zwraca informacje o orientacji\&. "
.ti -1c
.RI "std::string \fBgetRenderOrder\fP ()"
.br
.RI "Zwraca informacje o renderowaniu\&. "
.ti -1c
.RI "std::string \fBgetTiledVersion\fP ()"
.br
.RI "Zwraca informacje o wersji\&. "
.ti -1c
.RI "int \fBgetTileHeight\fP ()"
.br
.RI "Zwraca informacje o wysokosci kafelka\&. "
.ti -1c
.RI "std::vector< \fBTileSetMap\fP > \fBgetTileSetMap\fP ()"
.br
.RI "Zwraca kafelki mapy\&. "
.ti -1c
.RI "int \fBgetTileWidth\fP ()"
.br
.RI "Zwraca szerokosc kafelka\&. "
.ti -1c
.RI "std::string \fBgetType\fP ()"
.br
.RI "Zwraca informacje o typie\&. "
.ti -1c
.RI "float \fBgetVersion\fP ()"
.br
.RI "Zwraca informacje o uzytej wersji zapisu\&. "
.ti -1c
.RI "int \fBgetWidth\fP ()"
.br
.RI "Zwraca szerokość "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Map::Map (std::string mapa)"

.PP
Konstruktor który parsuje przekazana w parametrze mape\&. 
.SS "Map::~Map ()\fC [default]\fP"

.PP
Destruktor\&. 
.SH "Member Function Documentation"
.PP 
.SS "int Map::getHeight ()\fC [inline]\fP"

.PP
Zwraca wysokość 
.SS "std::vector< \fBLayer\fP > Map::getLayers ()\fC [inline]\fP"

.PP
Zwraca poszczególne warstwy\&. 
.SS "int Map::getNextLayerId ()\fC [inline]\fP"

.PP
Zwaraca nastepne id warstwy\&. 
.SS "int Map::getNextObjectId ()\fC [inline]\fP"

.PP
Zwraca nastepny id obiektu\&. 
.SS "std::string Map::getOrientation ()\fC [inline]\fP"

.PP
Zwraca informacje o orientacji\&. 
.SS "std::string Map::getRenderOrder ()\fC [inline]\fP"

.PP
Zwraca informacje o renderowaniu\&. 
.SS "std::string Map::getTiledVersion ()\fC [inline]\fP"

.PP
Zwraca informacje o wersji\&. 
.SS "int Map::getTileHeight ()\fC [inline]\fP"

.PP
Zwraca informacje o wysokosci kafelka\&. 
.SS "std::vector< \fBTileSetMap\fP > Map::getTileSetMap ()\fC [inline]\fP"

.PP
Zwraca kafelki mapy\&. 
.SS "int Map::getTileWidth ()\fC [inline]\fP"

.PP
Zwraca szerokosc kafelka\&. 
.SS "std::string Map::getType ()\fC [inline]\fP"

.PP
Zwraca informacje o typie\&. 
.SS "float Map::getVersion ()\fC [inline]\fP"

.PP
Zwraca informacje o uzytej wersji zapisu\&. 
.SS "int Map::getWidth ()\fC [inline]\fP"

.PP
Zwraca szerokość 
.SS "bool Map::isInfinite ()\fC [inline]\fP"

.PP
Sprawdza czy wystepuje niesokonczoność 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
