.TH "md_src_rapidjson_doc_npm" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_src_rapidjson_doc_npm \- NPM 

.SH "package\&.json"
.PP
.PP
.nf
{
  \&.\&.\&.
  "dependencies": {
    \&.\&.\&.
    "rapidjson": "git@github\&.com:Tencent/rapidjson\&.git"
  },
  \&.\&.\&.
  "gypfile": true
}
.fi
.PP
.SH "binding\&.gyp"
.PP
.PP
.nf
{
  \&.\&.\&.
  'targets': [
    {
      \&.\&.\&.
      'include_dirs': [
        '<!(node -e \'require("rapidjson")\')'
      ]
    }
  ]
}
.fi
.PP
 
