.TH "src/rapidjson/include/rapidjson/memorystream.h" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/memorystream.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stream\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMemoryStream\fP"
.br
.RI "Represents an in-memory input byte stream\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
