.TH "MemoryPoolAllocator< BaseAllocator >::ChunkHeader" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemoryPoolAllocator< BaseAllocator >::ChunkHeader \- Chunk header for perpending to each chunk\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBcapacity\fP"
.br
.RI "Capacity of the chunk in bytes (excluding the header itself)\&. "
.ti -1c
.RI "size_t \fBsize\fP"
.br
.RI "Current size of allocated memory in bytes\&. "
.ti -1c
.RI "\fBChunkHeader\fP * \fBnext\fP"
.br
.RI "Next chunk in the linked list\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename BaseAllocator = CrtAllocator>
.br
struct MemoryPoolAllocator< BaseAllocator >::ChunkHeader"Chunk header for perpending to each chunk\&. 

Chunks are stored as a singly linked list\&. 
.SH "Member Data Documentation"
.PP 
.SS "template<typename BaseAllocator  = CrtAllocator> size_t \fBMemoryPoolAllocator\fP< BaseAllocator >::ChunkHeader::capacity"

.PP
Capacity of the chunk in bytes (excluding the header itself)\&. 
.SS "template<typename BaseAllocator  = CrtAllocator> \fBChunkHeader\fP* \fBMemoryPoolAllocator\fP< BaseAllocator >::ChunkHeader::next"

.PP
Next chunk in the linked list\&. 
.SS "template<typename BaseAllocator  = CrtAllocator> size_t \fBMemoryPoolAllocator\fP< BaseAllocator >::ChunkHeader::size"

.PP
Current size of allocated memory in bytes\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
