.TH "MemoryPoolAllocator< BaseAllocator >::SharedData" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemoryPoolAllocator< BaseAllocator >::SharedData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBChunkHeader\fP * \fBchunkHead\fP"
.br
.RI "Head of the chunk linked-list\&. Only the head chunk serves allocation\&. "
.ti -1c
.RI "BaseAllocator * \fBownBaseAllocator\fP"
.br
.RI "base allocator created by this object\&. "
.ti -1c
.RI "size_t \fBrefcount\fP"
.br
.ti -1c
.RI "bool \fBownBuffer\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename BaseAllocator  = CrtAllocator> \fBChunkHeader\fP* \fBMemoryPoolAllocator\fP< BaseAllocator >::SharedData::chunkHead"

.PP
Head of the chunk linked-list\&. Only the head chunk serves allocation\&. 
.SS "template<typename BaseAllocator  = CrtAllocator> BaseAllocator* \fBMemoryPoolAllocator\fP< BaseAllocator >::SharedData::ownBaseAllocator"

.PP
base allocator created by this object\&. 
.SS "template<typename BaseAllocator  = CrtAllocator> bool \fBMemoryPoolAllocator\fP< BaseAllocator >::SharedData::ownBuffer"

.SS "template<typename BaseAllocator  = CrtAllocator> size_t \fBMemoryPoolAllocator\fP< BaseAllocator >::SharedData::refcount"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
