.TH "src/rapidjson/include/rapidjson/memorybuffer.h" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/memorybuffer.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stream\&.h'\fP
.br
\fC#include 'internal/stack\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBGenericMemoryBuffer< Allocator >\fP"
.br
.RI "Represents an in-memory output byte stream\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBGenericMemoryBuffer\fP \fBMemoryBuffer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<> void \fBPutN\fP (\fBMemoryBuffer\fP &memoryBuffer, char c, size_t n)"
.br
.RI "Implement specialized version of \fBPutN()\fP with memset() for better performance\&. "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBGenericMemoryBuffer\fP \fBMemoryBuffer\fP"

.SH "Function Documentation"
.PP 
.SS "template<> void PutN (\fBMemoryBuffer\fP & memoryBuffer, char c, size_t n)\fC [inline]\fP"

.PP
Implement specialized version of \fBPutN()\fP with memset() for better performance\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
