.TH "MessageHandler" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessageHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseReaderHandler< UTF8<>, MessageHandler >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBState\fP { \fBkExpectObjectStart\fP, \fBkExpectNameOrObjectEnd\fP, \fBkExpectValue\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessageHandler\fP ()"
.br
.ti -1c
.RI "bool \fBStartObject\fP ()"
.br
.ti -1c
.RI "bool \fBString\fP (const char *str, \fBSizeType\fP length, bool)"
.br
.ti -1c
.RI "bool \fBEndObject\fP (\fBSizeType\fP)"
.br
.ti -1c
.RI "bool \fBDefault\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMessageMap\fP \fBmessages_\fP"
.br
.ti -1c
.RI "enum \fBMessageHandler::State\fP \fBstate_\fP"
.br
.ti -1c
.RI "std::string \fBname_\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBMessageHandler::State\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIkExpectObjectStart \fP\fP
.TP
\fB\fIkExpectNameOrObjectEnd \fP\fP
.TP
\fB\fIkExpectValue \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MessageHandler::MessageHandler ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool MessageHandler::Default ()\fC [inline]\fP"

.SS "bool MessageHandler::EndObject (\fBSizeType\fP)\fC [inline]\fP"

.SS "bool MessageHandler::StartObject ()\fC [inline]\fP"

.SS "bool MessageHandler::String (const char * str, \fBSizeType\fP length, bool)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBMessageMap\fP MessageHandler::messages_"

.SS "std::string MessageHandler::name_"

.SS "enum \fBMessageHandler::State\fP MessageHandler::state_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
