.TH "src/rapidjson/example/messagereader/messagereader.cpp" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/example/messagereader/messagereader.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'rapidjson/reader\&.h'\fP
.br
\fC#include 'rapidjson/error/en\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMessageHandler\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef map< string, string > \fBMessageMap\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef map<string, string> \fBMessageMap\fP"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
