.TH "myjson" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myjson
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyAllocator\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef rapidjson::GenericDocument< rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator< \fBMyAllocator\fP >, \fBMyAllocator\fP > \fBDocument\fP"
.br
.ti -1c
.RI "typedef rapidjson::GenericPointer< \fB::myjson::Document::ValueType\fP, \fBMyAllocator\fP > \fBPointer\fP"
.br
.ti -1c
.RI "typedef \fB::myjson::Document::ValueType\fP \fBValue\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef rapidjson::GenericDocument< rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator< \fBMyAllocator\fP >, \fBMyAllocator\fP > \fBmyjson::Document\fP"

.SS "typedef rapidjson::GenericPointer< \fB::myjson::Document::ValueType\fP, \fBMyAllocator\fP > \fBmyjson::Pointer\fP"

.SS "typedef \fB::myjson::Document::ValueType\fP \fBmyjson::Value\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
