.TH "myjson::MyAllocator" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myjson::MyAllocator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void * \fBMalloc\fP (size_t _size)"
.br
.ti -1c
.RI "void * \fBRealloc\fP (void *_org_p, size_t _org_size, size_t _new_size)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBFree\fP (void *_p)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBkNeedFree\fP = true"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void myjson::MyAllocator::Free (void * _p)\fC [inline]\fP, \fC [static]\fP"

.SS "void * myjson::MyAllocator::Malloc (size_t _size)\fC [inline]\fP"

.SS "void * myjson::MyAllocator::Realloc (void * _org_p, size_t _org_size, size_t _new_size)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const bool myjson::MyAllocator::kNeedFree = true\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
