.TH "NameComparator" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NameComparator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBValue::Member\fP &lhs, const \fBValue::Member\fP &rhs) const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool NameComparator::operator() (const \fBValue::Member\fP & lhs, const \fBValue::Member\fP & rhs) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
