.TH "src/rapidjson/test/unittest/namespacetest.cpp" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/namespacetest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/document\&.h'\fP
.br
\fC#include 'rapidjson/writer\&.h'\fP
.br
\fC#include 'rapidjson/filereadstream\&.h'\fP
.br
\fC#include 'rapidjson/filewritestream\&.h'\fP
.br
\fC#include 'rapidjson/encodedstream\&.h'\fP
.br
\fC#include 'rapidjson/stringbuffer\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRAPIDJSON_NAMESPACE\fP   \fBmy::rapid::json\fP"
.br
.ti -1c
.RI "#define \fBRAPIDJSON_NAMESPACE_BEGIN\fP   namespace my { namespace rapid { namespace \fBjson\fP {"
.br
.ti -1c
.RI "#define \fBRAPIDJSON_NAMESPACE_END\fP   } } }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (NamespaceTest, Using)"
.br
.ti -1c
.RI "\fBTEST\fP (NamespaceTest, Direct)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const char \fBjson\fP [] = '{\\'hello\\':\\'world\\',\\'t\\':true,\\'f\\':false,\\'n\\':null,\\'i\\':123,\\'pi\\':3\&.1416,\\'a\\':[1,2,3,4]}'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RAPIDJSON_NAMESPACE   \fBmy::rapid::json\fP"

.SS "#define RAPIDJSON_NAMESPACE_BEGIN   namespace my { namespace rapid { namespace \fBjson\fP {"

.SS "#define RAPIDJSON_NAMESPACE_END   } } }"

.SH "Function Documentation"
.PP 
.SS "TEST (NamespaceTest, Direct)"

.SS "TEST (NamespaceTest, Using)"

.SH "Variable Documentation"
.PP 
.SS "const char json[] = '{\\'hello\\':\\'world\\',\\'t\\':true,\\'f\\':false,\\'n\\':null,\\'i\\':123,\\'pi\\':3\&.1416,\\'a\\':[1,2,3,4]}'\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
