.TH "src/rapidjson/test/unittest/namespacetest.cpp" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/namespacetest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/document\&.h'\fP
.br
\fC#include 'rapidjson/writer\&.h'\fP
.br
\fC#include 'rapidjson/filereadstream\&.h'\fP
.br
\fC#include 'rapidjson/filewritestream\&.h'\fP
.br
\fC#include 'rapidjson/encodedstream\&.h'\fP
.br
\fC#include 'rapidjson/stringbuffer\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRAPIDJSON_NAMESPACE\fP   my::rapid::json"
.br
.ti -1c
.RI "#define \fBRAPIDJSON_NAMESPACE_BEGIN\fP   namespace my { namespace rapid { namespace json {"
.br
.ti -1c
.RI "#define \fBRAPIDJSON_NAMESPACE_END\fP   } } }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (NamespaceTest, Using)"
.br
.ti -1c
.RI "\fBTEST\fP (NamespaceTest, Direct)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RAPIDJSON_NAMESPACE   my::rapid::json"

.SS "#define RAPIDJSON_NAMESPACE_BEGIN   namespace my { namespace rapid { namespace json {"

.SS "#define RAPIDJSON_NAMESPACE_END   } } }"

.SH "Function Documentation"
.PP 
.SS "TEST (NamespaceTest, Direct)"

.SS "TEST (NamespaceTest, Using)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
