.TH "NullStream" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NullStream
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef char \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNullStream\fP ()"
.br
.ti -1c
.RI "void \fBPut\fP (\fBCh\fP)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef char \fBNullStream::Ch\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "NullStream::NullStream ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void NullStream::Flush ()\fC [inline]\fP"

.SS "void NullStream::Put (\fBCh\fP)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
