.TH "NumbersAsStringsHandler" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumbersAsStringsHandler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBNull\fP ()"
.br
.ti -1c
.RI "bool \fBBool\fP (bool)"
.br
.ti -1c
.RI "bool \fBInt\fP (int)"
.br
.ti -1c
.RI "bool \fBUint\fP (unsigned)"
.br
.ti -1c
.RI "bool \fBInt64\fP (\fBint64_t\fP)"
.br
.ti -1c
.RI "bool \fBUint64\fP (\fBuint64_t\fP)"
.br
.ti -1c
.RI "bool \fBDouble\fP (double)"
.br
.ti -1c
.RI "bool \fBRawNumber\fP (const char *str, \fBSizeType\fP length, bool)"
.br
.ti -1c
.RI "bool \fBString\fP (const char *, \fBSizeType\fP, bool)"
.br
.ti -1c
.RI "bool \fBStartObject\fP ()"
.br
.ti -1c
.RI "bool \fBKey\fP (const char *, \fBSizeType\fP, bool)"
.br
.ti -1c
.RI "bool \fBEndObject\fP (\fBSizeType\fP)"
.br
.ti -1c
.RI "bool \fBStartArray\fP ()"
.br
.ti -1c
.RI "bool \fBEndArray\fP (\fBSizeType\fP)"
.br
.ti -1c
.RI "\fBNumbersAsStringsHandler\fP (const char *expected)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBexpected_\fP"
.br
.ti -1c
.RI "size_t \fBexpected_len_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NumbersAsStringsHandler::NumbersAsStringsHandler (const char * expected)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool NumbersAsStringsHandler::Bool (bool)\fC [inline]\fP"

.SS "bool NumbersAsStringsHandler::Double (double)\fC [inline]\fP"

.SS "bool NumbersAsStringsHandler::EndArray (\fBSizeType\fP)\fC [inline]\fP"

.SS "bool NumbersAsStringsHandler::EndObject (\fBSizeType\fP)\fC [inline]\fP"

.SS "bool NumbersAsStringsHandler::Int (int)\fC [inline]\fP"

.SS "bool NumbersAsStringsHandler::Int64 (\fBint64_t\fP)\fC [inline]\fP"

.SS "bool NumbersAsStringsHandler::Key (const char *, \fBSizeType\fP, bool)\fC [inline]\fP"

.SS "bool NumbersAsStringsHandler::Null ()\fC [inline]\fP"

.SS "bool NumbersAsStringsHandler::RawNumber (const char * str, \fBSizeType\fP length, bool)\fC [inline]\fP"

.SS "bool NumbersAsStringsHandler::StartArray ()\fC [inline]\fP"

.SS "bool NumbersAsStringsHandler::StartObject ()\fC [inline]\fP"

.SS "bool NumbersAsStringsHandler::String (const char *, \fBSizeType\fP, bool)\fC [inline]\fP"

.SS "bool NumbersAsStringsHandler::Uint (unsigned)\fC [inline]\fP"

.SS "bool NumbersAsStringsHandler::Uint64 (\fBuint64_t\fP)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const char* NumbersAsStringsHandler::expected_"

.SS "size_t NumbersAsStringsHandler::expected_len_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
