.TH "Opisuje" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Opisuje
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
, którą można spotkać w grze
.PP
jakiego korzsta gracz
.PP
może służyć jako pocisk 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
