.TH "OStreamWrapper" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OStreamWrapper
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef char \fBCh\fP"
.br
.ti -1c
.RI "typedef char \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOStreamWrapper\fP (std::ostream &os)"
.br
.ti -1c
.RI "\fBCh\fP \fBPeek\fP () const"
.br
.ti -1c
.RI "\fBCh\fP \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP () const"
.br
.ti -1c
.RI "\fBCh\fP * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "void \fBPut\fP (\fBCh\fP c)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (\fBCh\fP *)"
.br
.ti -1c
.RI "\fBOStreamWrapper\fP (std::ostream &os)"
.br
.ti -1c
.RI "\fBCh\fP \fBPeek\fP () const"
.br
.ti -1c
.RI "\fBCh\fP \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP () const"
.br
.ti -1c
.RI "\fBCh\fP * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "void \fBPut\fP (\fBCh\fP c)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (\fBCh\fP *)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBOStreamWrapper\fP (const \fBOStreamWrapper\fP &)"
.br
.ti -1c
.RI "\fBOStreamWrapper\fP & \fBoperator=\fP (const \fBOStreamWrapper\fP &)"
.br
.ti -1c
.RI "\fBOStreamWrapper\fP (const \fBOStreamWrapper\fP &)"
.br
.ti -1c
.RI "\fBOStreamWrapper\fP & \fBoperator=\fP (const \fBOStreamWrapper\fP &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::ostream & \fBos_\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef char \fBOStreamWrapper::Ch\fP"

.SS "typedef char \fBOStreamWrapper::Ch\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "OStreamWrapper::OStreamWrapper (std::ostream & os)\fC [inline]\fP"

.SS "OStreamWrapper::OStreamWrapper (const \fBOStreamWrapper\fP &)\fC [private]\fP"

.SS "OStreamWrapper::OStreamWrapper (std::ostream & os)\fC [inline]\fP"

.SS "OStreamWrapper::OStreamWrapper (const \fBOStreamWrapper\fP &)\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void OStreamWrapper::Flush ()\fC [inline]\fP"

.SS "void OStreamWrapper::Flush ()\fC [inline]\fP"

.SS "\fBOStreamWrapper\fP & OStreamWrapper::operator= (const \fBOStreamWrapper\fP &)\fC [private]\fP"

.SS "\fBOStreamWrapper\fP & OStreamWrapper::operator= (const \fBOStreamWrapper\fP &)\fC [private]\fP"

.SS "\fBCh\fP OStreamWrapper::Peek () const\fC [inline]\fP"

.SS "\fBCh\fP OStreamWrapper::Peek () const\fC [inline]\fP"

.SS "void OStreamWrapper::Put (\fBCh\fP c)\fC [inline]\fP"

.SS "void OStreamWrapper::Put (\fBCh\fP c)\fC [inline]\fP"

.SS "\fBCh\fP * OStreamWrapper::PutBegin ()\fC [inline]\fP"

.SS "\fBCh\fP * OStreamWrapper::PutBegin ()\fC [inline]\fP"

.SS "size_t OStreamWrapper::PutEnd (\fBCh\fP *)\fC [inline]\fP"

.SS "size_t OStreamWrapper::PutEnd (\fBCh\fP *)\fC [inline]\fP"

.SS "\fBCh\fP OStreamWrapper::Take ()\fC [inline]\fP"

.SS "\fBCh\fP OStreamWrapper::Take ()\fC [inline]\fP"

.SS "size_t OStreamWrapper::Tell () const\fC [inline]\fP"

.SS "size_t OStreamWrapper::Tell () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::ostream & OStreamWrapper::os_\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
