.TH "src/rapidjson/test/unittest/ostreamwrappertest.cpp" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/ostreamwrappertest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/ostreamwrapper\&.h'\fP
.br
\fC#include 'rapidjson/encodedstream\&.h'\fP
.br
\fC#include 'rapidjson/document\&.h'\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <fstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBOStreamWrapper\fP, ostringstream)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBOStreamWrapper\fP, stringstream)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBOStreamWrapper\fP, wostringstream)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBOStreamWrapper\fP, wstringstream)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBOStreamWrapper\fP, cout)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBOStreamWrapper\fP, ofstream)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBOStreamWrapper\fP, fstream)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (\fBOStreamWrapper\fP, cout)"

.SS "TEST (\fBOStreamWrapper\fP, fstream)"

.SS "TEST (\fBOStreamWrapper\fP, ofstream)"

.SS "TEST (\fBOStreamWrapper\fP, ostringstream)"

.SS "TEST (\fBOStreamWrapper\fP, stringstream)"

.SS "TEST (\fBOStreamWrapper\fP, wostringstream)"

.SS "TEST (\fBOStreamWrapper\fP, wstringstream)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
