.TH "src/rapidjson/include/rapidjson/ostreamwrapper.h" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/ostreamwrapper.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stream\&.h'\fP
.br
\fC#include <iosfwd>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBasicOStreamWrapper< StreamType >\fP"
.br
.RI "Wrapper of \fCstd::basic_ostream\fP into RapidJSON's Stream concept\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBBasicOStreamWrapper\fP< std::ostream > \fBOStreamWrapper\fP"
.br
.ti -1c
.RI "typedef \fBBasicOStreamWrapper\fP< std::wostream > \fBWOStreamWrapper\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBBasicOStreamWrapper\fP<std::ostream> \fBOStreamWrapper\fP"

.SS "typedef \fBBasicOStreamWrapper\fP<std::wostream> \fBWOStreamWrapper\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
