.TH "ParseUint64Handler" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseUint64Handler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseReaderHandler< UTF8<>, ParseUint64Handler >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseUint64Handler\fP ()"
.br
.ti -1c
.RI "bool \fBDefault\fP ()"
.br
.ti -1c
.RI "bool \fBUint64\fP (\fBuint64_t\fP i)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBstep_\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBactual_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParseUint64Handler::ParseUint64Handler ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ParseUint64Handler::Default ()\fC [inline]\fP"

.SS "bool ParseUint64Handler::Uint64 (\fBuint64_t\fP i)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBuint64_t\fP ParseUint64Handler::actual_"

.SS "unsigned ParseUint64Handler::step_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
