.TH "ParseDoubleHandler" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseDoubleHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseReaderHandler< UTF8<>, ParseDoubleHandler >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseDoubleHandler\fP ()"
.br
.ti -1c
.RI "bool \fBDefault\fP ()"
.br
.ti -1c
.RI "bool \fBDouble\fP (double d)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBstep_\fP"
.br
.ti -1c
.RI "double \fBactual_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParseDoubleHandler::ParseDoubleHandler ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ParseDoubleHandler::Default ()\fC [inline]\fP"

.SS "bool ParseDoubleHandler::Double (double d)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double ParseDoubleHandler::actual_"

.SS "unsigned ParseDoubleHandler::step_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
