.TH "ParseEmptyObjectHandler" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseEmptyObjectHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseReaderHandler< UTF8<>, ParseEmptyObjectHandler >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseEmptyObjectHandler\fP ()"
.br
.ti -1c
.RI "bool \fBDefault\fP ()"
.br
.ti -1c
.RI "bool \fBStartObject\fP ()"
.br
.ti -1c
.RI "bool \fBEndObject\fP (\fBSizeType\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBstep_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParseEmptyObjectHandler::ParseEmptyObjectHandler ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ParseEmptyObjectHandler::Default ()\fC [inline]\fP"

.SS "bool ParseEmptyObjectHandler::EndObject (\fBSizeType\fP)\fC [inline]\fP"

.SS "bool ParseEmptyObjectHandler::StartObject ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned ParseEmptyObjectHandler::step_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
