.TH "ParseBoolHandler< expect >" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseBoolHandler< expect >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseReaderHandler< UTF8<>, ParseBoolHandler< expect > >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseBoolHandler\fP ()"
.br
.ti -1c
.RI "bool \fBDefault\fP ()"
.br
.ti -1c
.RI "bool \fBBool\fP (bool b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBstep_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<bool expect> \fBParseBoolHandler\fP< expect >\fB::ParseBoolHandler\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<bool expect> bool \fBParseBoolHandler\fP< expect >::Bool (bool b)\fC [inline]\fP"

.SS "template<bool expect> bool \fBParseBoolHandler\fP< expect >::Default ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<bool expect> unsigned \fBParseBoolHandler\fP< expect >::step_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
