.TH "ParseMultipleRootHandler" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseMultipleRootHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseReaderHandler< UTF8<>, ParseMultipleRootHandler >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseMultipleRootHandler\fP ()"
.br
.ti -1c
.RI "bool \fBDefault\fP ()"
.br
.ti -1c
.RI "bool \fBStartObject\fP ()"
.br
.ti -1c
.RI "bool \fBEndObject\fP (\fBSizeType\fP)"
.br
.ti -1c
.RI "bool \fBStartArray\fP ()"
.br
.ti -1c
.RI "bool \fBEndArray\fP (\fBSizeType\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBstep_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParseMultipleRootHandler::ParseMultipleRootHandler ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ParseMultipleRootHandler::Default ()\fC [inline]\fP"

.SS "bool ParseMultipleRootHandler::EndArray (\fBSizeType\fP)\fC [inline]\fP"

.SS "bool ParseMultipleRootHandler::EndObject (\fBSizeType\fP)\fC [inline]\fP"

.SS "bool ParseMultipleRootHandler::StartArray ()\fC [inline]\fP"

.SS "bool ParseMultipleRootHandler::StartObject ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned ParseMultipleRootHandler::step_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
