.TH "ParseObjectHandler" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseObjectHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseReaderHandler< UTF8<>, ParseObjectHandler >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseObjectHandler\fP ()"
.br
.ti -1c
.RI "bool \fBDefault\fP ()"
.br
.ti -1c
.RI "bool \fBNull\fP ()"
.br
.ti -1c
.RI "bool \fBBool\fP (bool b)"
.br
.ti -1c
.RI "bool \fBInt\fP (int i)"
.br
.ti -1c
.RI "bool \fBUint\fP (unsigned i)"
.br
.ti -1c
.RI "bool \fBDouble\fP (double d)"
.br
.ti -1c
.RI "bool \fBString\fP (const char *str, size_t, bool)"
.br
.ti -1c
.RI "bool \fBStartObject\fP ()"
.br
.ti -1c
.RI "bool \fBEndObject\fP (\fBSizeType\fP memberCount)"
.br
.ti -1c
.RI "bool \fBStartArray\fP ()"
.br
.ti -1c
.RI "bool \fBEndArray\fP (\fBSizeType\fP elementCount)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBstep_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParseObjectHandler::ParseObjectHandler ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ParseObjectHandler::Bool (bool b)\fC [inline]\fP"

.SS "bool ParseObjectHandler::Default ()\fC [inline]\fP"

.SS "bool ParseObjectHandler::Double (double d)\fC [inline]\fP"

.SS "bool ParseObjectHandler::EndArray (\fBSizeType\fP elementCount)\fC [inline]\fP"

.SS "bool ParseObjectHandler::EndObject (\fBSizeType\fP memberCount)\fC [inline]\fP"

.SS "bool ParseObjectHandler::Int (int i)\fC [inline]\fP"

.SS "bool ParseObjectHandler::Null ()\fC [inline]\fP"

.SS "bool ParseObjectHandler::StartArray ()\fC [inline]\fP"

.SS "bool ParseObjectHandler::StartObject ()\fC [inline]\fP"

.SS "bool ParseObjectHandler::String (const char * str, size_t, bool)\fC [inline]\fP"

.SS "bool ParseObjectHandler::Uint (unsigned i)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned ParseObjectHandler::step_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
