.TH "ParseIntHandler" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseIntHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseReaderHandler< UTF8<>, ParseIntHandler >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseIntHandler\fP ()"
.br
.ti -1c
.RI "bool \fBDefault\fP ()"
.br
.ti -1c
.RI "bool \fBInt\fP (int i)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBstep_\fP"
.br
.ti -1c
.RI "int \fBactual_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParseIntHandler::ParseIntHandler ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ParseIntHandler::Default ()\fC [inline]\fP"

.SS "bool ParseIntHandler::Int (int i)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int ParseIntHandler::actual_"

.SS "unsigned ParseIntHandler::step_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
