.TH "ParseUintHandler" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseUintHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseReaderHandler< UTF8<>, ParseUintHandler >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseUintHandler\fP ()"
.br
.ti -1c
.RI "bool \fBDefault\fP ()"
.br
.ti -1c
.RI "bool \fBUint\fP (unsigned i)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBstep_\fP"
.br
.ti -1c
.RI "unsigned \fBactual_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParseUintHandler::ParseUintHandler ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ParseUintHandler::Default ()\fC [inline]\fP"

.SS "bool ParseUintHandler::Uint (unsigned i)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned ParseUintHandler::actual_"

.SS "unsigned ParseUintHandler::step_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
