.TH "ParseStringHandler< Encoding >" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseStringHandler< Encoding >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseReaderHandler< Encoding, ParseStringHandler< Encoding > >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseStringHandler\fP ()"
.br
.ti -1c
.RI "\fB~ParseStringHandler\fP ()"
.br
.ti -1c
.RI "\fBParseStringHandler\fP (const \fBParseStringHandler\fP &)"
.br
.ti -1c
.RI "\fBParseStringHandler\fP & \fBoperator=\fP (const \fBParseStringHandler\fP &)"
.br
.ti -1c
.RI "bool \fBDefault\fP ()"
.br
.ti -1c
.RI "bool \fBString\fP (const typename Encoding::Ch *str, size_t length, bool copy)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const Encoding::Ch * \fBstr_\fP"
.br
.ti -1c
.RI "size_t \fBlength_\fP"
.br
.ti -1c
.RI "bool \fBcopy_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename \fBEncoding\fP > \fBParseStringHandler\fP< \fBEncoding\fP >\fB::ParseStringHandler\fP ()\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > \fBParseStringHandler\fP< \fBEncoding\fP >::~\fBParseStringHandler\fP ()\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > \fBParseStringHandler\fP< \fBEncoding\fP >\fB::ParseStringHandler\fP (const \fBParseStringHandler\fP< \fBEncoding\fP > &)"

.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBEncoding\fP > bool \fBParseStringHandler\fP< \fBEncoding\fP >::Default ()\fC [inline]\fP"

.SS "template<typename \fBEncoding\fP > \fBParseStringHandler\fP & \fBParseStringHandler\fP< \fBEncoding\fP >::operator= (const \fBParseStringHandler\fP< \fBEncoding\fP > &)"

.SS "template<typename \fBEncoding\fP > bool \fBParseStringHandler\fP< \fBEncoding\fP >::String (const typename Encoding::Ch * str, size_t length, bool copy)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename \fBEncoding\fP > bool \fBParseStringHandler\fP< \fBEncoding\fP >::copy_"

.SS "template<typename \fBEncoding\fP > size_t \fBParseStringHandler\fP< \fBEncoding\fP >::length_"

.SS "template<typename \fBEncoding\fP > const Encoding::Ch* \fBParseStringHandler\fP< \fBEncoding\fP >::str_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
