.TH "ParseArrayHandler< count >" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseArrayHandler< count >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseReaderHandler< UTF8<>, ParseArrayHandler< count > >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseArrayHandler\fP ()"
.br
.ti -1c
.RI "bool \fBDefault\fP ()"
.br
.ti -1c
.RI "bool \fBUint\fP (unsigned i)"
.br
.ti -1c
.RI "bool \fBStartArray\fP ()"
.br
.ti -1c
.RI "bool \fBEndArray\fP (\fBSizeType\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBstep_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<unsigned count> \fBParseArrayHandler\fP< count >\fB::ParseArrayHandler\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<unsigned count> bool \fBParseArrayHandler\fP< count >::Default ()\fC [inline]\fP"

.SS "template<unsigned count> bool \fBParseArrayHandler\fP< count >::EndArray (\fBSizeType\fP)\fC [inline]\fP"

.SS "template<unsigned count> bool \fBParseArrayHandler\fP< count >::StartArray ()\fC [inline]\fP"

.SS "template<unsigned count> bool \fBParseArrayHandler\fP< count >::Uint (unsigned i)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<unsigned count> unsigned \fBParseArrayHandler\fP< count >::step_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
