.TH "src/rapidjson/test/perftest/perftest.h" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/perftest/perftest.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTEST_RAPIDJSON\fP   1"
.br
.ti -1c
.RI "#define \fBTEST_PLATFORM\fP   0"
.br
.ti -1c
.RI "#define \fBTEST_MISC\fP   0"
.br
.ti -1c
.RI "#define \fBTEST_VERSION_CODE\fP(x,  y,  z)     (((x)*100000) + ((y)*100) + (z))"
.br
.ti -1c
.RI "#define \fBRAPIDJSON_HAS_STDSTRING\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RAPIDJSON_HAS_STDSTRING   1"

.SS "#define TEST_MISC   0"

.SS "#define TEST_PLATFORM   0"

.SS "#define TEST_RAPIDJSON   1"

.SS "#define TEST_VERSION_CODE(x, y, z)     (((x)*100000) + ((y)*100) + (z))"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
