.TH "Person" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Person
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDependent\fP, and \fBEmployee\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPerson\fP (const std::string &name, unsigned age)"
.br
.ti -1c
.RI "\fBPerson\fP (const \fBPerson\fP &rhs)"
.br
.ti -1c
.RI "virtual \fB~Person\fP ()"
.br
.ti -1c
.RI "\fBPerson\fP & \fBoperator=\fP (const \fBPerson\fP &rhs)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "template<typename \fBWriter\fP > void \fBSerialize\fP (\fBWriter\fP &writer) const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Person::Person (const std::string & name, unsigned age)\fC [inline]\fP"

.SS "Person::Person (const \fBPerson\fP & rhs)\fC [inline]\fP"

.SS "Person::~Person ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBPerson\fP & Person::operator= (const \fBPerson\fP & rhs)\fC [inline]\fP"

.SS "template<typename \fBWriter\fP > void Person::Serialize (\fBWriter\fP & writer) const\fC [inline]\fP, \fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
