.TH "PlayerHUD" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerHUD
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PlayerHUD\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayerHUD\fP ()"
.br
.RI "Konstruktor dla HUD\&. "
.ti -1c
.RI "void \fBrender\fP (sf::RenderTarget &window)"
.br
.RI "Wyświetla tekstury HUD na ekranie\&. "
.ti -1c
.RI "void \fBupdate\fP (\fBDamageable\fP *damageableModule, bool playerReady)"
.br
.RI "Odświeża stan naszych tekstur HUD\&. "
.ti -1c
.RI "void \fBsetPosition\fP (float x, float y)"
.br
.RI "Pozwala ustawić pozycje dla tekstur HUD\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBtakedDmg\fP"
.br
.RI "Zmienna pozwalająca sprawdzić czy otrzymaliśmy jakieś obrażenia\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PlayerHUD::PlayerHUD ()"

.PP
Konstruktor dla HUD\&. 
.SH "Member Function Documentation"
.PP 
.SS "void PlayerHUD::render (sf::RenderTarget & window)"

.PP
Wyświetla tekstury HUD na ekranie\&. 
.SS "void PlayerHUD::setPosition (float x, float y)"

.PP
Pozwala ustawić pozycje dla tekstur HUD\&. 
.SS "void PlayerHUD::update (\fBDamageable\fP * damageableModule, bool playerReady)"

.PP
Odświeża stan naszych tekstur HUD\&. 
.SH "Member Data Documentation"
.PP 
.SS "bool PlayerHUD::takedDmg"

.PP
Zmienna pozwalająca sprawdzić czy otrzymaliśmy jakieś obrażenia\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
