.TH "Player" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Player\&.h>\fP
.PP
Inherits \fBDamageable\fP, and \fBAnimated\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayer\fP (float x=0, float y=0)"
.br
.RI "Konstruktor gracza z opcją podania lokalizacji początkowej na mapie\&. "
.ti -1c
.RI "void \fBmove\fP (float x, float y)"
.br
.RI "Służy do poruszania graczem\&. Podanie wartości 1 jako argument porusza graczem w domyślny sposób\&. "
.ti -1c
.RI "sf::Vector2f \fBgetPosition\fP ()"
.br
.RI "Zwraca pozycję gracza\&. "
.ti -1c
.RI "void \fBzeroVelocity\fP (bool x, bool y)"
.br
.RI "Zeruje x - poziomą, y - pionową prędkość gracza\&. "
.ti -1c
.RI "bool \fBcheckForIntersection\fP (sf::RectangleShape &shape)"
.br
.RI "Sprawdza, czy hitbox gracza nachodzi na hitbox podany w parametrze\&. "
.ti -1c
.RI "bool \fBgetTimeStopped\fP () const"
.br
.RI "Pozwala sprawdzić czy czas jest zatrzymany\&. "
.ti -1c
.RI "float \fBgetTimeStopValue\fP () const"
.br
.RI "Zwraca wartość 0-1 reprezentującą stopień naładowania umiejętności zatrzymania czasu\&. "
.ti -1c
.RI "void \fBupdate\fP (float deltaTime, const std::list< sf::RectangleShape > &allHitboxes)"
.br
.RI "Odświeża logikę gracza odpowiedzialną za ruch, czytanie klawiatury itd\&. "
.ti -1c
.RI "void \fBrender\fP (sf::RenderTarget &window)"
.br
.RI "Wyświetla postać gracza na ekranie\&. "
.ti -1c
.RI "void \fBsetPosition\fP (sf::Vector2f)"
.br
.RI "Ustawia pozycję postaci gracza a mapie\&. "
.ti -1c
.RI "void \fBswitchAnimation\fP (\fBAnimation\fP newAnimation)"
.br
.RI "Zmienia stan animacji gracza na podany\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisReady\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Player::Player (float x = \fC0\fP, float y = \fC0\fP)\fC [explicit]\fP"

.PP
Konstruktor gracza z opcją podania lokalizacji początkowej na mapie\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool Player::checkForIntersection (sf::RectangleShape & shape)"

.PP
Sprawdza, czy hitbox gracza nachodzi na hitbox podany w parametrze\&. 
.SS "sf::Vector2f Player::getPosition ()"

.PP
Zwraca pozycję gracza\&. 
.SS "bool Player::getTimeStopped () const\fC [inline]\fP"

.PP
Pozwala sprawdzić czy czas jest zatrzymany\&. 
.SS "float Player::getTimeStopValue () const\fC [inline]\fP"

.PP
Zwraca wartość 0-1 reprezentującą stopień naładowania umiejętności zatrzymania czasu\&. 
.SS "void Player::move (float x, float y)"

.PP
Służy do poruszania graczem\&. Podanie wartości 1 jako argument porusza graczem w domyślny sposób\&. 
.SS "void Player::render (sf::RenderTarget & window)"

.PP
Wyświetla postać gracza na ekranie\&. 
.SS "void Player::setPosition (sf::Vector2f newPos)"

.PP
Ustawia pozycję postaci gracza a mapie\&. 
.SS "void Player::switchAnimation (\fBAnimation\fP newAnimation)"

.PP
Zmienia stan animacji gracza na podany\&. 
.SS "void Player::update (float deltaTime, const std::list< sf::RectangleShape > & allHitboxes)"

.PP
Odświeża logikę gracza odpowiedzialną za ruch, czytanie klawiatury itd\&. 
.SS "void Player::zeroVelocity (bool x, bool y)"

.PP
Zeruje x - poziomą, y - pionową prędkość gracza\&. 
.SH "Member Data Documentation"
.PP 
.SS "bool Player::isReady"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
