.TH "src/entities/Player.h" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/entities/Player.h
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <SFML/Window/Keyboard\&.hpp>\fP
.br
\fC#include <list>\fP
.br
\fC#include <SFML/Audio\&.hpp>\fP
.br
\fC#include '\&.\&./modules/Damageable\&.h'\fP
.br
\fC#include '\&.\&./modules/Animated\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlayer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
