.TH "src/modules/PlayerHUD.h" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/PlayerHUD.h
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics/RenderTarget\&.hpp>\fP
.br
\fC#include <SFML/Graphics/RectangleShape\&.hpp>\fP
.br
\fC#include <SFML/Graphics/Texture\&.hpp>\fP
.br
\fC#include 'Damageable\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlayerHUD\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
