.TH "src/rapidjson/include/rapidjson/prettywriter.h" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/prettywriter.h
.SH SYNOPSIS
.br
.PP
\fC#include 'writer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >\fP"
.br
.RI "\fBWriter\fP with indentation and spacing\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPrettyFormatOptions\fP { \fBkFormatDefault\fP = 0, \fBkFormatSingleLineArray\fP = 1 }"
.br
.RI "Combination of \fBPrettyWriter\fP format flags\&. "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBPrettyFormatOptions\fP"

.PP
Combination of \fBPrettyWriter\fP format flags\&. 
.PP
\fBSee also\fP
.RS 4
\fBPrettyWriter::SetFormatOptions\fP 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIkFormatDefault \fP\fP
Default pretty formatting\&. 
.TP
\fB\fIkFormatSingleLineArray \fP\fP
Format arrays on a single line\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
