.TH "Random" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Random
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <unittest\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandom\fP (unsigned seed=0)"
.br
.ti -1c
.RI "unsigned \fBoperator()\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBmSeed\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Random::Random (unsigned seed = \fC0\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "unsigned Random::operator() ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned Random::mSeed\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
