.TH "src/rapidjson/include/rapidjson/internal/regex.h" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/internal/regex.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./allocators\&.h'\fP
.br
\fC#include '\&.\&./stream\&.h'\fP
.br
\fC#include 'stack\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBinternal::DecodedStream< SourceStream, Encoding >\fP"
.br
.ti -1c
.RI "class \fBinternal::GenericRegex< Encoding, Allocator >\fP"
.br
.RI "Regular expression engine with subset of ECMAscript grammar\&. "
.ti -1c
.RI "struct \fBinternal::GenericRegex< Encoding, Allocator >::Range\fP"
.br
.ti -1c
.RI "struct \fBinternal::GenericRegex< Encoding, Allocator >::State\fP"
.br
.ti -1c
.RI "struct \fBinternal::GenericRegex< Encoding, Allocator >::Frag\fP"
.br
.ti -1c
.RI "class \fBinternal::GenericRegexSearch< RegexType, Allocator >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinternal\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRAPIDJSON_REGEX_VERBOSE\fP   0"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef GenericRegex< \fBUTF8\fP<> > \fBinternal::Regex\fP"
.br
.ti -1c
.RI "typedef GenericRegexSearch< Regex > \fBinternal::RegexSearch\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const \fBSizeType\fP \fBinternal::kRegexInvalidState\fP = ~\fBSizeType\fP(0)"
.br
.RI "Represents an invalid index in \fBGenericRegex::State::out\fP, out1\&. "
.ti -1c
.RI "static const \fBSizeType\fP \fBinternal::kRegexInvalidRange\fP = ~\fBSizeType\fP(0)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RAPIDJSON_REGEX_VERBOSE   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
