.TH "RemoteSchemaDocumentProvider< SchemaDocumentType >" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RemoteSchemaDocumentProvider< SchemaDocumentType >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIGenericRemoteSchemaDocumentProvider< SchemaDocument >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRemoteSchemaDocumentProvider\fP ()"
.br
.ti -1c
.RI "\fB~RemoteSchemaDocumentProvider\fP ()"
.br
.ti -1c
.RI "virtual const SchemaDocumentType * \fBGetRemoteDocument\fP (const char *uri, \fBSizeType\fP length)"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "typedef \fBGenericDocument\fP< typename SchemaDocumentType::EncodingType, \fBMemoryPoolAllocator\fP<>, \fBMemoryPoolAllocator\fP<> > \fBDocumentType\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBRemoteSchemaDocumentProvider\fP (const \fBRemoteSchemaDocumentProvider\fP &)"
.br
.ti -1c
.RI "\fBRemoteSchemaDocumentProvider\fP & \fBoperator=\fP (const \fBRemoteSchemaDocumentProvider\fP &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "SchemaDocumentType * \fBsd_\fP [\fBkCount\fP]"
.br
.ti -1c
.RI "\fBDocumentType::AllocatorType\fP \fBdocumentAllocator_\fP"
.br
.ti -1c
.RI "SchemaDocumentType::AllocatorType \fBschemaAllocator_\fP"
.br
.ti -1c
.RI "char \fBdocumentBuffer_\fP [16384]"
.br
.ti -1c
.RI "char \fBschemaBuffer_\fP [128u *1024]"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static const size_t \fBkCount\fP = 5"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename SchemaDocumentType  = SchemaDocument> typedef \fBGenericDocument\fP<typename SchemaDocumentType::EncodingType, \fBMemoryPoolAllocator\fP<>, \fBMemoryPoolAllocator\fP<> > \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::DocumentType\fC [private]\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename SchemaDocumentType  = SchemaDocument> \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType >\fB::RemoteSchemaDocumentProvider\fP ()\fC [inline]\fP"

.SS "template<typename SchemaDocumentType  = SchemaDocument> \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::~\fBRemoteSchemaDocumentProvider\fP ()\fC [inline]\fP"

.SS "template<typename SchemaDocumentType  = SchemaDocument> \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType >\fB::RemoteSchemaDocumentProvider\fP (const \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType > &)\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename SchemaDocumentType  = SchemaDocument> virtual const SchemaDocumentType * \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::GetRemoteDocument (const char * uri, \fBSizeType\fP length)\fC [inline]\fP, \fC [virtual]\fP"

.SS "template<typename SchemaDocumentType  = SchemaDocument> \fBRemoteSchemaDocumentProvider\fP & \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::operator= (const \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType > &)\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename SchemaDocumentType  = SchemaDocument> \fBDocumentType::AllocatorType\fP \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::documentAllocator_\fC [private]\fP"

.SS "template<typename SchemaDocumentType  = SchemaDocument> char \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::documentBuffer_[16384]\fC [private]\fP"

.SS "template<typename SchemaDocumentType  = SchemaDocument> const size_t \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::kCount = 5\fC [static]\fP, \fC [private]\fP"

.SS "template<typename SchemaDocumentType  = SchemaDocument> SchemaDocumentType::AllocatorType \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::schemaAllocator_\fC [private]\fP"

.SS "template<typename SchemaDocumentType  = SchemaDocument> char \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::schemaBuffer_[128u *1024]\fC [private]\fP"

.SS "template<typename SchemaDocumentType  = SchemaDocument> SchemaDocumentType* \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::sd_[\fBkCount\fP]\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
