.TH "RemoteSchemaDocumentProvider< SchemaDocumentType >" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RemoteSchemaDocumentProvider< SchemaDocumentType >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIGenericRemoteSchemaDocumentProvider< SchemaDocument >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRemoteSchemaDocumentProvider\fP ()"
.br
.ti -1c
.RI "\fB~RemoteSchemaDocumentProvider\fP ()"
.br
.ti -1c
.RI "virtual const SchemaDocumentType * \fBGetRemoteDocument\fP (const char *uri, \fBSizeType\fP length)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename SchemaDocumentType  = SchemaDocument> \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType >\fB::RemoteSchemaDocumentProvider\fP ()\fC [inline]\fP"

.SS "template<typename SchemaDocumentType  = SchemaDocument> \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::~\fBRemoteSchemaDocumentProvider\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename SchemaDocumentType  = SchemaDocument> virtual const SchemaDocumentType * \fBRemoteSchemaDocumentProvider\fP< SchemaDocumentType >::GetRemoteDocument (const char * uri, \fBSizeType\fP length)\fC [inline]\fP, \fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
