.TH "ScanCopyUnescapedStringHandler" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScanCopyUnescapedStringHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseReaderHandler< UTF8<>, ScanCopyUnescapedStringHandler >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBString\fP (const char *str, size_t length, bool)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBbuffer\fP [1024+5+32]"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "bool ScanCopyUnescapedStringHandler::String (const char * str, size_t length, bool)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "char ScanCopyUnescapedStringHandler::buffer[1024+5+32]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
