.TH "Schema::TestSuite" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Schema::TestSuite
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestSuite\fP ()"
.br
.ti -1c
.RI "\fB~TestSuite\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSchemaDocument\fP * \fBschema\fP"
.br
.ti -1c
.RI "\fBDocumentList\fP \fBtests\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Schema::TestSuite::TestSuite ()\fC [inline]\fP"

.SS "Schema::TestSuite::~TestSuite ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBSchemaDocument\fP* Schema::TestSuite::schema"

.SS "\fBDocumentList\fP Schema::TestSuite::tests"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
