.TH "Schema" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Schema
.SH SYNOPSIS
.br
.PP
.PP
Inherits PerfTest\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTestSuite\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSchema\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetUp\fP ()"
.br
.ti -1c
.RI "virtual void \fBTearDown\fP ()"
.br
.in -1c
.SS "Protected Types"

.in +1c
.ti -1c
.RI "typedef std::vector< \fBDocument\fP * > \fBDocumentList\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBTestSuite\fP * > \fBTestSuiteList\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBTestSuiteList\fP \fBtestSuites\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBSchema\fP (const \fBSchema\fP &)"
.br
.ti -1c
.RI "\fBSchema\fP & \fBoperator=\fP (const \fBSchema\fP &)"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIsExcludeTestSuite\fP (const std::string &description)"
.br
.ti -1c
.RI "static bool \fBIsExcludeTest\fP (const std::string &description)"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef std::vector<\fBDocument\fP*> \fBSchema::DocumentList\fP\fC [protected]\fP"

.SS "typedef std::vector<\fBTestSuite\fP* > \fBSchema::TestSuiteList\fP\fC [protected]\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Schema::Schema ()\fC [inline]\fP"

.SS "Schema::Schema (const \fBSchema\fP &)\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static bool Schema::IsExcludeTest (const std::string & description)\fC [inline]\fP, \fC [static]\fP, \fC [private]\fP"

.SS "static bool Schema::IsExcludeTestSuite (const std::string & description)\fC [inline]\fP, \fC [static]\fP, \fC [private]\fP"

.SS "\fBSchema\fP & Schema::operator= (const \fBSchema\fP &)\fC [private]\fP"

.SS "virtual void Schema::SetUp ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual void Schema::TearDown ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBTestSuiteList\fP Schema::testSuites\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
