.TH "src/rapidjson/example/serialize/serialize.cpp" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/example/serialize/serialize.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'rapidjson/prettywriter\&.h'\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPerson\fP"
.br
.ti -1c
.RI "class \fBEducation\fP"
.br
.ti -1c
.RI "class \fBDependent\fP"
.br
.ti -1c
.RI "class \fBEmployee\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int, char *[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int, char *[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
