.TH "Shape" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shape
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBox\fP, and \fBCircle\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Shape\fP ()"
.br
.ti -1c
.RI "virtual const char * \fBGetType\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBPrint\fP (std::ostream &os) const =0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBShape\fP ()"
.br
.ti -1c
.RI "\fBShape\fP (double x, double y)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBx_\fP"
.br
.ti -1c
.RI "double \fBy_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename \fBArchiver\fP > \fBArchiver\fP & \fBoperator&\fP (\fBArchiver\fP &ar, \fBShape\fP &s)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual Shape::~Shape ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "Shape::Shape ()\fC [inline]\fP, \fC [protected]\fP"

.SS "Shape::Shape (double x, double y)\fC [inline]\fP, \fC [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual const char * Shape::GetType () const\fC [pure virtual]\fP"

.PP
Implemented in \fBCircle\fP, and \fBBox\fP\&.
.SS "virtual void Shape::Print (std::ostream & os) const\fC [pure virtual]\fP"

.PP
Implemented in \fBCircle\fP, and \fBBox\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename \fBArchiver\fP > \fBArchiver\fP & operator& (\fBArchiver\fP & ar, \fBShape\fP & s)\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "double Shape::x_\fC [protected]\fP"

.SS "double Shape::y_\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
