.TH "src/modules/Shooter.h" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/Shooter.h
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <list>\fP
.br
\fC#include '\&.\&./entities/projectiles/Projectile\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBShooter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
