.TH "src/rapidjson/test/unittest/simdtest.cpp" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/simdtest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/reader\&.h'\fP
.br
\fC#include 'rapidjson/writer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBScanCopyUnescapedStringHandler\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRAPIDJSON_NAMESPACE\fP   rapidjson_simd"
.br
.ti -1c
.RI "#define \fBSIMD_SUFFIX\fP(name)   name"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename StreamType > void \fBTestSkipWhitespace\fP ()"
.br
.ti -1c
.RI "\fBTEST\fP (SIMD, \fBSIMD_SUFFIX\fP(\fBSkipWhitespace\fP))"
.br
.ti -1c
.RI "\fBTEST\fP (SIMD, \fBSIMD_SUFFIX\fP(SkipWhitespace_EncodedMemoryStream))"
.br
.ti -1c
.RI "template<unsigned parseFlags, typename StreamType > void \fBTestScanCopyUnescapedString\fP ()"
.br
.ti -1c
.RI "\fBTEST\fP (SIMD, \fBSIMD_SUFFIX\fP(ScanCopyUnescapedString))"
.br
.ti -1c
.RI "\fBTEST\fP (SIMD, \fBSIMD_SUFFIX\fP(ScanWriteUnescapedString))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RAPIDJSON_NAMESPACE   rapidjson_simd"

.SS "#define SIMD_SUFFIX(name)   name"

.SH "Function Documentation"
.PP 
.SS "TEST (SIMD, \fBSIMD_SUFFIX\fP(ScanCopyUnescapedString))"

.SS "TEST (SIMD, \fBSIMD_SUFFIX\fP(ScanWriteUnescapedString))"

.SS "TEST (SIMD, \fBSIMD_SUFFIX\fP(\fBSkipWhitespace\fP))"

.SS "TEST (SIMD, \fBSIMD_SUFFIX\fP(SkipWhitespace_EncodedMemoryStream))"

.SS "template<unsigned parseFlags, typename StreamType > void TestScanCopyUnescapedString ()"

.SS "template<typename StreamType > void TestSkipWhitespace ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
