.TH "src/entities/Slime.h" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/entities/Slime.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Enemy\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSlime\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
