.TH "Slime" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Slime
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Slime\&.h>\fP
.PP
Inherits \fBEnemy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSlime\fP (float x, float y, float pathPointA, float pathPointB, bool moveRight)"
.br
.ti -1c
.RI "void \fBupdate\fP (float deltaSeconds) override"
.br
.RI "Implementacja wirtualnej metody update z \fBEnemy\&.h\fP\&. "
.ti -1c
.RI "void \fBrender\fP (sf::RenderTarget &window) override"
.br
.RI "Implementacja wirtualnej metody render z \fBEnemy\&.h\fP\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
przeciwnika, który porusza się poziomo od punktu A do B 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Slime::Slime (float x, float y, float pathPointA, float pathPointB, bool moveRight)\fC [explicit]\fP"
Konstruktor przeciwnika slime\&. x i y to pozycja na mapie, pathPointA i pathPointB określają zakres patrolu dla przeciwnika moveRight określa czy początkowo przeciwnik porusza się w lewo czy w prawo 
.SH "Member Function Documentation"
.PP 
.SS "void Slime::render (sf::RenderTarget & window)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implementacja wirtualnej metody render z \fBEnemy\&.h\fP\&. 
.PP
Implements \fBEnemy\fP\&.
.SS "void Slime::update (float deltaSeconds)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implementacja wirtualnej metody update z \fBEnemy\&.h\fP\&. 
.PP
Implements \fBEnemy\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
