.TH "src/rapidjson/include/rapidjson/internal/stack.h" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/internal/stack.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./allocators\&.h'\fP
.br
\fC#include 'swap\&.h'\fP
.br
\fC#include <cstddef>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBinternal::Stack< Allocator >\fP"
.br
.RI "A type-unsafe stack for storing different types of data\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinternal\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
