.TH "Stan" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stan
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
pierwszy poziom gry
.PP
drugi poziom gry
.PP
menu główne 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
