.TH "StdAllocator< T, BaseAllocator >::rebind< U >" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StdAllocator< T, BaseAllocator >::rebind< U >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <allocators\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBStdAllocator\fP< U, BaseAllocator > \fBother\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename \fBT\fP , typename BaseAllocator  = CrtAllocator> template<typename U > typedef \fBStdAllocator\fP<U, BaseAllocator> \fBStdAllocator\fP< \fBT\fP, BaseAllocator >::rebind< U >::other"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
