.TH "StreamTraits< GenericStringStream< Encoding > >" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StreamTraits< GenericStringStream< Encoding > >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBcopyOptimization\fP = 1 }"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "template<typename \fBEncoding\fP > anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIcopyOptimization \fP\fP


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
