.TH "src/rapidjson/include/rapidjson/stream.h" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/stream.h
.SH SYNOPSIS
.br
.PP
\fC#include 'rapidjson\&.h'\fP
.br
\fC#include 'encodings\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBStreamTraits< Stream >\fP"
.br
.RI "Provides additional information for stream\&. "
.ti -1c
.RI "class \fBGenericStreamWrapper< InputStream, Encoding >\fP"
.br
.RI "A Stream Wrapper\&. "
.ti -1c
.RI "struct \fBGenericStringStream< Encoding >\fP"
.br
.RI "Read-only string stream\&. "
.ti -1c
.RI "struct \fBStreamTraits< GenericStringStream< Encoding > >\fP"
.br
.ti -1c
.RI "struct \fBGenericInsituStringStream< Encoding >\fP"
.br
.RI "A read-write string stream\&. "
.ti -1c
.RI "struct \fBStreamTraits< GenericInsituStringStream< Encoding > >\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBGenericStringStream\fP< \fBUTF8\fP<> > \fBStringStream\fP"
.br
.RI "String stream with \fBUTF8\fP encoding\&. "
.ti -1c
.RI "typedef \fBGenericInsituStringStream\fP< \fBUTF8\fP<> > \fBInsituStringStream\fP"
.br
.RI "Insitu string stream with \fBUTF8\fP encoding\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename \fBStream\fP > void \fBPutReserve\fP (\fBStream\fP &stream, size_t count)"
.br
.RI "Reserve n characters for writing to a stream\&. "
.ti -1c
.RI "template<typename \fBStream\fP > void \fBPutUnsafe\fP (\fBStream\fP &stream, typename Stream::Ch c)"
.br
.RI "Write character to a stream, presuming buffer is reserved\&. "
.ti -1c
.RI "template<typename \fBStream\fP , typename Ch > void \fBPutN\fP (\fBStream\fP &stream, Ch c, size_t n)"
.br
.RI "Put N copies of a character to a stream\&. "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBGenericInsituStringStream\fP<\fBUTF8\fP<> > \fBInsituStringStream\fP"

.PP
Insitu string stream with \fBUTF8\fP encoding\&. 
.SS "typedef \fBGenericStringStream\fP<\fBUTF8\fP<> > \fBStringStream\fP"

.PP
String stream with \fBUTF8\fP encoding\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename \fBStream\fP , typename Ch > void PutN (\fBStream\fP & stream, Ch c, size_t n)\fC [inline]\fP"

.PP
Put N copies of a character to a stream\&. 
.SS "template<typename \fBStream\fP > void PutReserve (\fBStream\fP & stream, size_t count)\fC [inline]\fP"

.PP
Reserve n characters for writing to a stream\&. 
.SS "template<typename \fBStream\fP > void PutUnsafe (\fBStream\fP & stream, typename Stream::Ch c)\fC [inline]\fP"

.PP
Write character to a stream, presuming buffer is reserved\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
