.TH "src/rapidjson/include/rapidjson/internal/strfunc.h" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/internal/strfunc.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./stream\&.h'\fP
.br
\fC#include <cwchar>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinternal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename Ch > \fBSizeType\fP \fBinternal::StrLen\fP (const Ch *s)"
.br
.RI "Custom strlen() which works on different character types\&. "
.ti -1c
.RI "template<> \fBSizeType\fP \fBinternal::StrLen\fP (const char *s)"
.br
.ti -1c
.RI "template<> \fBSizeType\fP \fBinternal::StrLen\fP (const wchar_t *s)"
.br
.ti -1c
.RI "template<typename Ch > int \fBinternal::StrCmp\fP (const Ch *s1, const Ch *s2)"
.br
.RI "Custom strcmpn() which works on different character types\&. "
.ti -1c
.RI "template<typename \fBEncoding\fP > bool \fBinternal::CountStringCodePoint\fP (const typename Encoding::Ch *s, \fBSizeType\fP length, \fBSizeType\fP *outCount)"
.br
.RI "Returns number of code points in a encoded string\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
