.TH "src/rapidjson/test/unittest/strfunctest.cpp" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/strfunctest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/internal/strfunc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (StrFunc, CountStringCodePoint)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (StrFunc, CountStringCodePoint)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
