.TH "src/rapidjson/test/unittest/stringbuffertest.cpp" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/stringbuffertest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/stringbuffer\&.h'\fP
.br
\fC#include 'rapidjson/writer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBStringBuffer\fP, InitialSize)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBStringBuffer\fP, Put)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBStringBuffer\fP, PutN_Issue672)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBStringBuffer\fP, Clear)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBStringBuffer\fP, Push)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBStringBuffer\fP, Pop)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBStringBuffer\fP, GetLength_Issue744)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (\fBStringBuffer\fP, Clear)"

.SS "TEST (\fBStringBuffer\fP, GetLength_Issue744)"

.SS "TEST (\fBStringBuffer\fP, InitialSize)"

.SS "TEST (\fBStringBuffer\fP, Pop)"

.SS "TEST (\fBStringBuffer\fP, Push)"

.SS "TEST (\fBStringBuffer\fP, Put)"

.SS "TEST (\fBStringBuffer\fP, PutN_Issue672)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
