.TH "src/rapidjson/test/unittest/strtodtest.cpp" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/strtodtest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/internal/strtod\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBIGINTEGER_LITERAL\fP(s)   BigInteger(s, sizeof(s) \- 1)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (Strtod, CheckApproximationCase)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BIGINTEGER_LITERAL(s)   BigInteger(s, sizeof(s) \- 1)"

.SH "Function Documentation"
.PP 
.SS "TEST (Strtod, CheckApproximationCase)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
