.TH "src/rapidjson/include/rapidjson/internal/strtod.h" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/include/rapidjson/internal/strtod.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ieee754\&.h'\fP
.br
\fC#include 'biginteger\&.h'\fP
.br
\fC#include 'diyfp\&.h'\fP
.br
\fC#include 'pow10\&.h'\fP
.br
\fC#include <climits>\fP
.br
\fC#include <limits>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBinternal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBinternal::FastPath\fP (double significand, int exp)"
.br
.ti -1c
.RI "double \fBinternal::StrtodNormalPrecision\fP (double d, int p)"
.br
.ti -1c
.RI "template<typename \fBT\fP > \fBT\fP \fBinternal::Min3\fP (\fBT\fP \fBa\fP, \fBT\fP b, \fBT\fP c)"
.br
.ti -1c
.RI "int \fBinternal::CheckWithinHalfULP\fP (double b, const BigInteger &d, int dExp)"
.br
.ti -1c
.RI "bool \fBinternal::StrtodFast\fP (double d, int p, double *result)"
.br
.ti -1c
.RI "template<typename Ch > bool \fBinternal::StrtodDiyFp\fP (const Ch *decimals, int dLen, int dExp, double *result)"
.br
.ti -1c
.RI "template<typename Ch > double \fBinternal::StrtodBigInteger\fP (double approx, const Ch *decimals, int dLen, int dExp)"
.br
.ti -1c
.RI "template<typename Ch > double \fBinternal::StrtodFullPrecision\fP (double d, int p, const Ch *decimals, size_t length, size_t decimalPosition, int exp)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
