.TH "Student" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Student
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStudent\fP ()"
.br
.ti -1c
.RI "\fBStudent\fP (const std::string \fBname\fP, unsigned \fBage\fP, double \fBheight\fP, bool \fBcanSwim\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "unsigned \fBage\fP"
.br
.ti -1c
.RI "double \fBheight\fP"
.br
.ti -1c
.RI "bool \fBcanSwim\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Student::Student ()\fC [inline]\fP"

.SS "Student::Student (const std::string name, unsigned age, double height, bool canSwim)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned Student::age"

.SS "bool Student::canSwim"

.SS "double Student::height"

.SS "std::string Student::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
