.TH "TestStdAllocatorData" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestStdAllocatorData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestStdAllocatorData\fP (int &constructions, int &destructions)"
.br
.ti -1c
.RI "\fBTestStdAllocatorData\fP (const \fBTestStdAllocatorData\fP &rhs)"
.br
.ti -1c
.RI "\fBTestStdAllocatorData\fP & \fBoperator=\fP (const \fBTestStdAllocatorData\fP &rhs)"
.br
.ti -1c
.RI "\fB~TestStdAllocatorData\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TestStdAllocatorData::TestStdAllocatorData (int & constructions, int & destructions)\fC [inline]\fP"

.SS "TestStdAllocatorData::TestStdAllocatorData (const \fBTestStdAllocatorData\fP & rhs)\fC [inline]\fP"

.SS "TestStdAllocatorData::~TestStdAllocatorData ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBTestStdAllocatorData\fP & TestStdAllocatorData::operator= (const \fBTestStdAllocatorData\fP & rhs)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
