.TH "TileSetMap" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TileSetMap
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TileSetMap\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTileSetMap\fP (\fBrapidjson::Value\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "\fB~TileSetMap\fP ()"
.br
.RI "Destruktor kafelków mapy\&. "
.ti -1c
.RI "int \fBgetFirstGId\fP ()"
.br
.ti -1c
.RI "std::string \fBgetSource\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBfirstgid\fP"
.br
.RI "Zmienna reprezentująca pierwszy globalny identyfikator kafelka tego zestawu kafelków\&. "
.ti -1c
.RI "std::string \fBsource\fP"
.br
.RI "Zmienna przechowująca ścieżke do zestawu kafelków\&. "
.in -1c
.SH "Detailed Description"
.PP 
która ustawia kafelki na mape 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TileSetMap::TileSetMap (\fBrapidjson::Value\fP & value)\fC [inline]\fP"
Metoda która ustawia zmienne kafelków z pobranych wartości json 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP - wartości pobrane z json 
.RE
.PP

.SS "TileSetMap::~TileSetMap ()\fC [inline]\fP"

.PP
Destruktor kafelków mapy\&. 
.SH "Member Function Documentation"
.PP 
.SS "int TileSetMap::getFirstGId ()\fC [inline]\fP"
Metoda która zwraca informacje o pierwszy globalny identyfikator kafelka wybranego zestawu 
.PP
\fBReturns\fP
.RS 4
zwraca liczbe która reprezentuje id pierwszego kafelka w danym zestawie 
.RE
.PP

.SS "std::string TileSetMap::getSource ()\fC [inline]\fP"
Metoda która zwraca informacje ścieżke do pliku w którym przechowywanym jest zestaw kafelków 
.PP
\fBReturns\fP
.RS 4
zwraca ścieżke do zestawu kafelków 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "int TileSetMap::firstgid\fC [private]\fP"

.PP
Zmienna reprezentująca pierwszy globalny identyfikator kafelka tego zestawu kafelków\&. 
.SS "std::string TileSetMap::source\fC [private]\fP"

.PP
Zmienna przechowująca ścieżke do zestawu kafelków\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
