.TH "TileSet" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TileSet
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TileSet\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTileSet\fP ()"
.br
.RI "Konstruktor pusty\&. "
.ti -1c
.RI "\fBTileSet\fP (int firstgid, std::ifstream tileset)"
.br
.RI "Konstruktor który przyjmuje numer kafelka i jego tileset a nastepnie go parsuje\&. "
.ti -1c
.RI "\fB~TileSet\fP ()"
.br
.RI "Destruktor\&. "
.ti -1c
.RI "int \fBgetFirstGid\fP ()"
.br
.RI "Zwraca numer kafelka\&. "
.ti -1c
.RI "int \fBgetColumns\fP ()"
.br
.RI "Zwraca numer kolumny\&. "
.ti -1c
.RI "std::string \fBgetImage\fP ()"
.br
.RI "Zwraca informacje o obrazku kafelka\&. "
.ti -1c
.RI "int \fBgetImageHeight\fP ()"
.br
.RI "Zwraca wysokosc obrazka kafelka\&. "
.ti -1c
.RI "int \fBgetImageWidth\fP ()"
.br
.RI "Zwraca szerokosc obrazka kafelka\&. "
.ti -1c
.RI "int \fBgetMargin\fP ()"
.br
.RI "Zwraca margines\&. "
.ti -1c
.RI "std::string \fBgetName\fP ()"
.br
.RI "Zwraca nazwe\&. "
.ti -1c
.RI "int \fBgetSpacing\fP ()"
.br
.RI "Zwraca odstep\&. "
.ti -1c
.RI "int \fBgetTileCount\fP ()"
.br
.RI "Zwraca ilosc kafelkow\&. "
.ti -1c
.RI "std::string \fBgetTiledVersion\fP ()"
.br
.RI "Zwraca informacje o wersji kafelka\&. "
.ti -1c
.RI "int \fBgetTileHeight\fP ()"
.br
.RI "Zwraca wysokosc kafelka\&. "
.ti -1c
.RI "int \fBgetTileWidth\fP ()"
.br
.RI "Zwraca szerokosc kafelka\&. "
.ti -1c
.RI "std::string \fBgetType\fP ()"
.br
.RI "Zwraca typ\&. "
.ti -1c
.RI "float \fBgetVersion\fP ()"
.br
.RI "Zwraca numer wersji na której został stworzony kafelek\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TileSet::TileSet ()\fC [inline]\fP"

.PP
Konstruktor pusty\&. 
.SS "TileSet::TileSet (int firstgid, std::ifstream tileset)"

.PP
Konstruktor który przyjmuje numer kafelka i jego tileset a nastepnie go parsuje\&. 
.SS "TileSet::~TileSet ()\fC [default]\fP"

.PP
Destruktor\&. 
.SH "Member Function Documentation"
.PP 
.SS "int TileSet::getColumns ()\fC [inline]\fP"

.PP
Zwraca numer kolumny\&. 
.SS "int TileSet::getFirstGid ()\fC [inline]\fP"

.PP
Zwraca numer kafelka\&. 
.SS "std::string TileSet::getImage ()\fC [inline]\fP"

.PP
Zwraca informacje o obrazku kafelka\&. 
.SS "int TileSet::getImageHeight ()\fC [inline]\fP"

.PP
Zwraca wysokosc obrazka kafelka\&. 
.SS "int TileSet::getImageWidth ()\fC [inline]\fP"

.PP
Zwraca szerokosc obrazka kafelka\&. 
.SS "int TileSet::getMargin ()\fC [inline]\fP"

.PP
Zwraca margines\&. 
.SS "std::string TileSet::getName ()\fC [inline]\fP"

.PP
Zwraca nazwe\&. 
.SS "int TileSet::getSpacing ()\fC [inline]\fP"

.PP
Zwraca odstep\&. 
.SS "int TileSet::getTileCount ()\fC [inline]\fP"

.PP
Zwraca ilosc kafelkow\&. 
.SS "std::string TileSet::getTiledVersion ()\fC [inline]\fP"

.PP
Zwraca informacje o wersji kafelka\&. 
.SS "int TileSet::getTileHeight ()\fC [inline]\fP"

.PP
Zwraca wysokosc kafelka\&. 
.SS "int TileSet::getTileWidth ()\fC [inline]\fP"

.PP
Zwraca szerokosc kafelka\&. 
.SS "std::string TileSet::getType ()\fC [inline]\fP"

.PP
Zwraca typ\&. 
.SS "float TileSet::getVersion ()\fC [inline]\fP"

.PP
Zwraca numer wersji na której został stworzony kafelek\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
