.TH "TileMap" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TileMap
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TileMap\&.h>\fP
.PP
Inherits sf::Drawable, and sf::Transformable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBload\fP (\fBTileSet\fP tileset, \fBLayer\fP layer)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBdraw\fP (sf::RenderTarget &target, sf::RenderStates states) const"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "sf::VertexArray \fBverts\fP"
.br
.RI "Tablica która przechowuje wierzchołki\&. "
.ti -1c
.RI "sf::Texture \fBtex\fP"
.br
.RI "Przechowuje teksture kafelków\&. "
.in -1c
.SH "Detailed Description"
.PP 
, która przechowuje kafelki i je wczytuje 
.SH "Member Function Documentation"
.PP 
.SS "virtual void TileMap::draw (sf::RenderTarget & target, sf::RenderStates states) const\fC [inline]\fP, \fC [private]\fP, \fC [virtual]\fP"
Wirtualna metoda, który służy do przenoszenia elemntów do wyrenderowania na ekran 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP - element do wyrenderowania 
.br
\fIstates\fP - stany używane do renderowania 
.RE
.PP

.SS "bool TileMap::load (\fBTileSet\fP tileset, \fBLayer\fP layer)\fC [inline]\fP"
Służy do ładowania kafelków użytych w wskazanej przez parametr warstwie 
.PP
\fBParameters\fP
.RS 4
\fItileset\fP - obiekt z kafelkami 
.br
\fIlayer\fP - warstwa 
.RE
.PP
\fBReturns\fP
.RS 4
zwraca true w przypadku załadowania poprawnego lub false w przypadku niepowodzenia 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "sf::Texture TileMap::tex\fC [private]\fP"

.PP
Przechowuje teksture kafelków\&. 
.SS "sf::VertexArray TileMap::verts\fC [private]\fP"

.PP
Tablica która przechowuje wierzchołki\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
