.TH "TileSetMap" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TileSetMap
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TileSetMap\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTileSetMap\fP (\fBrapidjson::Value\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "\fB~TileSetMap\fP ()"
.br
.ti -1c
.RI "int \fBgetFirstGId\fP ()"
.br
.ti -1c
.RI "std::string \fBgetSource\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TileSetMap::TileSetMap (\fBrapidjson::Value\fP & value)\fC [inline]\fP"

.SS "TileSetMap::~TileSetMap ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int TileSetMap::getFirstGId ()\fC [inline]\fP"

.SS "std::string TileSetMap::getSource ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
