.TH "Traits< uint32_t >" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Traits< uint32_t >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBkBufferSize\fP = 11 }"
.br
.ti -1c
.RI "enum { \fBkMaxDigit\fP = 10 }"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBuint32_t\fP \fBNegate\fP (\fBuint32_t\fP x)"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIkBufferSize \fP\fP
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIkMaxDigit \fP\fP
.SH "Member Function Documentation"
.PP 
.SS "static \fBuint32_t\fP \fBTraits\fP< \fBuint32_t\fP >::Negate (\fBuint32_t\fP x)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
