.TH "Transcoder< Encoding, Encoding >" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transcoder< Encoding, Encoding > \- Specialization of \fBTranscoder\fP with same source and target encoding\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <encodings\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE bool \fBTranscode\fP (InputStream &is, OutputStream &os)"
.br
.ti -1c
.RI "template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE bool \fBTranscodeUnsafe\fP (InputStream &is, OutputStream &os)"
.br
.ti -1c
.RI "template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE bool \fBValidate\fP (InputStream &is, OutputStream &os)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename \fBEncoding\fP>
.br
struct Transcoder< Encoding, Encoding >"Specialization of \fBTranscoder\fP with same source and target encoding\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename \fBEncoding\fP > template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE bool \fBTranscoder\fP< \fBEncoding\fP, \fBEncoding\fP >::Transcode (InputStream & is, OutputStream & os)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename \fBEncoding\fP > template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE bool \fBTranscoder\fP< \fBEncoding\fP, \fBEncoding\fP >::TranscodeUnsafe (InputStream & is, OutputStream & os)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename \fBEncoding\fP > template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE bool \fBTranscoder\fP< \fBEncoding\fP, \fBEncoding\fP >::Validate (InputStream & is, OutputStream & os)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
