.TH "src/rapidjson/example/traverseaspointer.cpp" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/example/traverseaspointer.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'rapidjson/document\&.h'\fP
.br
\fC#include 'rapidjson/filereadstream\&.h'\fP
.br
\fC#include 'rapidjson/pointer\&.h'\fP
.br
\fC#include 'rapidjson/stringbuffer\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtraverse\fP (const \fBValue\fP &v, const \fBPointer\fP &p)"
.br
.ti -1c
.RI "int \fBmain\fP (int, char *[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int, char *[])"

.SS "void traverse (const \fBValue\fP & v, const \fBPointer\fP & p)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
