.TH "src/rapidjson/test/unittest/unittest.h" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/unittest.h
.SH SYNOPSIS
.br
.PP
\fC#include 'gtest/gtest\&.h'\fP
.br
\fC#include <stdexcept>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAssertException\fP"
.br
.ti -1c
.RI "class \fBRandom\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__STDC_CONSTANT_MACROS\fP   1"
.br
.ti -1c
.RI "#define \fBRAPIDJSON_HAS_CXX11_NOEXCEPT\fP   0"
.br
.ti -1c
.RI "#define \fBRAPIDJSON_ASSERT\fP(x)   (!(x) ? throw \fBAssertException\fP(RAPIDJSON_STRINGIFY(x)) : (void)0u)"
.br
.ti -1c
.RI "#define \fBRAPIDJSON_ASSERT_THROWS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename Ch > unsigned \fBStrLen\fP (const Ch *s)"
.br
.ti -1c
.RI "template<typename Ch > int \fBStrCmp\fP (const Ch *s1, const Ch *s2)"
.br
.ti -1c
.RI "template<typename Ch > Ch * \fBStrDup\fP (const Ch *str)"
.br
.ti -1c
.RI "FILE * \fBTempFile\fP (char *filename)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __STDC_CONSTANT_MACROS   1"

.SS "#define RAPIDJSON_ASSERT(x)   (!(x) ? throw \fBAssertException\fP(RAPIDJSON_STRINGIFY(x)) : (void)0u)"

.SS "#define RAPIDJSON_ASSERT_THROWS"

.SS "#define RAPIDJSON_HAS_CXX11_NOEXCEPT   0"

.SH "Function Documentation"
.PP 
.SS "template<typename Ch > int StrCmp (const Ch * s1, const Ch * s2)\fC [inline]\fP"

.SS "template<typename Ch > Ch * StrDup (const Ch * str)\fC [inline]\fP"

.SS "template<typename Ch > unsigned StrLen (const Ch * s)\fC [inline]\fP"

.SS "FILE * TempFile (char * filename)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
