.TH "src/rapidjson/test/unittest/uritest.cpp" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/rapidjson/test/unittest/uritest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'unittest\&.h'\fP
.br
\fC#include 'rapidjson/document\&.h'\fP
.br
\fC#include 'rapidjson/uri\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRAPIDJSON_SCHEMA_VERBOSE\fP   0"
.br
.ti -1c
.RI "#define \fBRAPIDJSON_HAS_STDSTRING\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (\fBUri\fP, DefaultConstructor)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBUri\fP, Parse)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBUri\fP, Parse_UTF16)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBUri\fP, CopyConstructor)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBUri\fP, Assignment)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBUri\fP, Resolve)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBUri\fP, Resolve_UTF16)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBUri\fP, Equals)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBUri\fP, Match)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBUri\fP, Issue1899)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RAPIDJSON_HAS_STDSTRING   1"

.SS "#define RAPIDJSON_SCHEMA_VERBOSE   0"

.SH "Function Documentation"
.PP 
.SS "TEST (\fBUri\fP, Assignment)"

.SS "TEST (\fBUri\fP, CopyConstructor)"

.SS "TEST (\fBUri\fP, DefaultConstructor)"

.SS "TEST (\fBUri\fP, Equals)"

.SS "TEST (\fBUri\fP, Issue1899)"

.SS "TEST (\fBUri\fP, Match)"

.SS "TEST (\fBUri\fP, Parse)"

.SS "TEST (\fBUri\fP, Parse_UTF16)"

.SS "TEST (\fBUri\fP, Resolve)"

.SS "TEST (\fBUri\fP, Resolve_UTF16)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
