.TH "UTF32BE< CharType >" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UTF32BE< CharType > \- UTF-32 big endian encoding\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <encodings\&.h>\fP
.PP
Inherits \fBUTF32< unsigned >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename InputByteStream > static CharType \fBTakeBOM\fP (InputByteStream &is)"
.br
.ti -1c
.RI "template<typename InputByteStream > static CharType \fBTake\fP (InputByteStream &is)"
.br
.ti -1c
.RI "template<typename OutputByteStream > static void \fBPutBOM\fP (OutputByteStream &os)"
.br
.ti -1c
.RI "template<typename OutputByteStream > static void \fBPut\fP (OutputByteStream &os, CharType c)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename CharType = unsigned>
.br
struct UTF32BE< CharType >"UTF-32 big endian encoding\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename CharType  = unsigned> template<typename OutputByteStream > static void \fBUTF32BE\fP< CharType >::Put (OutputByteStream & os, CharType c)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename CharType  = unsigned> template<typename OutputByteStream > static void \fBUTF32BE\fP< CharType >::PutBOM (OutputByteStream & os)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename CharType  = unsigned> template<typename InputByteStream > static CharType \fBUTF32BE\fP< CharType >::Take (InputByteStream & is)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename CharType  = unsigned> template<typename InputByteStream > static CharType \fBUTF32BE\fP< CharType >::TakeBOM (InputByteStream & is)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
