.TH "ValueCounter" 3 "Fri Jan 14 2022" "Version 1.0.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ValueCounter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseReaderHandler< Encoding, Derived >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValueCounter\fP ()"
.br
.ti -1c
.RI "bool \fBEndObject\fP (\fBSizeType\fP memberCount)"
.br
.ti -1c
.RI "bool \fBEndArray\fP (\fBSizeType\fP elementCount)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSizeType\fP \fBcount_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ValueCounter::ValueCounter ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ValueCounter::EndArray (\fBSizeType\fP elementCount)\fC [inline]\fP"

.SS "bool ValueCounter::EndObject (\fBSizeType\fP memberCount)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBSizeType\fP ValueCounter::count_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
