.TH "WIStreamWrapper" 3 "Fri Jan 21 2022" "Version 1.0" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WIStreamWrapper
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef wchar_t \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWIStreamWrapper\fP (std::wistream &is)"
.br
.ti -1c
.RI "\fBCh\fP \fBPeek\fP () const"
.br
.ti -1c
.RI "\fBCh\fP \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP () const"
.br
.ti -1c
.RI "\fBCh\fP * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "void \fBPut\fP (\fBCh\fP)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (\fBCh\fP *)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBWIStreamWrapper\fP (const \fBWIStreamWrapper\fP &)"
.br
.ti -1c
.RI "\fBWIStreamWrapper\fP & \fBoperator=\fP (const \fBWIStreamWrapper\fP &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::wistream & \fBis_\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "typedef wchar_t \fBWIStreamWrapper::Ch\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "WIStreamWrapper::WIStreamWrapper (std::wistream & is)\fC [inline]\fP"

.SS "WIStreamWrapper::WIStreamWrapper (const \fBWIStreamWrapper\fP &)\fC [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void WIStreamWrapper::Flush ()\fC [inline]\fP"

.SS "\fBWIStreamWrapper\fP & WIStreamWrapper::operator= (const \fBWIStreamWrapper\fP &)\fC [private]\fP"

.SS "\fBCh\fP WIStreamWrapper::Peek () const\fC [inline]\fP"

.SS "void WIStreamWrapper::Put (\fBCh\fP)\fC [inline]\fP"

.SS "\fBCh\fP * WIStreamWrapper::PutBegin ()\fC [inline]\fP"

.SS "size_t WIStreamWrapper::PutEnd (\fBCh\fP *)\fC [inline]\fP"

.SS "\fBCh\fP WIStreamWrapper::Take ()\fC [inline]\fP"

.SS "size_t WIStreamWrapper::Tell () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::wistream& WIStreamWrapper::is_\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
