.TH "Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Level" 3 "Fri Jan 21 2022" "Neon Jumper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Level \- Information for each nested level\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <writer\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevel\fP (bool inArray_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBvalueCount\fP"
.br
.RI "number of values in this level "
.ti -1c
.RI "bool \fBinArray\fP"
.br
.RI "true if in array, otherwise in object "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags>
.br
struct Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Level"Information for each nested level\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename OutputStream , typename SourceEncoding  = UTF8<>, typename TargetEncoding  = UTF8<>, typename StackAllocator  = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> \fBWriter\fP< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Level::Level (bool inArray_)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename OutputStream , typename SourceEncoding  = UTF8<>, typename TargetEncoding  = UTF8<>, typename StackAllocator  = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool \fBWriter\fP< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Level::inArray"

.PP
true if in array, otherwise in object 
.SS "template<typename OutputStream , typename SourceEncoding  = UTF8<>, typename TargetEncoding  = UTF8<>, typename StackAllocator  = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> size_t \fBWriter\fP< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Level::valueCount"

.PP
number of values in this level 

.SH "Author"
.PP 
Generated automatically by Doxygen for Neon Jumper from the source code\&.
